import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "avihayil",
    "name_he": "אביחיל",
    "name_en": "Avihayil",
    "lat": 32.350121,
    "lng": 34.872008,
    "region": "center",
    "type": "town"
  },
  {
    "id": "even_yehuda",
    "name_he": "אבן יהודה",
    "name_en": "Even Yehuda",
    "lat": 32.2727,
    "lng": 34.8867,
    "region": "center",
    "type": "local_council"
  },
  {
    "id": "udim",
    "name_he": "אודים",
    "name_en": "Udim",
    "lat": 32.264677,
    "lng": 34.846176,
    "region": "center",
    "type": "town"
  },
  {
    "id": "omez",
    "name_he": "אומץ",
    "name_en": "Omez",
    "lat": 32.370334,
    "lng": 34.994141,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ahituv",
    "name_he": "אחיטוב",
    "name_en": "Ahituv",
    "lat": 32.387757,
    "lng": 34.990728,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ahisamakh",
    "name_he": "אחיסמך",
    "name_en": "Ahisamakh",
    "lat": 31.934175,
    "lng": 34.907108,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ahiezer",
    "name_he": "אחיעזר",
    "name_en": "Ahi'ezer",
    "lat": 31.981216,
    "lng": 34.871768,
    "region": "center",
    "type": "town"
  },
  {
    "id": "eyal",
    "name_he": "אייל",
    "name_en": "Eyal",
    "lat": 32.210881,
    "lng": 34.97915,
    "region": "center",
    "type": "town"
  },
  {
    "id": "irus",
    "name_he": "אירוס",
    "name_en": "Irus",
    "lat": 31.928193,
    "lng": 34.776189,
    "region": "center",
    "type": "town"
  },
  {
    "id": "elyakhin",
    "name_he": "אליכין",
    "name_en": "Elyakhin",
    "lat": 32.407715,
    "lng": 34.924829,
    "region": "center",
    "type": "town"
  },
  {
    "id": "elyashiv",
    "name_he": "אלישיב",
    "name_en": "Elyashiv",
    "lat": 32.378989,
    "lng": 34.909469,
    "region": "center",
    "type": "town"
  },
  {
    "id": "elishama",
    "name_he": "אלישמע",
    "name_en": "Elishama",
    "lat": 32.152282,
    "lng": 34.928174,
    "region": "center",
    "type": "town"
  },
  {
    "id": "elad",
    "name_he": "אלעד",
    "name_en": "El'ad",
    "lat": 32.050679,
    "lng": 34.956965,
    "region": "center",
    "type": "town"
  },
  {
    "id": "arsuf",
    "name_he": "ארסוף",
    "name_en": "Arsuf",
    "lat": 31.621529,
    "lng": 34.925555,
    "region": "center",
    "type": "town"
  },
  {
    "id": "beerot_yizhaq",
    "name_he": "בארות יצחק",
    "name_en": "Be'erot Yizhaq",
    "lat": 32.041383,
    "lng": 34.910173,
    "region": "center",
    "type": "town"
  },
  {
    "id": "beerotayim",
    "name_he": "בארותיים",
    "name_en": "Be'erotayim",
    "lat": 32.321491,
    "lng": 34.985355,
    "region": "center",
    "type": "town"
  },
  {
    "id": "burgeta",
    "name_he": "בורגתה",
    "name_en": "Burgeta",
    "lat": 32.324382,
    "lng": 34.962448,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bahan",
    "name_he": "בחן",
    "name_en": "Bahan",
    "lat": 32.350906,
    "lng": 35.019806,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_elazari",
    "name_he": "בית אלעזרי",
    "name_en": "Bet El'azari",
    "lat": 31.844556,
    "lng": 34.803262,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_berl",
    "name_he": "בית ברל",
    "name_en": "Bet Berl",
    "lat": 32.201362,
    "lng": 34.926663,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_gamliel",
    "name_he": "בית גמליאל",
    "name_en": "Bet Gamli'el",
    "lat": 31.857185,
    "lng": 34.761382,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_dagan",
    "name_he": "בית דגן",
    "name_en": "Bet Dagan",
    "lat": 31.999238,
    "lng": 34.825829,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_halevi",
    "name_he": "בית הלוי",
    "name_en": "Bet Halevi",
    "lat": 32.353598,
    "lng": 34.931811,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_herut",
    "name_he": "בית חירות",
    "name_en": "Bet Herut",
    "lat": 32.380024,
    "lng": 34.867692,
    "region": "center",
    "type": "town",
    "aliases": [
      "בית חרות"
    ]
  },
  {
    "id": "bet_hilqiyya",
    "name_he": "בית חלקיה",
    "name_en": "Bet Hilqiyya",
    "lat": 31.791937,
    "lng": 34.811801,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_hanan",
    "name_he": "בית חנן",
    "name_en": "Bet Hanan",
    "lat": 31.931328,
    "lng": 34.771786,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_hashmonay",
    "name_he": "בית חשמונאי",
    "name_en": "Bet Hashmonay",
    "lat": 31.888618,
    "lng": 34.919288,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_yehoshua",
    "name_he": "בית יהושע",
    "name_en": "Bet Yehoshua",
    "lat": 32.260275,
    "lng": 34.863999,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_yannay",
    "name_he": "בית ינאי",
    "name_en": "Bet Yannay",
    "lat": 32.379898,
    "lng": 34.863327,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_yizhaq_sh_hefer",
    "name_he": "בית יצחק-שער חפר",
    "name_en": "Bet Yizhaq-Sh. Hefer",
    "lat": 32.333792,
    "lng": 34.89053,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_nehemya",
    "name_he": "בית נחמיה",
    "name_en": "Bet Nehemya",
    "lat": 31.975378,
    "lng": 34.955487,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_oved",
    "name_he": "בית עובד",
    "name_en": "Bet Oved",
    "lat": 31.922,
    "lng": 34.774007,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_uzziel",
    "name_he": "בית עוזיאל",
    "name_en": "Bet Uzzi'el",
    "lat": 31.870761,
    "lng": 34.905902,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_arif",
    "name_he": "בית עריף",
    "name_en": "Bet Arif",
    "lat": 31.995789,
    "lng": 34.934473,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bet_rabban",
    "name_he": "בית רבן",
    "name_en": "Bet Rabban",
    "lat": 31.817234,
    "lng": 34.729393,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bitan_aharon",
    "name_he": "ביתן אהרן",
    "name_en": "Bitan Aharon",
    "lat": 32.364545,
    "lng": 34.870646,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ben_zakkay",
    "name_he": "בן זכאי",
    "name_en": "Ben Zakkay",
    "lat": 31.856337,
    "lng": 34.728036,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ben_shemen_k_noar",
    "name_he": "בן שמן (כפר נוער)",
    "name_en": "Ben Shemen(k.no'ar)",
    "lat": 31.959816,
    "lng": 34.927766,
    "region": "center",
    "type": "town",
    "aliases": [
      "בן שמן"
    ]
  },
  {
    "id": "ben_shemen_moshav",
    "name_he": "בן שמן (מושב)",
    "name_en": "Ben Shemen (moshav)",
    "lat": 31.952202,
    "lng": 34.921655,
    "region": "center",
    "type": "moshav"
  },
  {
    "id": "bene_darom",
    "name_he": "בני דרום",
    "name_en": "Bene Darom",
    "lat": 31.820256,
    "lng": 34.69226,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bene_deror",
    "name_he": "בני דרור",
    "name_en": "Bene Deror",
    "lat": 32.262039,
    "lng": 34.898571,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bene_atarot",
    "name_he": "בני עטרות",
    "name_en": "Bene Atarot",
    "lat": 32.024192,
    "lng": 34.913739,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bene_ayish",
    "name_he": "בני עי\"ש",
    "name_en": "Bene Ayish",
    "lat": 31.789206,
    "lng": 34.760498,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bene_ziyyon",
    "name_he": "בני ציון",
    "name_en": "Bene Ziyyon",
    "lat": 32.220128,
    "lng": 34.869724,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bene_reem",
    "name_he": "בני ראם",
    "name_en": "Bene Re'em",
    "lat": 31.769735,
    "lng": 34.791045,
    "region": "center",
    "type": "town"
  },
  {
    "id": "benaya",
    "name_he": "בניה",
    "name_en": "Benaya",
    "lat": 31.843511,
    "lng": 34.752569,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bazra",
    "name_he": "בצרה",
    "name_en": "Bazra",
    "lat": 32.213806,
    "lng": 34.879348,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bareqet",
    "name_he": "ברקת",
    "name_en": "Bareqet",
    "lat": 32.015278,
    "lng": 34.945504,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bat_hen",
    "name_he": "בת חן",
    "name_en": "Bat Hen",
    "lat": 32.360281,
    "lng": 34.87191,
    "region": "center",
    "type": "town"
  },
  {
    "id": "bat_hefer",
    "name_he": "בת חפר",
    "name_en": "Bat Hefer",
    "lat": 32.333441,
    "lng": 35.013421,
    "region": "center",
    "type": "town"
  },
  {
    "id": "jaljulye",
    "name_he": "ג'לג'וליה",
    "name_en": "Jaljulye",
    "lat": 32.150873,
    "lng": 34.954995,
    "region": "center",
    "type": "town"
  },
  {
    "id": "geule_teman",
    "name_he": "גאולי תימן",
    "name_en": "Ge'ule Teman",
    "lat": 32.39101,
    "lng": 34.901487,
    "region": "center",
    "type": "town"
  },
  {
    "id": "geulim",
    "name_he": "גאולים",
    "name_en": "Ge'ulim",
    "lat": 32.297227,
    "lng": 34.949596,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gealya",
    "name_he": "גאליה",
    "name_en": "Ge'alya",
    "lat": 31.884261,
    "lng": 34.765897,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_brenner",
    "name_he": "גבעת ברנר",
    "name_en": "Giv'at Brenner",
    "lat": 31.867698,
    "lng": 34.800925,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_hashelosha",
    "name_he": "גבעת השלושה",
    "name_en": "Giv'at Hashelosha",
    "lat": 32.098828,
    "lng": 34.922131,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_hen",
    "name_he": "גבעת ח\"ן",
    "name_en": "Giv'at Hen",
    "lat": 32.168745,
    "lng": 34.878022,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_hayyim_ihud",
    "name_he": "גבעת חיים (איחוד)",
    "name_en": "Giv'at Hayyim (ihud)",
    "lat": 32.399456,
    "lng": 34.93316,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_hayyim_meuha",
    "name_he": "גבעת חיים (מאוחד)",
    "name_en": "Giv'at Hayyim(me'uha",
    "lat": 32.391706,
    "lng": 34.931351,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_koah",
    "name_he": "גבעת כ\"ח",
    "name_en": "Giv'at Koah",
    "lat": 32.03102,
    "lng": 34.935872,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_shemuel",
    "name_he": "גבעת שמואל",
    "name_en": "Giv'at Shemu'el",
    "lat": 32.077029,
    "lng": 34.850874,
    "region": "center",
    "type": "town"
  },
  {
    "id": "givat_shappira",
    "name_he": "גבעת שפירא",
    "name_en": "Giv'at Shappira",
    "lat": 32.357601,
    "lng": 34.87693,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gezer",
    "name_he": "גזר",
    "name_en": "Gezer",
    "lat": 31.876364,
    "lng": 34.920487,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gibbeton",
    "name_he": "גיבתון",
    "name_en": "Gibbeton",
    "lat": 31.888734,
    "lng": 34.799937,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ginnaton",
    "name_he": "גינתון",
    "name_en": "Ginnaton",
    "lat": 31.963279,
    "lng": 34.913769,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gimzo",
    "name_he": "גמזו",
    "name_en": "Gimzo",
    "lat": 31.928172,
    "lng": 34.940703,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gan_hadarom",
    "name_he": "גן הדרום",
    "name_en": "Gan Hadarom",
    "lat": 31.80399,
    "lng": 34.700926,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gan_hayyim",
    "name_he": "גן חיים",
    "name_en": "Gan Hayyim",
    "lat": 32.19511,
    "lng": 34.905892,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gan_yoshiyya",
    "name_he": "גן יאשיה",
    "name_en": "Gan Yoshiyya",
    "lat": 32.350288,
    "lng": 34.993721,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gan_soreq",
    "name_he": "גן שורק",
    "name_en": "Gan Soreq",
    "lat": 31.944559,
    "lng": 34.75874,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gan_shelomo",
    "name_he": "גן שלמה",
    "name_en": "Gan Shelomo",
    "lat": 31.878204,
    "lng": 34.798241,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gannot",
    "name_he": "גנות",
    "name_en": "Gannot",
    "lat": 32.017901,
    "lng": 34.828601,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gannot_hadar",
    "name_he": "גנות הדר",
    "name_en": "Gannot Hadar",
    "lat": 32.320886,
    "lng": 34.90107,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ganne_hadar",
    "name_he": "גני הדר",
    "name_en": "Ganne Hadar",
    "lat": 31.879023,
    "lng": 34.853918,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ganne_tal",
    "name_he": "גני טל",
    "name_en": "Ganne Tal",
    "lat": 31.788215,
    "lng": 34.792481,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ganne_yohanan",
    "name_he": "גני יוחנן",
    "name_en": "Ganne Yohanan",
    "lat": 31.858828,
    "lng": 34.844123,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ganne_am",
    "name_he": "גני עם",
    "name_en": "Ganne Am",
    "lat": 32.151074,
    "lng": 34.902395,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ganne_tiqwa",
    "name_he": "גני תקווה",
    "name_en": "Ganne Tiqwa",
    "lat": 32.061128,
    "lng": 34.875452,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gaash",
    "name_he": "געש",
    "name_en": "Ga'ash",
    "lat": 32.228993,
    "lng": 34.825878,
    "region": "center",
    "type": "town"
  },
  {
    "id": "gat_rimmon",
    "name_he": "גת רימון",
    "name_en": "Gat Rimmon",
    "lat": 32.068472,
    "lng": 34.880056,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hadar_am",
    "name_he": "הדר עם",
    "name_en": "Hadar Am",
    "lat": 32.349145,
    "lng": 34.901544,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hod_hasharon",
    "name_he": "הוד השרון",
    "name_en": "Hod HaSharon",
    "lat": 32.1509,
    "lng": 34.8924,
    "region": "center",
    "type": "city"
  },
  {
    "id": "hamapil",
    "name_he": "המעפיל",
    "name_en": "Hama'pil",
    "lat": 32.378031,
    "lng": 34.983335,
    "region": "center",
    "type": "town"
  },
  {
    "id": "haogen",
    "name_he": "העוגן",
    "name_en": "Haogen",
    "lat": 32.362354,
    "lng": 34.92376,
    "region": "center",
    "type": "town"
  },
  {
    "id": "herzliya",
    "name_he": "הרצליה",
    "name_en": "Herzliya",
    "lat": 32.1629,
    "lng": 34.7915,
    "region": "center",
    "type": "city"
  },
  {
    "id": "zetan",
    "name_he": "זיתן",
    "name_en": "Zetan",
    "lat": 31.975634,
    "lng": 34.890156,
    "region": "center",
    "type": "town"
  },
  {
    "id": "zemer",
    "name_he": "זמר",
    "name_en": "Zemer",
    "lat": 32.364041,
    "lng": 35.036784,
    "region": "center",
    "type": "town"
  },
  {
    "id": "havazzelet_hasharon",
    "name_he": "חבצלת השרון",
    "name_en": "Havazzelet Hasharon",
    "lat": 32.36082,
    "lng": 34.862812,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hagor",
    "name_he": "חגור",
    "name_en": "Hagor",
    "lat": 32.138169,
    "lng": 34.947248,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hogla",
    "name_he": "חגלה",
    "name_en": "Hogla",
    "lat": 32.387195,
    "lng": 34.925499,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hadid",
    "name_he": "חדיד",
    "name_en": "Hadid",
    "lat": 31.968879,
    "lng": 34.93129,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hulda",
    "name_he": "חולדה",
    "name_en": "Hulda",
    "lat": 31.831076,
    "lng": 34.882666,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hofit",
    "name_he": "חופית",
    "name_en": "Hofit",
    "lat": 32.385539,
    "lng": 34.875368,
    "region": "center",
    "type": "town"
  },
  {
    "id": "horeshim",
    "name_he": "חורשים",
    "name_en": "Horeshim",
    "lat": 32.138202,
    "lng": 34.970596,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hibbat_ziyyon",
    "name_he": "חיבת ציון",
    "name_en": "Hibbat Ziyyon",
    "lat": 32.397661,
    "lng": 34.912784,
    "region": "center",
    "type": "town"
  },
  {
    "id": "herut",
    "name_he": "חירות",
    "name_en": "Herut",
    "lat": 32.239731,
    "lng": 34.915719,
    "region": "center",
    "type": "town",
    "aliases": [
      "חרות"
    ]
  },
  {
    "id": "hemed",
    "name_he": "חמד",
    "name_en": "Hemed",
    "lat": 32.018449,
    "lng": 34.840042,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hanniel",
    "name_he": "חניאל",
    "name_en": "Hanni'el",
    "lat": 32.332543,
    "lng": 34.948174,
    "region": "center",
    "type": "town"
  },
  {
    "id": "hafez_hayyim",
    "name_he": "חפץ חיים",
    "name_en": "Hafez Hayyim",
    "lat": 31.789088,
    "lng": 34.800554,
    "region": "center",
    "type": "town"
  },
  {
    "id": "herev_leet",
    "name_he": "חרב לאת",
    "name_en": "Herev Le'et",
    "lat": 32.401169,
    "lng": 34.908815,
    "region": "center",
    "type": "town"
  },
  {
    "id": "haruzim",
    "name_he": "חרוצים",
    "name_en": "Haruzim",
    "lat": 32.227422,
    "lng": 34.864824,
    "region": "center",
    "type": "town"
  },
  {
    "id": "tayibe",
    "name_he": "טייבה",
    "name_en": "Tayibe",
    "lat": 32.26182,
    "lng": 35.005441,
    "region": "center",
    "type": "town"
  },
  {
    "id": "tire",
    "name_he": "טירה",
    "name_en": "Tire",
    "lat": 32.234094,
    "lng": 34.956619,
    "region": "center",
    "type": "town"
  },
  {
    "id": "tirat_yehuda",
    "name_he": "טירת יהודה",
    "name_en": "Tirat Yehuda",
    "lat": 32.013299,
    "lng": 34.933399,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yavne",
    "name_he": "יבנה",
    "name_en": "Yavne",
    "lat": 31.88,
    "lng": 34.7394,
    "region": "center",
    "type": "city"
  },
  {
    "id": "yagel",
    "name_he": "יגל",
    "name_en": "Yagel",
    "lat": 31.988363,
    "lng": 34.879006,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yad_binyamin",
    "name_he": "יד בנימין",
    "name_en": "Yad Binyamin",
    "lat": 31.797364,
    "lng": 34.821976,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yad_hanna",
    "name_he": "יד חנה",
    "name_en": "Yad Hanna",
    "lat": 32.325864,
    "lng": 35.006056,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yad_rambam",
    "name_he": "יד רמב\"ם",
    "name_en": "Yad Rambam",
    "lat": 31.900001,
    "lng": 34.900052,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yehud_monoson",
    "name_he": "יהוד-מונוסון",
    "name_en": "Yehud-Monoson",
    "lat": 32.031983,
    "lng": 34.887664,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yanuv",
    "name_he": "ינוב",
    "name_en": "Yanuv",
    "lat": 32.305356,
    "lng": 34.948801,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yesodot",
    "name_he": "יסודות",
    "name_en": "Yesodot",
    "lat": 31.81544,
    "lng": 34.86496,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yeaf",
    "name_he": "יעף",
    "name_en": "Ye'af",
    "lat": 32.267836,
    "lng": 34.966199,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yaziz",
    "name_he": "יציץ",
    "name_en": "Yaziz",
    "lat": 31.863735,
    "lng": 34.861536,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yaqum",
    "name_he": "יקום",
    "name_en": "Yaqum",
    "lat": 32.247966,
    "lng": 34.841955,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yarhiv",
    "name_he": "ירחיב",
    "name_en": "Yarhiv",
    "lat": 32.153488,
    "lng": 34.969029,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yarqona",
    "name_he": "ירקונה",
    "name_en": "Yarqona",
    "lat": 32.144731,
    "lng": 34.897364,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yashresh",
    "name_he": "ישרש",
    "name_en": "Yashresh",
    "lat": 31.91494,
    "lng": 34.848398,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kochav_yair_tsur_yi",
    "name_he": "כוכב יאיר",
    "name_en": "Kochav Yair Tsur Yi",
    "lat": 32.221389,
    "lng": 34.994916,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_aviv",
    "name_he": "כפר אביב",
    "name_en": "Kefar Aviv",
    "lat": 31.830988,
    "lng": 34.721011,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_bilu",
    "name_he": "כפר ביל\"ו",
    "name_en": "Kefar Bilu",
    "lat": 31.872968,
    "lng": 34.82606,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_bin_nun",
    "name_he": "כפר בן נון",
    "name_en": "Kefar Bin Nun",
    "lat": 31.861299,
    "lng": 34.947002,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kafar_bara",
    "name_he": "כפר ברא",
    "name_en": "Kafar Bara",
    "lat": 32.131132,
    "lng": 34.970643,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_daniyyel",
    "name_he": "כפר דניאל",
    "name_en": "Kefar Daniyyel",
    "lat": 31.933308,
    "lng": 34.932827,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_hanagid",
    "name_he": "כפר הנגיד",
    "name_en": "Kefar Hanagid",
    "lat": 31.88702,
    "lng": 34.749049,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_hess",
    "name_he": "כפר הס",
    "name_en": "Kefar Hess",
    "lat": 32.245521,
    "lng": 34.933595,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_haroe",
    "name_he": "כפר הרא\"ה",
    "name_en": "Kefar Haro'e",
    "lat": 32.390032,
    "lng": 34.911099,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_vitkin",
    "name_he": "כפר ויתקין",
    "name_en": "Kefar Vitkin",
    "lat": 32.380569,
    "lng": 34.87794,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_habad",
    "name_he": "כפר חב\"ד",
    "name_en": "Kefar Habad",
    "lat": 31.989476,
    "lng": 34.850233,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_hayyim",
    "name_he": "כפר חיים",
    "name_en": "Kefar Hayyim",
    "lat": 32.354142,
    "lng": 34.900289,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_truman",
    "name_he": "כפר טרומן",
    "name_en": "Kefar Truman",
    "lat": 31.980368,
    "lng": 34.923621,
    "region": "center",
    "type": "town"
  },
  {
    "id": "yedidya",
    "name_he": "כפר ידידיה",
    "name_en": "Yedidya",
    "lat": 32.345673,
    "lng": 34.898541,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_yona",
    "name_he": "כפר יונה",
    "name_en": "Kefar Yona",
    "lat": 32.316159,
    "lng": 34.931869,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_yabez",
    "name_he": "כפר יעבץ",
    "name_en": "Kefar Ya'bez",
    "lat": 32.274061,
    "lng": 34.96568,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_monash",
    "name_he": "כפר מונש",
    "name_en": "Kefar Monash",
    "lat": 32.347795,
    "lng": 34.916214,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_malal",
    "name_he": "כפר מל\"ל",
    "name_en": "Kefar Malal",
    "lat": 32.167482,
    "lng": 34.894344,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_mordekhay",
    "name_he": "כפר מרדכי",
    "name_en": "Kefar Mordekhay",
    "lat": 31.831503,
    "lng": 34.754308,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_netter",
    "name_he": "כפר נטר",
    "name_en": "Kefar Netter",
    "lat": 32.277882,
    "lng": 34.87517,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kfar_saba",
    "name_he": "כפר סבא",
    "name_en": "Kfar Saba",
    "lat": 32.1751,
    "lng": 34.9068,
    "region": "center",
    "type": "city"
  },
  {
    "id": "kefar_sirkin",
    "name_he": "כפר סירקין",
    "name_en": "Kefar Sirkin",
    "lat": 32.076524,
    "lng": 34.924326,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_avoda",
    "name_he": "כפר עבודה",
    "name_en": "Kefar Avoda",
    "lat": 32.257629,
    "lng": 34.941123,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kafar_qasem",
    "name_he": "כפר קאסם",
    "name_en": "Kafar Qasem",
    "lat": 32.117553,
    "lng": 34.967081,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_rut",
    "name_he": "כפר רות",
    "name_en": "Kefar Rut",
    "lat": 31.910109,
    "lng": 35.035579,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kefar_shemuel",
    "name_he": "כפר שמואל",
    "name_en": "Kefar Shemu'el",
    "lat": 31.888404,
    "lng": 34.933036,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kerem_beyavne",
    "name_he": "כרם ביבנה (ישיבה)",
    "name_en": "Kerem Beyavne",
    "lat": 31.819486,
    "lng": 34.721733,
    "region": "center",
    "type": "town",
    "aliases": [
      "כרם ביבנה"
    ]
  },
  {
    "id": "kerem_ben_shemen",
    "name_he": "כרם בן שמן",
    "name_en": "Kerem Ben Shemen",
    "lat": 31.958416,
    "lng": 34.933964,
    "region": "center",
    "type": "town"
  },
  {
    "id": "karme_yosef",
    "name_he": "כרמי יוסף",
    "name_en": "Karme Yosef",
    "lat": 31.847868,
    "lng": 34.920226,
    "region": "center",
    "type": "town"
  },
  {
    "id": "lod",
    "name_he": "לוד",
    "name_en": "Lod",
    "lat": 31.9514,
    "lng": 34.8882,
    "region": "center",
    "type": "city"
  },
  {
    "id": "lappid",
    "name_he": "לפיד",
    "name_en": "Lappid",
    "lat": 31.917371,
    "lng": 35.032387,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mevo_modiim",
    "name_he": "מבוא מודיעים",
    "name_en": "Mevo Modi'im",
    "lat": 31.933725,
    "lng": 34.987053,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mevoot_yam",
    "name_he": "מבואות ים",
    "name_en": "Mevo'ot Yam",
    "lat": 32.402816,
    "lng": 34.868583,
    "region": "center",
    "type": "town"
  },
  {
    "id": "magshimim",
    "name_he": "מגשימים",
    "name_en": "Magshimim",
    "lat": 32.046647,
    "lng": 34.898818,
    "region": "center",
    "type": "town"
  },
  {
    "id": "midreshet_ruppin",
    "name_he": "מדרשת רופין",
    "name_en": "Midreshet Ruppin",
    "lat": 32.341927,
    "lng": 34.912265,
    "region": "center",
    "type": "town",
    "aliases": [
      "המרכז האקדמי רופין"
    ]
  },
  {
    "id": "modiin",
    "name_he": "מודיעין-מכבים-רעות",
    "name_en": "Modi'in",
    "lat": 31.8969,
    "lng": 35.0104,
    "region": "center",
    "type": "city",
    "aliases": [
      "מודיעין"
    ]
  },
  {
    "id": "mazor",
    "name_he": "מזור",
    "name_en": "Mazor",
    "lat": 32.052714,
    "lng": 34.925807,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mazkeret_batya",
    "name_he": "מזכרת בתיה",
    "name_en": "Mazkeret Batya",
    "lat": 31.847052,
    "lng": 34.84303,
    "region": "center",
    "type": "town"
  },
  {
    "id": "meshar",
    "name_he": "מישר",
    "name_en": "Meshar",
    "lat": 31.818822,
    "lng": 34.753795,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mikhmoret",
    "name_he": "מכמורת",
    "name_en": "Mikhmoret",
    "lat": 32.405767,
    "lng": 34.872142,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mabarot",
    "name_he": "מעברות",
    "name_en": "Ma'barot",
    "lat": 32.363523,
    "lng": 34.90512,
    "region": "center",
    "type": "town"
  },
  {
    "id": "maas",
    "name_he": "מעש",
    "name_en": "Ma'as",
    "lat": 32.063697,
    "lng": 34.891365,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mazliah",
    "name_he": "מצליח",
    "name_en": "Mazliah",
    "lat": 31.904378,
    "lng": 34.874714,
    "region": "center",
    "type": "town"
  },
  {
    "id": "misgav_dov",
    "name_he": "משגב דב",
    "name_en": "Misgav Dov",
    "lat": 31.820063,
    "lng": 34.739599,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mishmar_ayyalon",
    "name_he": "משמר איילון",
    "name_en": "Mishmar Ayyalon",
    "lat": 31.871423,
    "lng": 34.945058,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mishmar_dawid",
    "name_he": "משמר דוד",
    "name_en": "Mishmar Dawid",
    "lat": 31.822285,
    "lng": 34.901267,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mishmar_hashiva",
    "name_he": "משמר השבעה",
    "name_en": "Mishmar Hashiv'a",
    "lat": 32.009751,
    "lng": 34.824323,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mishmar_hasharon",
    "name_he": "משמר השרון",
    "name_en": "Mishmar Hasharon",
    "lat": 32.356237,
    "lng": 34.904646,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mishmeret",
    "name_he": "משמרת",
    "name_en": "Mishmeret",
    "lat": 32.228351,
    "lng": 34.920413,
    "region": "center",
    "type": "town"
  },
  {
    "id": "mattan",
    "name_he": "מתן",
    "name_en": "Mattan",
    "lat": 32.157963,
    "lng": 34.975049,
    "region": "center",
    "type": "town"
  },
  {
    "id": "newe_yamin",
    "name_he": "נווה ימין",
    "name_en": "Newe Yamin",
    "lat": 32.171657,
    "lng": 34.939458,
    "region": "center",
    "type": "town"
  },
  {
    "id": "newe_yaraq",
    "name_he": "נווה ירק",
    "name_en": "Newe Yaraq",
    "lat": 32.132924,
    "lng": 34.924622,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nof_ayyalon",
    "name_he": "נוף איילון",
    "name_en": "Nof Ayyalon",
    "lat": 31.866069,
    "lng": 34.986503,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nofekh",
    "name_he": "נופך",
    "name_en": "Nofekh",
    "lat": 32.04369,
    "lng": 34.920369,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nordiyya",
    "name_he": "נורדיה",
    "name_en": "Nordiyya",
    "lat": 32.313965,
    "lng": 34.898168,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nehalim",
    "name_he": "נחלים",
    "name_en": "Nehalim",
    "lat": 32.058422,
    "lng": 34.913039,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nahshonim",
    "name_he": "נחשונים",
    "name_en": "Nahshonim",
    "lat": 32.061333,
    "lng": 34.948374,
    "region": "center",
    "type": "town"
  },
  {
    "id": "netaim",
    "name_he": "נטעים",
    "name_en": "Neta'im",
    "lat": 31.944746,
    "lng": 34.773991,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nizzane_oz",
    "name_he": "ניצני עוז",
    "name_en": "Nizzane Oz",
    "lat": 32.306476,
    "lng": 35.003524,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nir_eliyyahu",
    "name_he": "ניר אליהו",
    "name_en": "Nir Eliyyahu",
    "lat": 32.197029,
    "lng": 34.949369,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nir_gallim",
    "name_he": "ניר גלים",
    "name_en": "Nir Gallim",
    "lat": 31.825829,
    "lng": 34.684076,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nir_zevi",
    "name_he": "ניר צבי",
    "name_en": "Nir Zevi",
    "lat": 31.951016,
    "lng": 34.863616,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nirit",
    "name_he": "נירית",
    "name_en": "Nirit",
    "lat": 32.146431,
    "lng": 34.984976,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nes_ziona",
    "name_he": "נס ציונה",
    "name_en": "Nes Ziona",
    "lat": 31.9293,
    "lng": 34.7987,
    "region": "center",
    "type": "city"
  },
  {
    "id": "neurim",
    "name_he": "נעורים",
    "name_en": "Ne'urim",
    "lat": 32.372145,
    "lng": 34.861637,
    "region": "center",
    "type": "town"
  },
  {
    "id": "naan",
    "name_he": "נען",
    "name_en": "Na'an",
    "lat": 31.883235,
    "lng": 34.858218,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nezer_hazzani",
    "name_he": "נצר חזני",
    "name_en": "Nezer Hazzani",
    "lat": 31.821087,
    "lng": 34.862621,
    "region": "center",
    "type": "town"
  },
  {
    "id": "nezer_sereni",
    "name_he": "נצר סרני",
    "name_en": "Nezer Sereni",
    "lat": 31.923512,
    "lng": 34.824669,
    "region": "center",
    "type": "town"
  },
  {
    "id": "netanya",
    "name_he": "נתניה",
    "name_en": "Netanya",
    "lat": 32.3215,
    "lng": 34.8532,
    "region": "center",
    "type": "city"
  },
  {
    "id": "savyon",
    "name_he": "סביון",
    "name_en": "Savyon",
    "lat": 32.047246,
    "lng": 34.878195,
    "region": "center",
    "type": "town"
  },
  {
    "id": "sitriyya",
    "name_he": "סתריה",
    "name_en": "Sitriyya",
    "lat": 31.889666,
    "lng": 34.844715,
    "region": "center",
    "type": "town"
  },
  {
    "id": "adanim",
    "name_he": "עדנים",
    "name_en": "Adanim",
    "lat": 32.140129,
    "lng": 34.905246,
    "region": "center",
    "type": "town"
  },
  {
    "id": "olesh",
    "name_he": "עולש",
    "name_en": "Olesh",
    "lat": 32.332528,
    "lng": 34.984498,
    "region": "center",
    "type": "town"
  },
  {
    "id": "azarya",
    "name_he": "עזריה",
    "name_en": "Azarya",
    "lat": 31.888251,
    "lng": 34.903944,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ayanot",
    "name_he": "עיינות",
    "name_en": "Ayanot",
    "lat": 31.915397,
    "lng": 34.768086,
    "region": "center",
    "type": "town"
  },
  {
    "id": "en_hahoresh",
    "name_he": "עין החורש",
    "name_en": "En Hahoresh",
    "lat": 32.386139,
    "lng": 34.940035,
    "region": "center",
    "type": "town"
  },
  {
    "id": "en_wered",
    "name_he": "עין ורד",
    "name_en": "En Wered",
    "lat": 32.264715,
    "lng": 34.931823,
    "region": "center",
    "type": "town"
  },
  {
    "id": "en_sarid",
    "name_he": "עין שריד",
    "name_en": "En Sarid",
    "lat": 32.273757,
    "lng": 34.935621,
    "region": "center",
    "type": "town"
  },
  {
    "id": "enat",
    "name_he": "עינת",
    "name_en": "Enat",
    "lat": 32.082605,
    "lng": 34.938814,
    "region": "center",
    "type": "town"
  },
  {
    "id": "aseret",
    "name_he": "עשרת",
    "name_en": "Aseret",
    "lat": 31.824633,
    "lng": 34.74714,
    "region": "center",
    "type": "town"
  },
  {
    "id": "pedaya",
    "name_he": "פדיה",
    "name_en": "Pedaya",
    "lat": 31.855799,
    "lng": 34.878584,
    "region": "center",
    "type": "town"
  },
  {
    "id": "porat",
    "name_he": "פורת",
    "name_en": "Porat",
    "lat": 32.276298,
    "lng": 34.951834,
    "region": "center",
    "type": "town"
  },
  {
    "id": "palmahim",
    "name_he": "פלמחים",
    "name_en": "Palmahim",
    "lat": 31.934649,
    "lng": 34.710837,
    "region": "center",
    "type": "town"
  },
  {
    "id": "pardesiyya",
    "name_he": "פרדסיה",
    "name_en": "Pardesiyya",
    "lat": 32.306193,
    "lng": 34.909312,
    "region": "center",
    "type": "town"
  },
  {
    "id": "petah_tikva",
    "name_he": "פתח תקווה",
    "name_en": "Petah Tikva",
    "lat": 32.0868,
    "lng": 34.8868,
    "region": "center",
    "type": "city"
  },
  {
    "id": "petahya",
    "name_he": "פתחיה",
    "name_en": "Petahya",
    "lat": 31.867807,
    "lng": 34.886099,
    "region": "center",
    "type": "town"
  },
  {
    "id": "zofiyya",
    "name_he": "צופיה",
    "name_en": "Zofiyya",
    "lat": 31.856234,
    "lng": 34.738702,
    "region": "center",
    "type": "town",
    "aliases": [
      "מעון צופיה"
    ]
  },
  {
    "id": "zofit",
    "name_he": "צופית",
    "name_en": "Zofit",
    "lat": 32.191504,
    "lng": 34.922144,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shoshannat_haamaqim",
    "name_he": "צוקי ים",
    "name_en": "Shoshannat Haamaqim(",
    "lat": 32.360855,
    "lng": 34.858258,
    "region": "center",
    "type": "town"
  },
  {
    "id": "zur_yizhaq",
    "name_he": "צור יצחק",
    "name_en": "Zur Yizhaq",
    "lat": 32.240674,
    "lng": 34.997482,
    "region": "center",
    "type": "town"
  },
  {
    "id": "zur_moshe",
    "name_he": "צור משה",
    "name_en": "Zur Moshe",
    "lat": 32.298738,
    "lng": 34.913349,
    "region": "center",
    "type": "town"
  },
  {
    "id": "zur_natan",
    "name_he": "צור נתן",
    "name_en": "Zur Natan",
    "lat": 32.240791,
    "lng": 35.012687,
    "region": "center",
    "type": "town"
  },
  {
    "id": "zafriyya",
    "name_he": "צפריה",
    "name_en": "Zafriyya",
    "lat": 32.003205,
    "lng": 34.855902,
    "region": "center",
    "type": "town"
  },
  {
    "id": "qevuzat_yavne",
    "name_he": "קבוצת יבנה",
    "name_en": "Qevuzat Yavne",
    "lat": 31.815065,
    "lng": 34.720136,
    "region": "center",
    "type": "town"
  },
  {
    "id": "kadima_zoran",
    "name_he": "קדימה-צורן",
    "name_en": "Kadima-Zoran",
    "lat": 32.276,
    "lng": 34.92,
    "region": "center",
    "type": "local_council",
    "aliases": [
      "קדימה"
    ]
  },
  {
    "id": "qidron",
    "name_he": "קדרון",
    "name_en": "Qidron",
    "lat": 31.815438,
    "lng": 34.795995,
    "region": "center",
    "type": "town"
  },
  {
    "id": "qalansawe",
    "name_he": "קלנסווה",
    "name_en": "Qalansawe",
    "lat": 32.289216,
    "lng": 34.979421,
    "region": "center",
    "type": "town"
  },
  {
    "id": "qiryat_eqron",
    "name_he": "קרית עקרון",
    "name_en": "Qiryat Eqron",
    "lat": 31.86188,
    "lng": 34.821024,
    "region": "center",
    "type": "town"
  },
  {
    "id": "qiryat_shelomo",
    "name_he": "קרית שלמה",
    "name_en": "Qiryat Shelomo",
    "lat": 32.234447,
    "lng": 34.861821,
    "region": "center",
    "type": "town"
  },
  {
    "id": "rosh_haayin",
    "name_he": "ראש העין",
    "name_en": "Rosh HaAyin",
    "lat": 32.096,
    "lng": 34.9569,
    "region": "center",
    "type": "city"
  },
  {
    "id": "rishon_lezion",
    "name_he": "ראשון לציון",
    "name_en": "Rishon LeZion",
    "lat": 31.9642,
    "lng": 34.8047,
    "region": "center",
    "type": "city"
  },
  {
    "id": "rehovot",
    "name_he": "רחובות",
    "name_en": "Rehovot",
    "lat": 31.8928,
    "lng": 34.8113,
    "region": "center",
    "type": "city"
  },
  {
    "id": "rinnatya",
    "name_he": "רינתיה",
    "name_en": "Rinnatya",
    "lat": 32.044351,
    "lng": 34.928079,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ramot_hashavim",
    "name_he": "רמות השבים",
    "name_en": "Ramot Hashavim",
    "lat": 32.166004,
    "lng": 34.883555,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ramot_meir",
    "name_he": "רמות מאיר",
    "name_en": "Ramot Me'ir",
    "lat": 31.874055,
    "lng": 34.855256,
    "region": "center",
    "type": "town"
  },
  {
    "id": "ramla",
    "name_he": "רמלה",
    "name_en": "Ramla",
    "lat": 31.9284,
    "lng": 34.8626,
    "region": "center",
    "type": "city"
  },
  {
    "id": "ramat_hakovesh",
    "name_he": "רמת הכובש",
    "name_en": "Ramat Hakovesh",
    "lat": 32.217676,
    "lng": 34.93793,
    "region": "center",
    "type": "town"
  },
  {
    "id": "raanana",
    "name_he": "רעננה",
    "name_en": "Ra'anana",
    "lat": 32.184,
    "lng": 34.871,
    "region": "center",
    "type": "city"
  },
  {
    "id": "rishpon",
    "name_he": "רשפון",
    "name_en": "Rishpon",
    "lat": 32.199902,
    "lng": 34.824176,
    "region": "center",
    "type": "town"
  },
  {
    "id": "sede_warburg",
    "name_he": "שדה ורבורג",
    "name_en": "Sede Warburg",
    "lat": 32.209194,
    "lng": 34.897404,
    "region": "center",
    "type": "town"
  },
  {
    "id": "sede_hemed",
    "name_he": "שדי חמד",
    "name_en": "Sede Hemed",
    "lat": 32.160327,
    "lng": 34.944483,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shedema",
    "name_he": "שדמה",
    "name_en": "Shedema",
    "lat": 31.833555,
    "lng": 34.741596,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shoham",
    "name_he": "שוהם",
    "name_en": "Shoham",
    "lat": 31.9979,
    "lng": 34.9468,
    "region": "center",
    "type": "local_council",
    "aliases": [
      "שהם"
    ]
  },
  {
    "id": "shoshannat_haamaqim_224",
    "name_he": "שושנת העמקים",
    "name_en": "Shoshannat Haamaqim",
    "lat": 32.354128,
    "lng": 34.857083,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shilat",
    "name_he": "שילת",
    "name_en": "Shilat",
    "lat": 31.918123,
    "lng": 35.019372,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shaalvim",
    "name_he": "שעלבים",
    "name_en": "Sha'alvim",
    "lat": 31.870964,
    "lng": 34.983116,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shaar_efrayim",
    "name_he": "שער אפרים",
    "name_en": "Sha'ar Efrayim",
    "lat": 32.289098,
    "lng": 34.997354,
    "region": "center",
    "type": "town"
  },
  {
    "id": "shefayim",
    "name_he": "שפיים",
    "name_en": "Shefayim",
    "lat": 32.219786,
    "lng": 34.827341,
    "region": "center",
    "type": "town"
  },
  {
    "id": "tel_yizhaq",
    "name_he": "תל יצחק",
    "name_en": "Tel Yizhaq",
    "lat": 32.252426,
    "lng": 34.871791,
    "region": "center",
    "type": "town"
  },
  {
    "id": "tel_mond",
    "name_he": "תל מונד",
    "name_en": "Tel Mond",
    "lat": 32.252984,
    "lng": 34.918167,
    "region": "center",
    "type": "town"
  },
  {
    "id": "tenuvot",
    "name_he": "תנובות",
    "name_en": "Tenuvot",
    "lat": 32.306979,
    "lng": 34.962962,
    "region": "center",
    "type": "town"
  }
];
