import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "ibtin",
    "name_he": "אבטין",
    "name_en": "Ibtin",
    "lat": 32.762108,
    "lng": 35.112605,
    "region": "haifa",
    "type": "town",
    "aliases": [
      "איבטין"
    ]
  },
  {
    "id": "aviel",
    "name_he": "אביאל",
    "name_en": "Avi'el",
    "lat": 32.531501,
    "lng": 34.993251,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "umm_al_fahm",
    "name_he": "אום אל-פחם",
    "name_en": "Umm Al-Fahm",
    "lat": 32.521074,
    "lng": 35.148649,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "umm_al_qutuf",
    "name_he": "אום אל-קוטוף",
    "name_en": "Umm Al-Qutuf",
    "lat": 32.467807,
    "lng": 35.059197,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "or_akiva",
    "name_he": "אור עקיבא",
    "name_en": "Or Akiva",
    "lat": 32.5074,
    "lng": 34.9187,
    "region": "haifa",
    "type": "city"
  },
  {
    "id": "oranim",
    "name_he": "אורנים",
    "name_en": "Oranim",
    "lat": 32.71247,
    "lng": 35.108867,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "usha",
    "name_he": "אושה",
    "name_en": "Usha",
    "lat": 32.795849,
    "lng": 35.114104,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "al_aryan",
    "name_he": "אל-עריאן",
    "name_en": "Al-Aryan",
    "lat": 32.498122,
    "lng": 35.125209,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "allone_yizhaq",
    "name_he": "אלוני יצחק",
    "name_en": "Allone Yizhaq",
    "lat": 32.51039,
    "lng": 35.004125,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "baqa_al_gharbiyye",
    "name_he": "באקה אל-גרביה",
    "name_en": "Baqa Al-Gharbiyye",
    "lat": 32.420081,
    "lng": 35.04121,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "bet_oren",
    "name_he": "בית אורן",
    "name_en": "Bet Oren",
    "lat": 32.7316,
    "lng": 35.004568,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "bet_hananya",
    "name_he": "בית חנניה",
    "name_en": "Bet Hananya",
    "lat": 32.528876,
    "lng": 34.925866,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "bet_zevi",
    "name_he": "בית צבי",
    "name_en": "Bet Zevi",
    "lat": 32.719278,
    "lng": 34.9697,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "binyamina",
    "name_he": "בנימינה-גבעת עדה",
    "name_en": "Binyamina",
    "lat": 32.5208,
    "lng": 34.9465,
    "region": "haifa",
    "type": "local_council",
    "aliases": [
      "בנימינה"
    ]
  },
  {
    "id": "basma",
    "name_he": "בסמ\"ה",
    "name_en": "Basma",
    "lat": 32.545359,
    "lng": 35.152205,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "barqay",
    "name_he": "ברקאי",
    "name_en": "Barqay",
    "lat": 32.475258,
    "lng": 35.02933,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "bat_shelomo",
    "name_he": "בת שלמה",
    "name_en": "Bat Shelomo",
    "lat": 32.600428,
    "lng": 35.003378,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "jisr_az_zarqa",
    "name_he": "ג'סר א-זרקא",
    "name_en": "Jisr Az-Zarqa",
    "lat": 32.536792,
    "lng": 34.911435,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "jaat",
    "name_he": "ג'ת",
    "name_en": "Jaat",
    "lat": 32.399293,
    "lng": 35.035489,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "geva_karmel",
    "name_he": "גבע כרמל",
    "name_en": "Geva Karmel",
    "lat": 32.662739,
    "lng": 34.955235,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "givat_nili",
    "name_he": "גבעת ניל\"י",
    "name_en": "Giv'at Nili",
    "lat": 32.547805,
    "lng": 35.041623,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "gan_hashomeron",
    "name_he": "גן השומרון",
    "name_en": "Gan Hashomeron",
    "lat": 32.463061,
    "lng": 35.001329,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "gan_shemuel",
    "name_he": "גן שמואל",
    "name_en": "Gan Shemu'el",
    "lat": 32.451499,
    "lng": 34.950945,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "daliyat_al_karmel",
    "name_he": "דאלית אל-כרמל",
    "name_en": "Daliyat Al-Karmel",
    "lat": 32.693415,
    "lng": 35.0515,
    "region": "haifa",
    "type": "town",
    "aliases": [
      "דלית אל כרמל"
    ]
  },
  {
    "id": "dor",
    "name_he": "דור",
    "name_en": "Dor",
    "lat": 32.607186,
    "lng": 34.923345,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "habonim",
    "name_he": "הבונים",
    "name_en": "Habonim",
    "lat": 32.636017,
    "lng": 34.932514,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "hahoterim",
    "name_he": "החותרים",
    "name_en": "Hahoterim",
    "lat": 32.751799,
    "lng": 34.956827,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "zichron_yaakov",
    "name_he": "זכרון יעקב",
    "name_en": "Zikhron Ya'akov",
    "lat": 32.5713,
    "lng": 34.9515,
    "region": "haifa",
    "type": "local_council"
  },
  {
    "id": "khawaled",
    "name_he": "ח'ואלד",
    "name_en": "Khawaled",
    "lat": 32.788381,
    "lng": 35.435457,
    "region": "haifa",
    "type": "town",
    "aliases": [
      "כפר ח'וואלד"
    ]
  },
  {
    "id": "hadera",
    "name_he": "חדרה",
    "name_en": "Hadera",
    "lat": 32.434,
    "lng": 34.9196,
    "region": "haifa",
    "type": "city"
  },
  {
    "id": "haifa",
    "name_he": "חיפה",
    "name_en": "Haifa",
    "lat": 32.794,
    "lng": 34.9896,
    "region": "haifa",
    "type": "city"
  },
  {
    "id": "harish",
    "name_he": "חריש",
    "name_en": "Harish",
    "lat": 32.460918,
    "lng": 35.046576,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "tirat_carmel",
    "name_he": "טירת כרמל",
    "name_en": "Tirat Carmel",
    "lat": 32.76,
    "lng": 34.971,
    "region": "haifa",
    "type": "city"
  },
  {
    "id": "yagur",
    "name_he": "יגור",
    "name_en": "Yagur",
    "lat": 32.743658,
    "lng": 35.075476,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_bialik",
    "name_he": "כפר ביאליק",
    "name_en": "Kefar Bialik",
    "lat": 32.820585,
    "lng": 35.086547,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_gallim",
    "name_he": "כפר גלים",
    "name_en": "Kefar Gallim",
    "lat": 32.766635,
    "lng": 34.958621,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_glikson",
    "name_he": "כפר גליקסון",
    "name_en": "Kefar Glikson",
    "lat": 32.50595,
    "lng": 35.005027,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_hamakkabi",
    "name_he": "כפר המכבי",
    "name_en": "Kefar Hamakkabi",
    "lat": 32.790601,
    "lng": 35.115426,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_hanoar_hadati",
    "name_he": "כפר הנוער הדתי",
    "name_en": "Kefar Hano'ar Hadati",
    "lat": 32.742239,
    "lng": 35.099131,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_hasidim_alef",
    "name_he": "כפר חסידים א'",
    "name_en": "Kefar Hasidim Alef",
    "lat": 32.75024,
    "lng": 35.093014,
    "region": "haifa",
    "type": "town",
    "aliases": [
      "כפר חסידים"
    ]
  },
  {
    "id": "kefar_hasidim_bet",
    "name_he": "כפר חסידים ב'",
    "name_en": "Kefar Hasidim Bet",
    "lat": 32.749818,
    "lng": 35.087077,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kefar_pines",
    "name_he": "כפר פינס",
    "name_en": "Kefar Pines",
    "lat": 32.484262,
    "lng": 35.00256,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kafar_qara",
    "name_he": "כפר קרע",
    "name_en": "Kafar Qara",
    "lat": 32.504859,
    "lng": 35.049836,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "kerem_maharal",
    "name_he": "כרם מהר\"ל",
    "name_en": "Kerem Maharal",
    "lat": 32.645903,
    "lng": 34.990644,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "lahavot_haviva",
    "name_he": "להבות חביבה",
    "name_en": "Lahavot Haviva",
    "lat": 32.395017,
    "lng": 35.009714,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "maor",
    "name_he": "מאור",
    "name_en": "Ma'or",
    "lat": 32.424236,
    "lng": 35.005548,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "meir_shefeya",
    "name_he": "מאיר שפיה",
    "name_en": "Me'ir Shefeya",
    "lat": 32.591222,
    "lng": 34.970786,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "megadim",
    "name_he": "מגדים",
    "name_en": "Megadim",
    "lat": 32.725936,
    "lng": 34.961471,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "maggal",
    "name_he": "מגל",
    "name_en": "Maggal",
    "lat": 32.385645,
    "lng": 35.034712,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "me_ammi",
    "name_he": "מי עמי",
    "name_en": "Me Ammi",
    "lat": 32.503407,
    "lng": 35.148319,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "meiser",
    "name_he": "מייסר",
    "name_en": "Meiser",
    "lat": 32.44516,
    "lng": 35.041799,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "maagan_mikhael",
    "name_he": "מעגן מיכאל",
    "name_en": "Ma'agan Mikha'el",
    "lat": 32.556379,
    "lng": 34.915646,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "mayan_zevi",
    "name_he": "מעין צבי",
    "name_en": "Ma'yan Zevi",
    "lat": 32.567862,
    "lng": 34.940368,
    "region": "haifa",
    "type": "town",
    "aliases": [
      "מעיין צבי"
    ]
  },
  {
    "id": "maale_iron",
    "name_he": "מעלה עירון",
    "name_en": "Ma'ale Iron",
    "lat": 31.347159,
    "lng": 35.06016,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "maanit",
    "name_he": "מענית",
    "name_en": "Ma'anit",
    "lat": 32.45695,
    "lng": 35.028738,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "mitspe_ilan",
    "name_he": "מצפה אילן",
    "name_en": "Mitspe Ilan",
    "lat": 32.461297,
    "lng": 35.068916,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "mezer",
    "name_he": "מצר",
    "name_en": "Mezer",
    "lat": 32.440445,
    "lng": 35.048002,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "mishmarot",
    "name_he": "משמרות",
    "name_en": "Mishmarot",
    "lat": 32.487624,
    "lng": 34.984209,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "newe_avot",
    "name_he": "נווה אבות",
    "name_en": "Newe Avot",
    "lat": 32.485706,
    "lng": 34.967158,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "newe_yam",
    "name_he": "נווה ים",
    "name_en": "Newe Yam",
    "lat": 32.678729,
    "lng": 34.931684,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "nofit",
    "name_he": "נופית",
    "name_en": "Nofit",
    "lat": 32.759127,
    "lng": 35.146172,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "nahsholim",
    "name_he": "נחשולים",
    "name_en": "Nahsholim",
    "lat": 32.613583,
    "lng": 34.921263,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "nir_ezyon",
    "name_he": "ניר עציון",
    "name_en": "Nir Ezyon",
    "lat": 32.699373,
    "lng": 34.991651,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "nesher",
    "name_he": "נשר",
    "name_en": "Nesher",
    "lat": 32.7716,
    "lng": 35.042,
    "region": "haifa",
    "type": "city"
  },
  {
    "id": "ofer",
    "name_he": "עופר",
    "name_en": "Ofer",
    "lat": 32.622356,
    "lng": 34.981784,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "en_ayyala",
    "name_he": "עין איילה",
    "name_en": "En Ayyala",
    "lat": 32.630337,
    "lng": 34.948835,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "en_hod",
    "name_he": "עין הוד",
    "name_en": "En Hod",
    "lat": 32.699698,
    "lng": 34.982661,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "ein_hod",
    "name_he": "עין חוד",
    "name_en": "Ein Hod",
    "lat": 32.691547,
    "lng": 34.99986,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "en_karmel",
    "name_he": "עין כרמל",
    "name_en": "En Karmel",
    "lat": 32.676951,
    "lng": 34.953137,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "en_iron",
    "name_he": "עין עירון",
    "name_en": "En Iron",
    "lat": 32.483694,
    "lng": 35.009648,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "en_shemer",
    "name_he": "עין שמר",
    "name_en": "En Shemer",
    "lat": 32.463162,
    "lng": 35.007735,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "ammiqam",
    "name_he": "עמיקם",
    "name_en": "Ammiqam",
    "lat": 32.563421,
    "lng": 35.020763,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "isifya",
    "name_he": "עספיא",
    "name_en": "Isifya",
    "lat": 32.71153,
    "lng": 35.074719,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "arara",
    "name_he": "ערערה",
    "name_en": "Ar'ara",
    "lat": 32.498731,
    "lng": 35.0957,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "atlit",
    "name_he": "עתלית",
    "name_en": "Atlit",
    "lat": 32.693028,
    "lng": 34.943276,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "fureidis",
    "name_he": "פוריידיס",
    "name_en": "Fureidis",
    "lat": 32.5979,
    "lng": 34.953933,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "pardes_hanna_karkur",
    "name_he": "פרדס חנה-כרכור",
    "name_en": "Pardes Hanna-Karkur",
    "lat": 32.4726,
    "lng": 34.9671,
    "region": "haifa",
    "type": "local_council",
    "aliases": [
      "פרדס חנה"
    ]
  },
  {
    "id": "zerufa",
    "name_he": "צרופה",
    "name_en": "Zerufa",
    "lat": 32.648573,
    "lng": 34.94764,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "caesarea",
    "name_he": "קיסריה",
    "name_en": "Caesarea",
    "lat": 32.5013,
    "lng": 34.8878,
    "region": "haifa",
    "type": "local_council"
  },
  {
    "id": "qazir",
    "name_he": "קציר",
    "name_en": "Qazir",
    "lat": 32.488191,
    "lng": 35.10334,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "qiryat_atta",
    "name_he": "קרית אתא",
    "name_en": "Qiryat Atta",
    "lat": 32.805807,
    "lng": 35.105009,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "qiryat_bialik",
    "name_he": "קרית ביאליק",
    "name_en": "Qiryat Bialik",
    "lat": 32.836384,
    "lng": 35.097105,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "qiryat_tivon",
    "name_he": "קרית טבעון",
    "name_en": "Qiryat Tiv'on",
    "lat": 32.711502,
    "lng": 35.126289,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "qiryat_yam",
    "name_he": "קרית ים",
    "name_en": "Qiryat Yam",
    "lat": 32.848699,
    "lng": 35.071854,
    "region": "haifa",
    "type": "town",
    "aliases": [
      "קריית ים"
    ]
  },
  {
    "id": "qiryat_motzkin",
    "name_he": "קרית מוצקין",
    "name_en": "Qiryat Motzkin",
    "lat": 32.841845,
    "lng": 35.082688,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "ras_ali",
    "name_he": "ראס עלי",
    "name_en": "Ras Ali",
    "lat": 32.77185,
    "lng": 35.154352,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "regavim",
    "name_he": "רגבים",
    "name_en": "Regavim",
    "lat": 32.524445,
    "lng": 35.034299,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "rekhasim",
    "name_he": "רכסים",
    "name_en": "Rekhasim",
    "lat": 32.751472,
    "lng": 35.102085,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "ramat_yohanan",
    "name_he": "רמת יוחנן",
    "name_en": "Ramat Yohanan",
    "lat": 32.79275,
    "lng": 35.122308,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "sede_yizhaq",
    "name_he": "שדה יצחק",
    "name_en": "Sede Yizhaq",
    "lat": 32.40481,
    "lng": 34.994817,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "sedot_yam",
    "name_he": "שדות ים",
    "name_en": "Sedot Yam",
    "lat": 32.493087,
    "lng": 34.893731,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "shaar_haamaqim",
    "name_he": "שער העמקים",
    "name_en": "Sha'ar Haamaqim",
    "lat": 32.72375,
    "lng": 35.112386,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "shaar_menashe",
    "name_he": "שער מנשה",
    "name_en": "Sha'ar Menashe",
    "lat": 32.449843,
    "lng": 35.016119,
    "region": "haifa",
    "type": "town"
  },
  {
    "id": "talme_elazar",
    "name_he": "תלמי אלעזר",
    "name_en": "Talme El'azar",
    "lat": 32.446828,
    "lng": 34.978492,
    "region": "haifa",
    "type": "town"
  }
];
