import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "abu_ghosh",
    "name_he": "אבו גוש",
    "name_en": "Abu Ghosh",
    "lat": 31.8072,
    "lng": 35.1082,
    "region": "jerusalem",
    "type": "local_council"
  },
  {
    "id": "aviezer",
    "name_he": "אביעזר",
    "name_en": "Avi'ezer",
    "lat": 31.681665,
    "lng": 35.01611,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "even_sappir",
    "name_he": "אבן ספיר",
    "name_en": "Even Sappir",
    "lat": 31.763291,
    "lng": 35.134132,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "adderet",
    "name_he": "אדרת",
    "name_en": "Adderet",
    "lat": 31.660092,
    "lng": 34.994499,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "ora",
    "name_he": "אורה",
    "name_en": "Ora",
    "lat": 31.756425,
    "lng": 35.156728,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "etanim",
    "name_he": "איתנים",
    "name_en": "Etanim",
    "lat": 31.778324,
    "lng": 35.095683,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "eshtaol",
    "name_he": "אשתאול",
    "name_en": "Eshta'ol",
    "lat": 31.781469,
    "lng": 35.008695,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "bet_zayit",
    "name_he": "בית זית",
    "name_en": "Bet Zayit",
    "lat": 31.782378,
    "lng": 35.161863,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "bet_meir",
    "name_he": "בית מאיר",
    "name_en": "Bet Me'ir",
    "lat": 31.794183,
    "lng": 35.036807,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "bet_neqofa",
    "name_he": "בית נקופה",
    "name_en": "Bet Neqofa",
    "lat": 31.804251,
    "lng": 35.126275,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "beit_shemesh",
    "name_he": "בית שמש",
    "name_en": "Beit Shemesh",
    "lat": 31.7465,
    "lng": 34.9868,
    "region": "jerusalem",
    "type": "city"
  },
  {
    "id": "beitar_illit",
    "name_he": "ביתר עילית",
    "name_en": "Beitar Illit",
    "lat": 31.6963,
    "lng": 35.1247,
    "region": "jerusalem",
    "type": "city"
  },
  {
    "id": "beqoa",
    "name_he": "בקוע",
    "name_en": "Beqoa",
    "lat": 31.829299,
    "lng": 34.924658,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "bar_giyyora",
    "name_he": "בר גיורא",
    "name_en": "Bar Giyyora",
    "lat": 31.729042,
    "lng": 35.073092,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "givat_yearim",
    "name_he": "גבעת יערים",
    "name_en": "Giv'at Ye'arim",
    "lat": 31.786647,
    "lng": 35.091911,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "givat_yeshayahu",
    "name_he": "גבעת ישעיהו",
    "name_en": "Giv'at Yesha'yahu",
    "lat": 31.670361,
    "lng": 34.947779,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "givat_shemesh",
    "name_he": "גבעת שמש",
    "name_en": "Giv'at Shemesh",
    "lat": 31.775171,
    "lng": 34.951486,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "gizo",
    "name_he": "גיזו",
    "name_en": "Gizo",
    "lat": 31.804999,
    "lng": 34.938605,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "gefen",
    "name_he": "גפן",
    "name_en": "Gefen",
    "lat": 31.740857,
    "lng": 34.878454,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "harel",
    "name_he": "הראל",
    "name_en": "Har'el",
    "lat": 31.809723,
    "lng": 34.951742,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zekharya",
    "name_he": "זכריה",
    "name_en": "Zekharya",
    "lat": 31.70977,
    "lng": 34.944794,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zanoah",
    "name_he": "זנוח",
    "name_en": "Zanoah",
    "lat": 31.732314,
    "lng": 34.999605,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "tal_shahar",
    "name_he": "טל שחר",
    "name_en": "Tal Shahar",
    "lat": 31.805712,
    "lng": 34.903599,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "yad_hashemona",
    "name_he": "יד השמונה",
    "name_en": "Yad Hashemona",
    "lat": 31.80889,
    "lng": 35.090052,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "yedida",
    "name_he": "ידידה",
    "name_en": "Yedida",
    "lat": 31.812947,
    "lng": 35.105511,
    "region": "jerusalem",
    "type": "town",
    "aliases": [
      "כפר הנוער קריית יערים"
    ]
  },
  {
    "id": "jerusalem",
    "name_he": "ירושלים",
    "name_en": "Jerusalem",
    "lat": 31.7683,
    "lng": 35.2137,
    "region": "jerusalem",
    "type": "city"
  },
  {
    "id": "yishi",
    "name_he": "ישעי",
    "name_en": "Yish'i",
    "lat": 31.751388,
    "lng": 34.965681,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "kesalon",
    "name_he": "כסלון",
    "name_en": "Kesalon",
    "lat": 31.773777,
    "lng": 35.049562,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "kefar_uriyya",
    "name_he": "כפר אוריה",
    "name_en": "Kefar Uriyya",
    "lat": 31.793314,
    "lng": 34.946942,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "kefar_zoharim",
    "name_he": "כפר זוהרים",
    "name_en": "Kefar Zoharim",
    "lat": 32.472673,
    "lng": 35.093227,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "luzit",
    "name_he": "לוזית",
    "name_en": "Luzit",
    "lat": 31.687259,
    "lng": 34.886404,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "mevo_betar",
    "name_he": "מבוא ביתר",
    "name_en": "Mevo Betar",
    "lat": 31.722803,
    "lng": 35.105477,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "mevaseret_zion",
    "name_he": "מבשרת ציון",
    "name_en": "Mevaseret Zion",
    "lat": 31.8003,
    "lng": 35.1504,
    "region": "jerusalem",
    "type": "local_council"
  },
  {
    "id": "modiin_illit",
    "name_he": "מודיעין עילית",
    "name_en": "Modi'in Illit",
    "lat": 31.9333,
    "lng": 35.0447,
    "region": "jerusalem",
    "type": "city"
  },
  {
    "id": "moza_illit",
    "name_he": "מוצא עילית",
    "name_en": "Moza Illit",
    "lat": 31.7939,
    "lng": 35.157294,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "mahseya",
    "name_he": "מחסיה",
    "name_en": "Mahseya",
    "lat": 31.748084,
    "lng": 35.007239,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "matta",
    "name_he": "מטע",
    "name_en": "Matta",
    "lat": 31.717707,
    "lng": 35.061349,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "mesillat_ziyyon",
    "name_he": "מסילת ציון",
    "name_en": "Mesillat Ziyyon",
    "lat": 31.802156,
    "lng": 35.011083,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "maaleh_adumim",
    "name_he": "מעלה אדומים",
    "name_en": "Ma'ale Adumim",
    "lat": 31.7773,
    "lng": 35.2985,
    "region": "jerusalem",
    "type": "city"
  },
  {
    "id": "maale_hahamisha",
    "name_he": "מעלה החמישה",
    "name_en": "Ma'ale Hahamisha",
    "lat": 31.817654,
    "lng": 35.11132,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "newe_ilan",
    "name_he": "נווה אילן",
    "name_en": "Newe Ilan",
    "lat": 31.80819,
    "lng": 35.080936,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "newe_mikhael",
    "name_he": "נווה מיכאל",
    "name_en": "Newe Mikha'el",
    "lat": 31.672988,
    "lng": 35.006358,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "newe_shalom",
    "name_he": "נווה שלום",
    "name_en": "Newe Shalom",
    "lat": 31.818017,
    "lng": 34.978299,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "nehusha",
    "name_he": "נחושה",
    "name_en": "Nehusha",
    "lat": 31.626369,
    "lng": 34.951473,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "naham",
    "name_he": "נחם",
    "name_en": "Naham",
    "lat": 31.76664,
    "lng": 35.003128,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "nahshon",
    "name_he": "נחשון",
    "name_en": "Nahshon",
    "lat": 31.830734,
    "lng": 34.954728,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "nataf",
    "name_he": "נטף",
    "name_en": "Nataf",
    "lat": 31.832086,
    "lng": 35.067745,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "nes_harim",
    "name_he": "נס הרים",
    "name_en": "Nes Harim",
    "lat": 31.745557,
    "lng": 35.055307,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "netiv_halamed_he",
    "name_he": "נתיב הל\"ה",
    "name_en": "Netiv Halamed-He",
    "lat": 31.688399,
    "lng": 34.982399,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "agur",
    "name_he": "עגור",
    "name_en": "Agur",
    "lat": 31.69723,
    "lng": 34.912343,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "en_karem_b_s_haqlai",
    "name_he": "עין כרם-בי\"ס חקלאי",
    "name_en": "En Karem-B.s.haqla'i",
    "lat": 31.777887,
    "lng": 35.152426,
    "region": "jerusalem",
    "type": "town",
    "aliases": [
      "פנימיית עין כרם"
    ]
  },
  {
    "id": "ein_naqquba",
    "name_he": "עין נקובא",
    "name_en": "Ein Naqquba",
    "lat": 31.794426,
    "lng": 35.121583,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "ein_rafa",
    "name_he": "עין ראפה",
    "name_en": "Ein Rafa",
    "lat": 31.789603,
    "lng": 35.113257,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "amminadav",
    "name_he": "עמינדב",
    "name_en": "Amminadav",
    "lat": 31.750863,
    "lng": 35.141377,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zova",
    "name_he": "צובה",
    "name_en": "Zova",
    "lat": 31.783861,
    "lng": 35.119138,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zur_hadassa",
    "name_he": "צור הדסה",
    "name_en": "Zur Hadassa",
    "lat": 31.71569,
    "lng": 35.095837,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zelafon",
    "name_he": "צלפון",
    "name_en": "Zelafon",
    "lat": 31.805769,
    "lng": 34.927228,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zafririm",
    "name_he": "צפרירים",
    "name_en": "Zafririm",
    "lat": 31.660377,
    "lng": 34.943195,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "zora",
    "name_he": "צרעה",
    "name_en": "Zor'a",
    "lat": 31.76219,
    "lng": 34.969236,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "qiryat_yearim",
    "name_he": "קרית יערים",
    "name_en": "Qiryat Ye'arim",
    "lat": 31.802552,
    "lng": 35.099007,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "qiryat_anavim",
    "name_he": "קרית ענבים",
    "name_en": "Qiryat Anavim",
    "lat": 31.810182,
    "lng": 35.118912,
    "region": "jerusalem",
    "type": "town",
    "aliases": [
      "קריית ענבים"
    ]
  },
  {
    "id": "ramat_raziel",
    "name_he": "רמת רזיאל",
    "name_en": "Ramat Razi'el",
    "lat": 31.773956,
    "lng": 35.072944,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "ramat_rahel",
    "name_he": "רמת רחל",
    "name_en": "Ramat Rahel",
    "lat": 31.739163,
    "lng": 35.21843,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "sedot_mikha",
    "name_he": "שדות מיכה",
    "name_en": "Sedot Mikha",
    "lat": 31.721028,
    "lng": 34.920709,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "shoeva",
    "name_he": "שואבה",
    "name_en": "Sho'eva",
    "lat": 31.798837,
    "lng": 35.078525,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "shoresh",
    "name_he": "שורש",
    "name_en": "Shoresh",
    "lat": 31.796962,
    "lng": 35.06546,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "li_on",
    "name_he": "שריגים (לי-און)",
    "name_en": "Li-On",
    "lat": 31.677025,
    "lng": 34.93461,
    "region": "jerusalem",
    "type": "town",
    "aliases": [
      "שריגים - ליאון"
    ]
  },
  {
    "id": "tirosh",
    "name_he": "תירוש",
    "name_en": "Tirosh",
    "lat": 31.748643,
    "lng": 34.888695,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "taoz",
    "name_he": "תעוז",
    "name_en": "Ta'oz",
    "lat": 31.801887,
    "lng": 34.973635,
    "region": "jerusalem",
    "type": "town"
  },
  {
    "id": "tarum",
    "name_he": "תרום",
    "name_en": "Tarum",
    "lat": 31.783268,
    "lng": 34.982314,
    "region": "jerusalem",
    "type": "town"
  }
];
