import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "avne_hefez",
    "name_he": "אבני חפץ",
    "name_en": "Avne Hefez",
    "lat": 32.286158,
    "lng": 35.072117,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "ovnat",
    "name_he": "אבנת",
    "name_en": "Ovnat",
    "lat": 31.67902,
    "lng": 35.437279,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "adora",
    "name_he": "אדורה",
    "name_en": "Adora",
    "lat": 31.552513,
    "lng": 35.017851,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "oranit",
    "name_he": "אורנית",
    "name_en": "Oranit",
    "lat": 32.130455,
    "lng": 34.990292,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "itamar",
    "name_he": "איתמר",
    "name_en": "Itamar",
    "lat": 32.1742,
    "lng": 35.307585,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "elon_more",
    "name_he": "אלון מורה",
    "name_en": "Elon More",
    "lat": 32.232632,
    "lng": 35.33302,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "allon_shevut",
    "name_he": "אלון שבות",
    "name_en": "Allon Shevut",
    "lat": 31.657062,
    "lng": 35.12393,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "almog",
    "name_he": "אלמוג",
    "name_en": "Almog",
    "lat": 31.785706,
    "lng": 35.461403,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "elazar",
    "name_he": "אלעזר",
    "name_en": "El'azar",
    "lat": 31.659515,
    "lng": 35.143354,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "alfei_menashe",
    "name_he": "אלפי מנשה",
    "name_en": "Alfei Menashe",
    "lat": 32.1728,
    "lng": 35.0242,
    "region": "judea_samaria",
    "type": "local_council"
  },
  {
    "id": "elqana",
    "name_he": "אלקנה",
    "name_en": "Elqana",
    "lat": 32.10972,
    "lng": 35.036708,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "asefar",
    "name_he": "אספר",
    "name_en": "Asefar",
    "lat": 31.585579,
    "lng": 35.187513,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "מיצד"
    ]
  },
  {
    "id": "efrat",
    "name_he": "אפרת",
    "name_en": "Efrat",
    "lat": 31.654,
    "lng": 35.1578,
    "region": "judea_samaria",
    "type": "local_council"
  },
  {
    "id": "argaman",
    "name_he": "ארגמן",
    "name_en": "Argaman",
    "lat": 32.1726,
    "lng": 35.521885,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "ariel",
    "name_he": "אריאל",
    "name_en": "Ariel",
    "lat": 32.1043,
    "lng": 35.1723,
    "region": "judea_samaria",
    "type": "city"
  },
  {
    "id": "eshkolot",
    "name_he": "אשכולות",
    "name_en": "Eshkolot",
    "lat": 31.391044,
    "lng": 34.904964,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "beit_el",
    "name_he": "בית אל",
    "name_en": "Beit El",
    "lat": 31.9412,
    "lng": 35.2326,
    "region": "judea_samaria",
    "type": "local_council"
  },
  {
    "id": "bet_arye",
    "name_he": "בית אריה",
    "name_en": "Bet Arye",
    "lat": 32.039087,
    "lng": 35.04821,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "bet_haarava",
    "name_he": "בית הערבה",
    "name_en": "Bet Haarava",
    "lat": 31.808305,
    "lng": 35.477788,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "bet_horon",
    "name_he": "בית חורון",
    "name_en": "Bet Horon",
    "lat": 31.879787,
    "lng": 35.123483,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "beqaot",
    "name_he": "בקעות",
    "name_en": "Beqa'ot",
    "lat": 32.243656,
    "lng": 35.452562,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "brukhin",
    "name_he": "ברוכין",
    "name_en": "Brukhin",
    "lat": 32.080006,
    "lng": 35.087337,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "berakha",
    "name_he": "ברכה",
    "name_en": "Berakha",
    "lat": 32.192882,
    "lng": 35.265381,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "הר ברכה"
    ]
  },
  {
    "id": "barqan",
    "name_he": "ברקן",
    "name_en": "Barqan",
    "lat": 32.107854,
    "lng": 35.107994,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "bat_ayin",
    "name_he": "בת עין",
    "name_en": "Bat Ayin",
    "lat": 31.658823,
    "lng": 35.100011,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "geva_binyamin",
    "name_he": "גבע בנימין",
    "name_en": "Geva Binyamin",
    "lat": 31.849898,
    "lng": 35.275807,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "givon_hahadasha",
    "name_he": "גבעון החדשה",
    "name_en": "Giv'on Hahadasha",
    "lat": 31.848173,
    "lng": 35.158692,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "givat_zeev",
    "name_he": "גבעת זאב",
    "name_en": "Givat Ze'ev",
    "lat": 31.8608,
    "lng": 35.1727,
    "region": "judea_samaria",
    "type": "local_council"
  },
  {
    "id": "gittit",
    "name_he": "גיתית",
    "name_en": "Gittit",
    "lat": 32.10204,
    "lng": 35.397583,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "gilgal",
    "name_he": "גלגל",
    "name_en": "Gilgal",
    "lat": 31.999377,
    "lng": 35.445348,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "dolev",
    "name_he": "דולב",
    "name_en": "Dolev",
    "lat": 31.926454,
    "lng": 35.133118,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "har_adar",
    "name_he": "הר אדר",
    "name_en": "Har Adar",
    "lat": 31.826729,
    "lng": 35.129428,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "har_gillo",
    "name_he": "הר גילה",
    "name_en": "Har Gillo",
    "lat": 31.724341,
    "lng": 35.165662,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "wered_yeriho",
    "name_he": "ורד יריחו",
    "name_en": "Wered Yeriho",
    "lat": 31.826377,
    "lng": 35.436015,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "hebron",
    "name_he": "חברון",
    "name_en": "Hebron",
    "lat": 31.530099,
    "lng": 35.093058,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "haggai",
    "name_he": "חגי",
    "name_en": "Haggai",
    "lat": 31.492868,
    "lng": 35.080194,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "בית חג\"י"
    ]
  },
  {
    "id": "hinnanit",
    "name_he": "חיננית",
    "name_en": "Hinnanit",
    "lat": 32.480596,
    "lng": 35.172167,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "nahal_hemdat",
    "name_he": "חמדת",
    "name_en": "Nahal Hemdat",
    "lat": 32.2512,
    "lng": 35.526581,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "hamra",
    "name_he": "חמרה",
    "name_en": "Hamra",
    "lat": 32.200138,
    "lng": 35.437581,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "hermesh",
    "name_he": "חרמש",
    "name_en": "Hermesh",
    "lat": 32.423657,
    "lng": 35.118759,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "hashmonaim",
    "name_he": "חשמונאים",
    "name_en": "Hashmona'im",
    "lat": 31.931247,
    "lng": 35.02375,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "talmon",
    "name_he": "טלמון",
    "name_en": "Talmon",
    "lat": 31.936299,
    "lng": 35.139637,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "tene",
    "name_he": "טנא",
    "name_en": "Tene",
    "lat": 31.37449,
    "lng": 34.956629,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "טנא עומרים"
    ]
  },
  {
    "id": "yitav",
    "name_he": "ייט\"ב",
    "name_en": "Yitav",
    "lat": 31.94749,
    "lng": 35.424844,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "yafit",
    "name_he": "יפית",
    "name_en": "Yafit",
    "lat": 32.063172,
    "lng": 35.473973,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "yizhar",
    "name_he": "יצהר",
    "name_en": "Yizhar",
    "lat": 32.168513,
    "lng": 35.237197,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "yaqir",
    "name_he": "יקיר",
    "name_en": "Yaqir",
    "lat": 32.148955,
    "lng": 35.113351,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kokhav_hashahar",
    "name_he": "כוכב השחר",
    "name_en": "Kokhav Hashahar",
    "lat": 31.960828,
    "lng": 35.349677,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kokhav_yaaqov",
    "name_he": "כוכב יעקב",
    "name_en": "Kokhav Ya'aqov",
    "lat": 31.882159,
    "lng": 35.242891,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kefar_adummim",
    "name_he": "כפר אדומים",
    "name_en": "Kefar Adummim",
    "lat": 31.82563,
    "lng": 35.329186,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kefar_haoranim",
    "name_he": "כפר האורנים",
    "name_en": "Kefar Haoranim",
    "lat": 31.919925,
    "lng": 35.036879,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kefar_ezyon",
    "name_he": "כפר עציון",
    "name_en": "Kefar Ezyon",
    "lat": 31.649242,
    "lng": 35.11542,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kefar_tappuah",
    "name_he": "כפר תפוח",
    "name_en": "Kefar Tappuah",
    "lat": 32.11951,
    "lng": 35.249838,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "karme_zur",
    "name_he": "כרמי צור",
    "name_en": "Karme Zur",
    "lat": 31.60867,
    "lng": 35.100131,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "karmel",
    "name_he": "כרמל",
    "name_en": "Karmel",
    "lat": 31.429988,
    "lng": 35.183755,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "mevo_dotan",
    "name_he": "מבוא דותן",
    "name_en": "Mevo Dotan",
    "lat": 32.420163,
    "lng": 35.175493,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "mevo_horon",
    "name_he": "מבוא חורון",
    "name_en": "Mevo Horon",
    "lat": 31.849942,
    "lng": 35.034979,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "migdal_oz",
    "name_he": "מגדל עוז",
    "name_en": "Migdal Oz",
    "lat": 31.639267,
    "lng": 35.143472,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "migdalim",
    "name_he": "מגדלים",
    "name_en": "Migdalim",
    "lat": 32.090229,
    "lng": 35.34227,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "mehola",
    "name_he": "מחולה",
    "name_en": "Mehola",
    "lat": 32.365369,
    "lng": 35.515702,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "mekhora",
    "name_he": "מכורה",
    "name_en": "Mekhora",
    "lat": 32.164626,
    "lng": 35.423011,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "maon",
    "name_he": "מעון",
    "name_en": "Ma'on",
    "lat": 31.409088,
    "lng": 35.160291,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "maale_efrayim",
    "name_he": "מעלה אפרים",
    "name_en": "Ma'ale Efrayim",
    "lat": 32.069932,
    "lng": 35.405029,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "maale_levona",
    "name_he": "מעלה לבונה",
    "name_en": "Ma'ale Levona",
    "lat": 32.054864,
    "lng": 35.240346,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "maale_mikhmas",
    "name_he": "מעלה מכמש",
    "name_en": "Ma'ale Mikhmas",
    "lat": 31.879345,
    "lng": 35.306075,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "maale_amos",
    "name_he": "מעלה עמוס",
    "name_en": "Ma'ale Amos",
    "lat": 31.596404,
    "lng": 35.229869,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "bet_yattir",
    "name_he": "מצדות יהודה",
    "name_en": "Bet Yattir",
    "lat": 31.363937,
    "lng": 35.112641,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "בית יתיר"
    ]
  },
  {
    "id": "mizpe_yeriho",
    "name_he": "מצפה יריחו",
    "name_en": "Mizpe Yeriho",
    "lat": 31.815734,
    "lng": 35.3941,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "mizpe_shalem",
    "name_he": "מצפה שלם",
    "name_en": "Mizpe Shalem",
    "lat": 31.568182,
    "lng": 35.401781,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "massua",
    "name_he": "משואה",
    "name_en": "Massu'a",
    "lat": 32.112815,
    "lng": 35.490676,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "maskiyyot",
    "name_he": "משכיות",
    "name_en": "Maskiyyot",
    "lat": 32.318176,
    "lng": 35.502231,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "mattityahu",
    "name_he": "מתתיהו",
    "name_en": "Mattityahu",
    "lat": 31.929582,
    "lng": 35.034625,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "negohot",
    "name_he": "נגוהות",
    "name_en": "Negohot",
    "lat": 31.492971,
    "lng": 34.983238,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "neve_tsuf",
    "name_he": "נוה צוף",
    "name_en": "Neve Tsuf",
    "lat": 32.006241,
    "lng": 35.125511,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "נווה צוף"
    ]
  },
  {
    "id": "newe_daniyyel",
    "name_he": "נווה דניאל",
    "name_en": "Newe Daniyyel",
    "lat": 31.67841,
    "lng": 35.142969,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "nofim",
    "name_he": "נופים",
    "name_en": "Nofim",
    "lat": 32.155489,
    "lng": 35.102646,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "noqedim",
    "name_he": "נוקדים",
    "name_en": "Noqedim",
    "lat": 31.645142,
    "lng": 35.243217,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "nahaliel",
    "name_he": "נחליאל",
    "name_en": "Nahali'el",
    "lat": 31.973944,
    "lng": 35.140138,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "nili",
    "name_he": "ניל\"י",
    "name_en": "Nili",
    "lat": 31.964777,
    "lng": 35.048018,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "נילי"
    ]
  },
  {
    "id": "naale",
    "name_he": "נעלה",
    "name_en": "Na'ale",
    "lat": 31.96099,
    "lng": 35.060185,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "naama",
    "name_he": "נעמ\"ה",
    "name_en": "Naama",
    "lat": 31.907371,
    "lng": 35.466403,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "נעמה"
    ]
  },
  {
    "id": "naaran",
    "name_he": "נערן",
    "name_en": "Na'aran",
    "lat": 31.967315,
    "lng": 35.455614,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "netiv_hagedud",
    "name_he": "נתיב הגדוד",
    "name_en": "Netiv Hagedud",
    "lat": 31.988361,
    "lng": 35.445247,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "suseya",
    "name_he": "סוסיה",
    "name_en": "Suseya",
    "lat": 31.391359,
    "lng": 35.113925,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "סוסיא"
    ]
  },
  {
    "id": "salit",
    "name_he": "סלעית",
    "name_en": "Sal'it",
    "lat": 32.242389,
    "lng": 35.049905,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "sansanna",
    "name_he": "סנסנה",
    "name_en": "Sansanna",
    "lat": 31.362982,
    "lng": 34.90324,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "ofra",
    "name_he": "עופרה",
    "name_en": "Ofra",
    "lat": 31.953843,
    "lng": 35.261482,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "עפרה"
    ]
  },
  {
    "id": "ateret",
    "name_he": "עטרת",
    "name_en": "Ateret",
    "lat": 32.000352,
    "lng": 35.176451,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "eli",
    "name_he": "עלי",
    "name_en": "Eli",
    "lat": 32.068911,
    "lng": 35.261068,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "ale_zahav",
    "name_he": "עלי זהב",
    "name_en": "Ale Zahav",
    "lat": 32.069238,
    "lng": 35.067437,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "almon",
    "name_he": "עלמון",
    "name_en": "Almon",
    "lat": 31.83018,
    "lng": 35.294069,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "ammihay",
    "name_he": "עמיחי",
    "name_en": "Ammihay",
    "lat": 32.045942,
    "lng": 35.328153,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "immanuel",
    "name_he": "עמנואל",
    "name_en": "Immanu'el",
    "lat": 32.161625,
    "lng": 35.139396,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "enav",
    "name_he": "ענב",
    "name_en": "Enav",
    "lat": 32.285994,
    "lng": 35.127323,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "otniel",
    "name_he": "עתניאל",
    "name_en": "Otni'el",
    "lat": 31.43919,
    "lng": 35.030205,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "peduel",
    "name_he": "פדואל",
    "name_en": "Pedu'el",
    "lat": 32.061852,
    "lng": 35.051775,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "pene_hever",
    "name_he": "פני חבר",
    "name_en": "Pene Hever",
    "lat": 31.485755,
    "lng": 35.165515,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "מעלה חבר"
    ]
  },
  {
    "id": "pesagot",
    "name_he": "פסגות",
    "name_en": "Pesagot",
    "lat": 31.898538,
    "lng": 35.225312,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "pezael",
    "name_he": "פצאל",
    "name_en": "Peza'el",
    "lat": 32.044561,
    "lng": 35.442702,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "zufin",
    "name_he": "צופים",
    "name_en": "Zufin",
    "lat": 32.196873,
    "lng": 35.010031,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "kedumim",
    "name_he": "קדומים",
    "name_en": "Kedumim",
    "lat": 32.1777,
    "lng": 35.1524,
    "region": "judea_samaria",
    "type": "local_council"
  },
  {
    "id": "qedar",
    "name_he": "קדר",
    "name_en": "Qedar",
    "lat": 31.753966,
    "lng": 35.310369,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "qalya",
    "name_he": "קליה",
    "name_en": "Qalya",
    "lat": 31.750497,
    "lng": 35.466946,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "qiryat_arba",
    "name_he": "קרית ארבע",
    "name_en": "Qiryat Arba",
    "lat": 31.54231,
    "lng": 35.120572,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "qiryat_netafim",
    "name_he": "קרית נטפים",
    "name_en": "Qiryat Netafim",
    "lat": 32.116878,
    "lng": 35.112278,
    "region": "judea_samaria",
    "type": "town",
    "aliases": [
      "קריית נטפים"
    ]
  },
  {
    "id": "karnei_shomron",
    "name_he": "קרני שומרון",
    "name_en": "Karnei Shomron",
    "lat": 32.1734,
    "lng": 35.0971,
    "region": "judea_samaria",
    "type": "local_council"
  },
  {
    "id": "rosh_zurim",
    "name_he": "ראש צורים",
    "name_en": "Rosh Zurim",
    "lat": 31.667429,
    "lng": 35.124061,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "revava",
    "name_he": "רבבה",
    "name_en": "Revava",
    "lat": 32.118831,
    "lng": 35.127703,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "roi",
    "name_he": "רועי",
    "name_en": "Ro'i",
    "lat": 32.24826,
    "lng": 35.483777,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "rotem",
    "name_he": "רותם",
    "name_en": "Rotem",
    "lat": 32.33672,
    "lng": 35.518244,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "rehelim",
    "name_he": "רחלים",
    "name_en": "Rehelim",
    "lat": 32.101963,
    "lng": 35.256468,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "rehan",
    "name_he": "ריחן",
    "name_en": "Rehan",
    "lat": 32.468299,
    "lng": 35.136308,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "rimmonim",
    "name_he": "רימונים",
    "name_en": "Rimmonim",
    "lat": 31.934054,
    "lng": 35.34065,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "shave_shomeron",
    "name_he": "שבי שומרון",
    "name_en": "Shave Shomeron",
    "lat": 32.263491,
    "lng": 35.185201,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "shadmot_mehola",
    "name_he": "שדמות מחולה",
    "name_en": "Shadmot Mehola",
    "lat": 32.346005,
    "lng": 35.534728,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "shilo",
    "name_he": "שילה",
    "name_en": "Shilo",
    "lat": 32.053308,
    "lng": 35.297784,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "shima",
    "name_he": "שמעה",
    "name_en": "Shim'a",
    "lat": 31.387616,
    "lng": 35.012543,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "shaqed",
    "name_he": "שקד",
    "name_en": "Shaqed",
    "lat": 32.473835,
    "lng": 35.168755,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "tomer",
    "name_he": "תומר",
    "name_en": "Tomer",
    "lat": 32.018538,
    "lng": 35.439202,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "telem",
    "name_he": "תלם",
    "name_en": "Telem",
    "lat": 31.564563,
    "lng": 35.030981,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "teqoa",
    "name_he": "תקוע",
    "name_en": "Teqoa",
    "lat": 31.653136,
    "lng": 35.229336,
    "region": "judea_samaria",
    "type": "town"
  },
  {
    "id": "avigayil",
    "name_he": "אביגיל",
    "name_en": "Avigayil",
    "lat": 31.403512,
    "lng": 35.142374,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "evyatar",
    "name_he": "אביתר",
    "name_en": "Evyatar",
    "lat": 32.120521,
    "lng": 35.277202,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "ahiya",
    "name_he": "אחיה",
    "name_en": "Ahiya",
    "lat": 32.06091,
    "lng": 35.328256,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "ivei_hanahal",
    "name_he": "איבי הנחל",
    "name_en": "Ibei HaNahal",
    "lat": 31.604,
    "lng": 35.219089,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "esh_kodesh",
    "name_he": "אש קודש",
    "name_en": "Esh Kodesh",
    "lat": 32.06517,
    "lng": 35.337695,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "gvaot",
    "name_he": "גבעות",
    "name_en": "Gvaot",
    "lat": 31.679403,
    "lng": 35.101451,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "givat_asaf",
    "name_he": "גבעת אסף",
    "name_en": "Giv'at Asaf",
    "lat": 31.908592,
    "lng": 35.248044,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "givat_harel",
    "name_he": "גבעת הראל",
    "name_en": "Giv'at Harel",
    "lat": 32.058219,
    "lng": 35.275672,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "givat_haroeh",
    "name_he": "גבעת הרואה",
    "name_en": "Giv'at HaRo'eh",
    "lat": 32.054137,
    "lng": 35.263313,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "beit_habracha",
    "name_he": "בית הברכה",
    "name_en": "Beit HaBerakhah",
    "lat": 31.632275,
    "lng": 35.131664,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_gilead",
    "name_he": "חוות גלעד",
    "name_en": "Havat Gilad",
    "lat": 32.195196,
    "lng": 35.183544,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "harasha",
    "name_he": "חרשה",
    "name_en": "Harasha",
    "lat": 31.94397,
    "lng": 35.143618,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "tal_menashe",
    "name_he": "טל מנשה",
    "name_en": "Tal Menashe",
    "lat": 32.483176,
    "lng": 35.161686,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "migron",
    "name_he": "מגרון",
    "name_en": "Migron",
    "lat": 31.874695,
    "lng": 35.259658,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "adurim",
    "name_he": "אדורים",
    "name_en": "Adurim",
    "lat": 31.484847,
    "lng": 35.043797,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "eshtemoa",
    "name_he": "אשתמוע",
    "name_en": "Eshtemoa",
    "lat": 31.393005,
    "lng": 35.015785,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "dorot_illit",
    "name_he": "דורות עילית",
    "name_en": "Dorot Illit",
    "lat": 32.137488,
    "lng": 35.062315,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "hebron_jewish_community",
    "name_he": "היישוב היהודי חברון",
    "name_en": "Hebron Jewish Community",
    "lat": 31.525162,
    "lng": 35.109098,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_avihi",
    "name_he": "חוות אביחי",
    "name_en": "Havat Avihi",
    "lat": 32.04636,
    "lng": 35.036204,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_elhai",
    "name_he": "חוות אלחי",
    "name_en": "Havat Elhai",
    "lat": 32.276446,
    "lng": 35.155804,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_talia",
    "name_he": "חוות טליה",
    "name_en": "Havat Talia",
    "lat": 31.367378,
    "lng": 35.124279,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_yair",
    "name_he": "חוות יאיר",
    "name_en": "Havat Yair",
    "lat": 32.144838,
    "lng": 35.107003,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_nahalat_avot",
    "name_he": "חוות נחלת אבות",
    "name_en": "Havat Nahalat Avot",
    "lat": 31.57758,
    "lng": 35.196304,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_eden",
    "name_he": "חוות עדן",
    "name_en": "Havat Eden",
    "lat": 31.700028,
    "lng": 35.141168,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_qashoala",
    "name_he": "חוות קשואלה",
    "name_en": "Havat Qashoala",
    "lat": 31.67581,
    "lng": 35.101919,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_tzaan_kedar",
    "name_he": "חוות צאן קדר",
    "name_en": "Havat Tzaan Kedar",
    "lat": 31.735933,
    "lng": 35.320223,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_shoviel",
    "name_he": "חוות שוביאל",
    "name_en": "Havat Shoviel",
    "lat": 32.079689,
    "lng": 35.13597,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_shacharit",
    "name_he": "חוות שחרית",
    "name_en": "Havat Shacharit",
    "lat": 32.090298,
    "lng": 35.072916,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_telem_north",
    "name_he": "חוות תלם צפון",
    "name_en": "Havat Telem North",
    "lat": 31.571056,
    "lng": 35.037356,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "homesh",
    "name_he": "חומש",
    "name_en": "Homesh",
    "lat": 32.310681,
    "lng": 35.191882,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "alon",
    "name_he": "אלון",
    "name_en": "Alon",
    "lat": 31.830774,
    "lng": 35.353582,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "bnei_adam",
    "name_he": "בני אדם",
    "name_en": "Bnei Adam",
    "lat": 31.843438,
    "lng": 35.306404,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "gofna",
    "name_he": "גופנה",
    "name_en": "Gofna",
    "lat": 31.979189,
    "lng": 35.125037,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "neve_erez",
    "name_he": "נווה ארז",
    "name_en": "Neve Erez",
    "lat": 31.864592,
    "lng": 35.309966,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "pnei_kedem",
    "name_he": "פני קדם",
    "name_en": "Pnei Kedem",
    "lat": 31.584736,
    "lng": 35.202338,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "sde_boaz",
    "name_he": "שדה בועז",
    "name_en": "Sde Boaz",
    "lat": 31.691828,
    "lng": 35.144468,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_neve_tsuf",
    "name_he": "חוות נווה צוף",
    "name_en": "Havat Neve Tsuf",
    "lat": 32.006832,
    "lng": 35.144887,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_nahal_shilo",
    "name_he": "חוות נחל שילה",
    "name_en": "Havat Nahal Shilo",
    "lat": 32.047518,
    "lng": 35.281619,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_migdalim",
    "name_he": "חוות מגדלים",
    "name_en": "Havat Migdalim",
    "lat": 32.09511,
    "lng": 35.352398,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_droma",
    "name_he": "חוות דרומא",
    "name_en": "Havat Droma",
    "lat": 31.396841,
    "lng": 35.145878,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "havat_haroeh_haivri",
    "name_he": "חוות הרועה העברי",
    "name_en": "Havat HaRo'eh HaIvri",
    "lat": 31.812158,
    "lng": 35.321322,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "shvut_rachel",
    "name_he": "שבות רחל",
    "name_en": "Shvut Rachel",
    "lat": 32.055043,
    "lng": 35.311074,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "kida",
    "name_he": "קידה",
    "name_en": "Kida",
    "lat": 32.050941,
    "lng": 35.343091,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "nofei_prat",
    "name_he": "נופי פרת",
    "name_en": "Nofei Prat",
    "lat": 31.822108,
    "lng": 35.321562,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "kfar_eldad",
    "name_he": "כפר אלדד",
    "name_en": "Kfar Eldad",
    "lat": 31.648011,
    "lng": 35.253398,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "mitzpe_yair",
    "name_he": "מצפה יאיר",
    "name_en": "Mitzpe Yair",
    "lat": 31.384215,
    "lng": 35.136093,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "adei_ad",
    "name_he": "עדי עד",
    "name_en": "Adei Ad",
    "lat": 32.040458,
    "lng": 35.335781,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "susia_hakeduma",
    "name_he": "סוסיא הקדומה",
    "name_en": "Susia HaKeduma",
    "lat": 31.40519,
    "lng": 35.103386,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "neriya",
    "name_he": "נריה",
    "name_en": "Neriya",
    "lat": 31.953483,
    "lng": 35.12599,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "nofei_nehemiah",
    "name_he": "נופי נחמיה",
    "name_en": "Nofei Nehemiah",
    "lat": 32.098523,
    "lng": 35.237257,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "ashael",
    "name_he": "עשהאל",
    "name_en": "Ashael",
    "lat": 31.373635,
    "lng": 35.040455,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "ofarim",
    "name_he": "עופרים",
    "name_en": "Ofarim",
    "lat": 32.019879,
    "lng": 35.04523,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "tel_tzion",
    "name_he": "תל ציון",
    "name_en": "Tel Tzion",
    "lat": 31.880892,
    "lng": 35.238763,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "kedar_south",
    "name_he": "קדר דרום",
    "name_en": "Kedar South",
    "lat": 31.746284,
    "lng": 35.301488,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "aira_hashahar",
    "name_he": "אעירה השחר",
    "name_en": "A'ira HaShahar",
    "lat": 31.95027,
    "lng": 35.368398,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "afeka",
    "name_he": "אפקה",
    "name_en": "Afeka",
    "lat": 31.468602,
    "lng": 35.038062,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "bar_kokhba",
    "name_he": "בר כוכבא",
    "name_en": "Bar Kokhba",
    "lat": 31.71235,
    "lng": 35.15987,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "sde_efraim",
    "name_he": "שדה אפרים",
    "name_en": "Sde Efraim",
    "lat": 31.939424,
    "lng": 35.090768,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "sde_bar",
    "name_he": "שדה בר",
    "name_en": "Sde Bar",
    "lat": 31.660199,
    "lng": 35.244481,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "ramat_migron",
    "name_he": "רמת מגרון",
    "name_en": "Ramat Migron",
    "lat": 31.886816,
    "lng": 35.273349,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "hagivah_hatzehubah",
    "name_he": "הגבעה הצהובה",
    "name_en": "HaGivah HaTzehubah",
    "lat": 31.657895,
    "lng": 35.120337,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "givat_porat_yosef",
    "name_he": "גבעת פורת יוסף",
    "name_en": "Givat Porat Yosef",
    "lat": 32.214997,
    "lng": 35.370401,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "shaarei_tikva",
    "name_he": "שערי תקווה",
    "name_en": "Sha'arei Tikva",
    "lat": 32.12175,
    "lng": 35.026275,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "etz_efraim",
    "name_he": "עץ אפרים",
    "name_en": "Etz Efraim",
    "lat": 32.119461,
    "lng": 35.046127,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "kerem_reim",
    "name_he": "כרם רעים",
    "name_en": "Kerem Reim",
    "lat": 31.959098,
    "lng": 35.140304,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "mechinat_elisha",
    "name_he": "מכינת אלישע",
    "name_en": "Mechinat Elisha",
    "lat": 32.01136,
    "lng": 35.138588,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "malachei_hashalom",
    "name_he": "מלאכי השלום",
    "name_en": "Malachei HaShalom",
    "lat": 32.026379,
    "lng": 35.365097,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "maale_rehavam",
    "name_he": "מעלה רחבעם",
    "name_en": "Ma'ale Rehavam",
    "lat": 31.649915,
    "lng": 35.258841,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "mitzpe_dani",
    "name_he": "מצפה דני",
    "name_en": "Mitzpe Dani",
    "lat": 31.88028,
    "lng": 35.314705,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "mitzpe_ziv",
    "name_he": "מצפה זי\"ו",
    "name_en": "Mitzpe Ziv",
    "lat": 31.484143,
    "lng": 35.144821,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "mitzpe_hagit",
    "name_he": "מצפה חגית",
    "name_en": "Mitzpe Hagit",
    "lat": 31.85139,
    "lng": 35.336908,
    "region": "judea_samaria",
    "type": "settlement"
  },
  {
    "id": "shlomtzion",
    "name_he": "שלומציון",
    "name_en": "Shlomtzion",
    "lat": 32.099687,
    "lng": 35.494737,
    "region": "judea_samaria",
    "type": "settlement"
  }
];
