import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "abu_sinan",
    "name_he": "אבו סנאן",
    "name_en": "Abu Sinan",
    "lat": 32.961027,
    "lng": 35.169463,
    "region": "north",
    "type": "town"
  },
  {
    "id": "avtalyon",
    "name_he": "אבטליון",
    "name_en": "Avtalyon",
    "lat": 32.837072,
    "lng": 35.351539,
    "region": "north",
    "type": "town"
  },
  {
    "id": "avivim",
    "name_he": "אביבים",
    "name_en": "Avivim",
    "lat": 33.088926,
    "lng": 35.471282,
    "region": "north",
    "type": "town"
  },
  {
    "id": "avital",
    "name_he": "אביטל",
    "name_en": "Avital",
    "lat": 32.557447,
    "lng": 35.30449,
    "region": "north",
    "type": "town"
  },
  {
    "id": "abbirim",
    "name_he": "אבירים",
    "name_en": "Abbirim",
    "lat": 33.038356,
    "lng": 35.287129,
    "region": "north",
    "type": "town"
  },
  {
    "id": "even_menahem",
    "name_he": "אבן מנחם",
    "name_en": "Even Menahem",
    "lat": 33.073538,
    "lng": 35.292897,
    "region": "north",
    "type": "town"
  },
  {
    "id": "avne_etan",
    "name_he": "אבני איתן",
    "name_en": "Avne Etan",
    "lat": 32.824608,
    "lng": 35.766179,
    "region": "north",
    "type": "town"
  },
  {
    "id": "addirim",
    "name_he": "אדירים",
    "name_en": "Addirim",
    "lat": 32.549099,
    "lng": 35.27201,
    "region": "north",
    "type": "town"
  },
  {
    "id": "adamit",
    "name_he": "אדמית",
    "name_en": "Adamit",
    "lat": 33.079843,
    "lng": 35.20908,
    "region": "north",
    "type": "town"
  },
  {
    "id": "odem",
    "name_he": "אודם",
    "name_en": "Odem",
    "lat": 33.193228,
    "lng": 35.74999,
    "region": "north",
    "type": "town"
  },
  {
    "id": "omen",
    "name_he": "אומן",
    "name_en": "Omen",
    "lat": 32.563308,
    "lng": 35.242399,
    "region": "north",
    "type": "town"
  },
  {
    "id": "or_haganuz",
    "name_he": "אור הגנוז",
    "name_en": "Or Haganuz",
    "lat": 33.005744,
    "lng": 35.446042,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ortal",
    "name_he": "אורטל",
    "name_en": "Ortal",
    "lat": 33.084686,
    "lng": 35.761666,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ahuzzat_baraq",
    "name_he": "אחוזת ברק",
    "name_en": "Ahuzzat Baraq",
    "lat": 32.643751,
    "lng": 35.337364,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ahihud",
    "name_he": "אחיהוד",
    "name_en": "Ahihud",
    "lat": 32.907159,
    "lng": 35.176097,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ayyelet_hashahar",
    "name_he": "איילת השחר",
    "name_en": "Ayyelet Hashahar",
    "lat": 33.022559,
    "lng": 35.578312,
    "region": "north",
    "type": "town"
  },
  {
    "id": "elon",
    "name_he": "אילון",
    "name_en": "Elon",
    "lat": 33.063915,
    "lng": 35.217728,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ilaniyya",
    "name_he": "אילניה",
    "name_en": "Ilaniyya",
    "lat": 32.754651,
    "lng": 35.406475,
    "region": "north",
    "type": "town"
  },
  {
    "id": "iksal",
    "name_he": "אכסאל",
    "name_en": "Iksal",
    "lat": 32.680741,
    "lng": 35.322528,
    "region": "north",
    "type": "town"
  },
  {
    "id": "el_rom",
    "name_he": "אל-רום",
    "name_en": "El-Rom",
    "lat": 33.178995,
    "lng": 35.771573,
    "region": "north",
    "type": "town"
  },
  {
    "id": "alummot",
    "name_he": "אלומות",
    "name_en": "Alummot",
    "lat": 32.707354,
    "lng": 35.545869,
    "region": "north",
    "type": "town"
  },
  {
    "id": "allon_hagalil",
    "name_he": "אלון הגליל",
    "name_en": "Allon Hagalil",
    "lat": 32.758132,
    "lng": 35.219687,
    "region": "north",
    "type": "town"
  },
  {
    "id": "allone_abba",
    "name_he": "אלוני אבא",
    "name_en": "Allone Abba",
    "lat": 32.729173,
    "lng": 35.171029,
    "region": "north",
    "type": "town"
  },
  {
    "id": "allone_habashan",
    "name_he": "אלוני הבשן",
    "name_en": "Allone Habashan",
    "lat": 33.041914,
    "lng": 35.838682,
    "region": "north",
    "type": "town"
  },
  {
    "id": "allonim",
    "name_he": "אלונים",
    "name_en": "Allonim",
    "lat": 32.720876,
    "lng": 35.144199,
    "region": "north",
    "type": "town"
  },
  {
    "id": "eli_ad",
    "name_he": "אלי-עד",
    "name_en": "Eli-Ad",
    "lat": 32.805441,
    "lng": 35.735574,
    "region": "north",
    "type": "town"
  },
  {
    "id": "elifelet",
    "name_he": "אליפלט",
    "name_en": "Elifelet",
    "lat": 32.947004,
    "lng": 35.548899,
    "region": "north",
    "type": "town"
  },
  {
    "id": "elyaqim",
    "name_he": "אליקים",
    "name_en": "Elyaqim",
    "lat": 32.631794,
    "lng": 35.067242,
    "region": "north",
    "type": "town"
  },
  {
    "id": "almagor",
    "name_he": "אלמגור",
    "name_en": "Almagor",
    "lat": 32.911342,
    "lng": 35.602387,
    "region": "north",
    "type": "town"
  },
  {
    "id": "elqosh",
    "name_he": "אלקוש",
    "name_en": "Elqosh",
    "lat": 33.033294,
    "lng": 35.323788,
    "region": "north",
    "type": "town"
  },
  {
    "id": "amirim",
    "name_he": "אמירים",
    "name_en": "Amirim",
    "lat": 32.938142,
    "lng": 35.449411,
    "region": "north",
    "type": "town"
  },
  {
    "id": "amnun",
    "name_he": "אמנון",
    "name_en": "Amnun",
    "lat": 32.904028,
    "lng": 35.573297,
    "region": "north",
    "type": "town"
  },
  {
    "id": "aniam",
    "name_he": "אניעם",
    "name_en": "Ani'am",
    "lat": 32.957934,
    "lng": 35.7405,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ibillin",
    "name_he": "אעבלין",
    "name_en": "I'billin",
    "lat": 32.824073,
    "lng": 35.191121,
    "region": "north",
    "type": "town"
  },
  {
    "id": "afiq",
    "name_he": "אפיק",
    "name_en": "Afiq",
    "lat": 32.77849,
    "lng": 35.702811,
    "region": "north",
    "type": "town"
  },
  {
    "id": "afiqim",
    "name_he": "אפיקים",
    "name_en": "Afiqim",
    "lat": 32.680693,
    "lng": 35.578283,
    "region": "north",
    "type": "town"
  },
  {
    "id": "afeq",
    "name_he": "אפק",
    "name_en": "Afeq",
    "lat": 32.839405,
    "lng": 35.12802,
    "region": "north",
    "type": "town"
  },
  {
    "id": "arbel",
    "name_he": "ארבל",
    "name_en": "Arbel",
    "lat": 32.812565,
    "lng": 35.483708,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nahal_eshbal",
    "name_he": "אשבל",
    "name_en": "Nahal Eshbal",
    "lat": 32.876665,
    "lng": 35.304931,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ashdot_yaaqov_ihud",
    "name_he": "אשדות יעקב (איחוד)",
    "name_en": "Ashdot Ya'aqov(ihud)",
    "lat": 32.658548,
    "lng": 35.580429,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ashdot_yaaqov_meuh",
    "name_he": "אשדות יעקב (מאוחד)",
    "name_en": "Ashdot Ya'aqov(me'uh",
    "lat": 32.665559,
    "lng": 35.581538,
    "region": "north",
    "type": "town"
  },
  {
    "id": "eshhar",
    "name_he": "אשחר",
    "name_en": "Eshhar",
    "lat": 32.885894,
    "lng": 35.300499,
    "region": "north",
    "type": "town"
  },
  {
    "id": "asherat",
    "name_he": "אשרת",
    "name_en": "Asherat",
    "lat": 32.970718,
    "lng": 35.157259,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bustan_hagalil",
    "name_he": "בוסתן הגליל",
    "name_en": "Bustan Hagalil",
    "lat": 32.951281,
    "lng": 35.082695,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bueine_nujeidat",
    "name_he": "בועיינה-נוג'ידאת",
    "name_en": "Bu'eine-Nujeidat",
    "lat": 32.807866,
    "lng": 35.368775,
    "region": "north",
    "type": "town"
  },
  {
    "id": "buqata",
    "name_he": "בוקעאתא",
    "name_en": "Buq'ata",
    "lat": 33.200135,
    "lng": 35.78007,
    "region": "north",
    "type": "town",
    "aliases": [
      "בוקעתא"
    ]
  },
  {
    "id": "bir_el_maksur",
    "name_he": "ביר אל-מכסור",
    "name_en": "Bir El-Maksur",
    "lat": 32.778946,
    "lng": 35.222938,
    "region": "north",
    "type": "town",
    "aliases": [
      "ביר אלמכסור"
    ]
  },
  {
    "id": "biriyya",
    "name_he": "ביריה",
    "name_en": "Biriyya",
    "lat": 32.978222,
    "lng": 35.500106,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_alfa",
    "name_he": "בית אלפא",
    "name_en": "Bet Alfa",
    "lat": 32.517038,
    "lng": 35.432293,
    "region": "north",
    "type": "town"
  },
  {
    "id": "beit_jann",
    "name_he": "בית ג'ן",
    "name_en": "Beit Jann",
    "lat": 32.964635,
    "lng": 35.37854,
    "region": "north",
    "type": "town",
    "aliases": [
      "בית ג'אן"
    ]
  },
  {
    "id": "bet_hillel",
    "name_he": "בית הלל",
    "name_en": "Bet Hillel",
    "lat": 33.209514,
    "lng": 35.60523,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_haemeq",
    "name_he": "בית העמק",
    "name_en": "Bet Haemeq",
    "lat": 32.970578,
    "lng": 35.1453,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_hashitta",
    "name_he": "בית השיטה",
    "name_en": "Bet Hashitta",
    "lat": 32.550464,
    "lng": 35.439321,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_zeid",
    "name_he": "בית זיד",
    "name_en": "Bet Zeid",
    "lat": 32.701796,
    "lng": 35.114458,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_zera",
    "name_he": "בית זרע",
    "name_en": "Bet Zera",
    "lat": 32.688766,
    "lng": 35.573496,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_yosef",
    "name_he": "בית יוסף",
    "name_en": "Bet Yosef",
    "lat": 32.556606,
    "lng": 35.547182,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_lehem_hagelilit",
    "name_he": "בית לחם הגלילית",
    "name_en": "Bet Lehem Hagelilit",
    "lat": 32.734601,
    "lng": 35.191869,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_qeshet",
    "name_he": "בית קשת",
    "name_en": "Bet Qeshet",
    "lat": 32.71863,
    "lng": 35.393788,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bet_rimmon",
    "name_he": "בית רימון",
    "name_en": "Bet Rimmon",
    "lat": 32.782728,
    "lng": 35.33017,
    "region": "north",
    "type": "town"
  },
  {
    "id": "beit_shean",
    "name_he": "בית שאן",
    "name_en": "Beit She'an",
    "lat": 32.4974,
    "lng": 35.4968,
    "region": "north",
    "type": "city"
  },
  {
    "id": "bet_shearim",
    "name_he": "בית שערים",
    "name_en": "Bet She'arim",
    "lat": 32.695823,
    "lng": 35.177601,
    "region": "north",
    "type": "town"
  },
  {
    "id": "balfuriyya",
    "name_he": "בלפוריה",
    "name_en": "Balfuriyya",
    "lat": 32.630173,
    "lng": 35.29672,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ben_ammi",
    "name_he": "בן עמי",
    "name_en": "Ben Ammi",
    "lat": 33.004198,
    "lng": 35.123711,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bene_yehuda",
    "name_he": "בני יהודה",
    "name_en": "Bene Yehuda",
    "lat": 32.798252,
    "lng": 35.68951,
    "region": "north",
    "type": "town"
  },
  {
    "id": "basmat_tabun",
    "name_he": "בסמת טבעון",
    "name_en": "Basmat Tab'un",
    "lat": 32.735638,
    "lng": 35.142019,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bi_ne",
    "name_he": "בענה",
    "name_en": "Bi Ne",
    "lat": 32.928931,
    "lng": 35.27491,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bezet",
    "name_he": "בצת",
    "name_en": "Bezet",
    "lat": 33.070687,
    "lng": 35.134453,
    "region": "north",
    "type": "town"
  },
  {
    "id": "bar_yohay",
    "name_he": "בר יוחאי",
    "name_en": "Bar Yohay",
    "lat": 32.997676,
    "lng": 35.448337,
    "region": "north",
    "type": "town"
  },
  {
    "id": "baram",
    "name_he": "ברעם",
    "name_en": "Bar'am",
    "lat": 33.057907,
    "lng": 35.434448,
    "region": "north",
    "type": "town"
  },
  {
    "id": "baraq",
    "name_he": "ברק",
    "name_en": "Baraq",
    "lat": 32.543068,
    "lng": 35.265069,
    "region": "north",
    "type": "town"
  },
  {
    "id": "judeide_maker",
    "name_he": "ג'דיידה-מכר",
    "name_en": "Judeide-Maker",
    "lat": 32.931809,
    "lng": 35.139409,
    "region": "north",
    "type": "town",
    "aliases": [
      "ג'דידה מכר"
    ]
  },
  {
    "id": "julis",
    "name_he": "ג'וליס",
    "name_en": "Julis",
    "lat": 32.94129,
    "lng": 35.180813,
    "region": "north",
    "type": "town"
  },
  {
    "id": "jish_gush_halav",
    "name_he": "ג'ש (גוש חלב)",
    "name_en": "Jish(gush Halav)",
    "lat": 33.022522,
    "lng": 35.447009,
    "region": "north",
    "type": "town",
    "aliases": [
      "ג'ש - גוש חלב"
    ]
  },
  {
    "id": "geva",
    "name_he": "גבע",
    "name_en": "Geva",
    "lat": 32.566431,
    "lng": 35.37316,
    "region": "north",
    "type": "town"
  },
  {
    "id": "givat_avni",
    "name_he": "גבעת אבני",
    "name_en": "Giv'at Avni",
    "lat": 32.774772,
    "lng": 35.438149,
    "region": "north",
    "type": "town"
  },
  {
    "id": "givat_ela",
    "name_he": "גבעת אלה",
    "name_en": "Giv'at Ela",
    "lat": 32.721464,
    "lng": 35.245157,
    "region": "north",
    "type": "town"
  },
  {
    "id": "givat_yoav",
    "name_he": "גבעת יואב",
    "name_en": "Giv'at Yo'av",
    "lat": 32.79855,
    "lng": 35.681543,
    "region": "north",
    "type": "town"
  },
  {
    "id": "givat_oz",
    "name_he": "גבעת עוז",
    "name_en": "Giv'at Oz",
    "lat": 32.55531,
    "lng": 35.198372,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gevat",
    "name_he": "גבת",
    "name_en": "Gevat",
    "lat": 32.675075,
    "lng": 35.212161,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gadot",
    "name_he": "גדות",
    "name_en": "Gadot",
    "lat": 33.017736,
    "lng": 35.619975,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gadish",
    "name_he": "גדיש",
    "name_en": "Gadish",
    "lat": 32.558878,
    "lng": 35.245194,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gidona",
    "name_he": "גדעונה",
    "name_en": "Gid'ona",
    "lat": 32.548786,
    "lng": 35.359397,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gonen",
    "name_he": "גונן",
    "name_en": "Gonen",
    "lat": 33.122785,
    "lng": 35.646214,
    "region": "north",
    "type": "town"
  },
  {
    "id": "goren",
    "name_he": "גורן",
    "name_en": "Goren",
    "lat": 33.05748,
    "lng": 35.235352,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gornot_hagalil",
    "name_he": "גורנות הגליל",
    "name_en": "Gornot Hagalil",
    "lat": 33.059921,
    "lng": 35.249604,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gazit",
    "name_he": "גזית",
    "name_en": "Gazit",
    "lat": 32.637816,
    "lng": 35.446851,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gilon",
    "name_he": "גילון",
    "name_en": "Gilon",
    "lat": 32.903737,
    "lng": 35.236031,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ginnosar",
    "name_he": "גינוסר",
    "name_en": "Ginnosar",
    "lat": 32.848119,
    "lng": 35.52373,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ginnegar",
    "name_he": "גיניגר",
    "name_en": "Ginnegar",
    "lat": 32.66379,
    "lng": 35.258359,
    "region": "north",
    "type": "town",
    "aliases": [
      "גניגר"
    ]
  },
  {
    "id": "gitta",
    "name_he": "גיתה",
    "name_en": "Gitta",
    "lat": 32.96718,
    "lng": 35.250324,
    "region": "north",
    "type": "town"
  },
  {
    "id": "even_yizhaq_galed",
    "name_he": "גלעד (אבן יצחק)",
    "name_en": "Even Yizhaq(gal'ed)",
    "lat": 32.556957,
    "lng": 35.076176,
    "region": "north",
    "type": "town",
    "aliases": [
      "גלעד"
    ]
  },
  {
    "id": "gan_ner",
    "name_he": "גן נר",
    "name_en": "Gan Ner",
    "lat": 32.527468,
    "lng": 35.334182,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gaton",
    "name_he": "געתון",
    "name_en": "Ga'ton",
    "lat": 33.006224,
    "lng": 35.214752,
    "region": "north",
    "type": "town"
  },
  {
    "id": "geshur",
    "name_he": "גשור",
    "name_en": "Geshur",
    "lat": 32.819543,
    "lng": 35.715659,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gesher",
    "name_he": "גשר",
    "name_en": "Gesher",
    "lat": 32.619624,
    "lng": 35.55144,
    "region": "north",
    "type": "town"
  },
  {
    "id": "gesher_haziw",
    "name_he": "גשר הזיו",
    "name_en": "Gesher Haziw",
    "lat": 33.040283,
    "lng": 35.11104,
    "region": "north",
    "type": "town"
  },
  {
    "id": "devora",
    "name_he": "דבורה",
    "name_en": "Devora",
    "lat": 32.552557,
    "lng": 35.264552,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dabburye",
    "name_he": "דבוריה",
    "name_en": "Dabburye",
    "lat": 32.69176,
    "lng": 35.372028,
    "region": "north",
    "type": "town"
  },
  {
    "id": "daverat",
    "name_he": "דברת",
    "name_en": "Daverat",
    "lat": 32.647415,
    "lng": 35.349798,
    "region": "north",
    "type": "town"
  },
  {
    "id": "deganya_alef",
    "name_he": "דגניה א'",
    "name_en": "Deganya Alef",
    "lat": 32.707653,
    "lng": 35.574847,
    "region": "north",
    "type": "town"
  },
  {
    "id": "deganya_bet",
    "name_he": "דגניה ב'",
    "name_en": "Deganya Bet",
    "lat": 32.70002,
    "lng": 35.575516,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dovev",
    "name_he": "דוב\"ב",
    "name_en": "Dovev",
    "lat": 33.053872,
    "lng": 35.40949,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dahi",
    "name_he": "דחי",
    "name_en": "Dahi",
    "lat": 32.621043,
    "lng": 35.345646,
    "region": "north",
    "type": "town"
  },
  {
    "id": "deir_al_asad",
    "name_he": "דייר אל-אסד",
    "name_en": "Deir Al-Asad",
    "lat": 32.937743,
    "lng": 35.261913,
    "region": "north",
    "type": "town"
  },
  {
    "id": "deir_hanna",
    "name_he": "דייר חנא",
    "name_en": "Deir Hanna",
    "lat": 32.861658,
    "lng": 35.368105,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dishon",
    "name_he": "דישון",
    "name_en": "Dishon",
    "lat": 33.082137,
    "lng": 35.518809,
    "region": "north",
    "type": "town"
  },
  {
    "id": "daliyya",
    "name_he": "דליה",
    "name_en": "Daliyya",
    "lat": 32.589841,
    "lng": 35.075053,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dalton",
    "name_he": "דלתון",
    "name_en": "Dalton",
    "lat": 33.015154,
    "lng": 35.492013,
    "region": "north",
    "type": "town"
  },
  {
    "id": "demeide",
    "name_he": "דמיידה",
    "name_en": "Demeide",
    "lat": 32.815585,
    "lng": 35.227209,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dan",
    "name_he": "דן",
    "name_en": "Dan",
    "lat": 33.240602,
    "lng": 35.65227,
    "region": "north",
    "type": "town"
  },
  {
    "id": "dafna",
    "name_he": "דפנה",
    "name_en": "Dafna",
    "lat": 33.230045,
    "lng": 35.638425,
    "region": "north",
    "type": "town"
  },
  {
    "id": "haon",
    "name_he": "האון",
    "name_en": "Haon",
    "lat": 32.725179,
    "lng": 35.62188,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hagosherim",
    "name_he": "הגושרים",
    "name_en": "Hagosherim",
    "lat": 33.22064,
    "lng": 35.624373,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hodayot",
    "name_he": "הודיות",
    "name_en": "Hodayot",
    "lat": 31.646218,
    "lng": 34.595988,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hoshaaya",
    "name_he": "הושעיה",
    "name_en": "Hosha'aya",
    "lat": 32.758116,
    "lng": 35.292298,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hazorea",
    "name_he": "הזורע",
    "name_en": "Hazorea",
    "lat": 32.645166,
    "lng": 35.120003,
    "region": "north",
    "type": "town",
    "aliases": [
      "יקנעם המושבה והזורע"
    ]
  },
  {
    "id": "hazoreim",
    "name_he": "הזורעים",
    "name_en": "Hazore'im",
    "lat": 32.746598,
    "lng": 35.501833,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hayogev",
    "name_he": "היוגב",
    "name_en": "Hayogev",
    "lat": 32.611806,
    "lng": 35.204236,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hilla",
    "name_he": "הילה",
    "name_en": "Hilla",
    "lat": 33.036276,
    "lng": 35.244256,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hasolelim",
    "name_he": "הסוללים",
    "name_en": "Hasolelim",
    "lat": 32.750961,
    "lng": 35.237972,
    "region": "north",
    "type": "town"
  },
  {
    "id": "harduf",
    "name_he": "הרדוף",
    "name_en": "Harduf",
    "lat": 32.76393,
    "lng": 35.174049,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hararit",
    "name_he": "הררית",
    "name_en": "Hararit",
    "lat": 32.845371,
    "lng": 35.366111,
    "region": "north",
    "type": "town"
  },
  {
    "id": "zarzir",
    "name_he": "זרזיר",
    "name_en": "Zarzir",
    "lat": 32.717271,
    "lng": 35.223656,
    "region": "north",
    "type": "town"
  },
  {
    "id": "khawaled_986",
    "name_he": "ח'ואלד (שבט)",
    "name_en": "Khawaled",
    "lat": 32.759014,
    "lng": 35.158282,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hever",
    "name_he": "חבר",
    "name_en": "Hever",
    "lat": 32.54767,
    "lng": 35.264284,
    "region": "north",
    "type": "town",
    "aliases": [
      "מרכז חבר"
    ]
  },
  {
    "id": "had_nes",
    "name_he": "חד-נס",
    "name_en": "Had-Nes",
    "lat": 32.934109,
    "lng": 35.637116,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hujeirat_dahra",
    "name_he": "חוג'ייראת (ד'הרה)",
    "name_en": "Hujeirat (dahra)",
    "lat": 32.835021,
    "lng": 35.288982,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hulata",
    "name_he": "חולתה",
    "name_en": "Hulata",
    "lat": 33.051598,
    "lng": 35.609933,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hosen",
    "name_he": "חוסן",
    "name_en": "Hosen",
    "lat": 32.997997,
    "lng": 35.299197,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hussniyya",
    "name_he": "חוסנייה",
    "name_en": "Hussniyya",
    "lat": 32.901484,
    "lng": 35.316989,
    "region": "north",
    "type": "town"
  },
  {
    "id": "huqoq",
    "name_he": "חוקוק",
    "name_en": "Huqoq",
    "lat": 32.880039,
    "lng": 35.495454,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hurfeish",
    "name_he": "חורפיש",
    "name_en": "Hurfeish",
    "lat": 33.017612,
    "lng": 35.347145,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hazon",
    "name_he": "חזון",
    "name_en": "Hazon",
    "lat": 32.90487,
    "lng": 35.396976,
    "region": "north",
    "type": "town"
  },
  {
    "id": "haluz",
    "name_he": "חלוץ",
    "name_en": "Haluz",
    "lat": 32.950298,
    "lng": 35.311888,
    "region": "north",
    "type": "town",
    "aliases": [
      "הר חלוץ"
    ]
  },
  {
    "id": "hamam",
    "name_he": "חמאם",
    "name_en": "Hamam",
    "lat": 32.829785,
    "lng": 35.489819,
    "region": "north",
    "type": "town",
    "aliases": [
      "ואדי אל חמאם"
    ]
  },
  {
    "id": "hamadya",
    "name_he": "חמדיה",
    "name_en": "Hamadya",
    "lat": 32.519863,
    "lng": 35.520528,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hanita",
    "name_he": "חניתה",
    "name_en": "Hanita",
    "lat": 33.088099,
    "lng": 35.174049,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hannaton",
    "name_he": "חנתון",
    "name_en": "Hannaton",
    "lat": 32.784496,
    "lng": 35.243945,
    "region": "north",
    "type": "town"
  },
  {
    "id": "haspin",
    "name_he": "חספין",
    "name_en": "Haspin",
    "lat": 32.845467,
    "lng": 35.79348,
    "region": "north",
    "type": "town"
  },
  {
    "id": "hefzi_bah",
    "name_he": "חפצי-בה",
    "name_en": "Hefzi-Bah",
    "lat": 32.519441,
    "lng": 35.424546,
    "region": "north",
    "type": "town",
    "aliases": [
      "בית אלפא וחפציבה"
    ]
  },
  {
    "id": "hatzor_haglilit",
    "name_he": "חצור הגלילית",
    "name_en": "Hatzor HaGlilit",
    "lat": 32.987,
    "lng": 35.5393,
    "region": "north",
    "type": "local_council"
  },
  {
    "id": "harashim",
    "name_he": "חרשים",
    "name_en": "Harashim",
    "lat": 32.95683,
    "lng": 35.328155,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tiberias",
    "name_he": "טבריה",
    "name_en": "Tiberias",
    "lat": 32.7922,
    "lng": 35.5312,
    "region": "north",
    "type": "city"
  },
  {
    "id": "tuba_zangariyye",
    "name_he": "טובא-זנגריה",
    "name_en": "Tuba-Zangariyye",
    "lat": 32.967408,
    "lng": 35.594828,
    "region": "north",
    "type": "town"
  },
  {
    "id": "turan",
    "name_he": "טורעאן",
    "name_en": "Tur'an",
    "lat": 32.776843,
    "lng": 35.37489,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tayibe_baemeq",
    "name_he": "טייבה (בעמק)",
    "name_en": "Tayibe(baemeq)",
    "lat": 32.604163,
    "lng": 35.445119,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tirat_zevi",
    "name_he": "טירת צבי",
    "name_en": "Tirat Zevi",
    "lat": 32.421341,
    "lng": 35.527826,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tal_el",
    "name_he": "טל-אל",
    "name_en": "Tal-El",
    "lat": 32.926539,
    "lng": 35.178859,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tamra",
    "name_he": "טמרה",
    "name_en": "Tamra",
    "lat": 32.853959,
    "lng": 35.190739,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tamra_yizreel",
    "name_he": "טמרה (יזרעאל)",
    "name_en": "Tamra (yizre'el)",
    "lat": 32.634363,
    "lng": 35.40382,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tefahot",
    "name_he": "טפחות",
    "name_en": "Tefahot",
    "lat": 32.867356,
    "lng": 35.422849,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yanuh_jat",
    "name_he": "יאנוח-ג'ת",
    "name_en": "Yanuh-Jat",
    "lat": 32.985199,
    "lng": 35.244312,
    "region": "north",
    "type": "town",
    "aliases": [
      "ינוח ג'ת"
    ]
  },
  {
    "id": "yavneel",
    "name_he": "יבנאל",
    "name_en": "Yavneel",
    "lat": 32.7163,
    "lng": 35.4978,
    "region": "north",
    "type": "local_council"
  },
  {
    "id": "yuval",
    "name_he": "יובל",
    "name_en": "Yuval",
    "lat": 33.244805,
    "lng": 35.597689,
    "region": "north",
    "type": "town",
    "aliases": [
      "כפר יובל"
    ]
  },
  {
    "id": "yuvalim",
    "name_he": "יובלים",
    "name_en": "Yuvalim",
    "lat": 32.878134,
    "lng": 35.27049,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yodefat",
    "name_he": "יודפת",
    "name_en": "Yodefat",
    "lat": 32.836761,
    "lng": 35.272334,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yonatan",
    "name_he": "יונתן",
    "name_en": "Yonatan",
    "lat": 32.93659,
    "lng": 35.793801,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yizreel",
    "name_he": "יזרעאל",
    "name_en": "Yizre'el",
    "lat": 32.561643,
    "lng": 35.321506,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yehiam",
    "name_he": "יחיעם",
    "name_en": "Yehi'am",
    "lat": 32.997394,
    "lng": 35.219647,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yesud_hamaala",
    "name_he": "יסוד המעלה",
    "name_en": "Yesud Hama'ala",
    "lat": 33.055683,
    "lng": 35.600747,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yasur",
    "name_he": "יסעור",
    "name_en": "Yas'ur",
    "lat": 32.900741,
    "lng": 35.166232,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yaad",
    "name_he": "יעד",
    "name_en": "Ya'ad",
    "lat": 32.878102,
    "lng": 35.243713,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yael",
    "name_he": "יעל",
    "name_en": "Ya'el",
    "lat": 32.552252,
    "lng": 35.308006,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yaara",
    "name_he": "יערה",
    "name_en": "Ya'ara",
    "lat": 33.067661,
    "lng": 35.185777,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yafi",
    "name_he": "יפיע",
    "name_en": "Yafi",
    "lat": 32.683772,
    "lng": 35.274703,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yifat",
    "name_he": "יפעת",
    "name_en": "Yif'at",
    "lat": 32.677756,
    "lng": 35.224733,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yiftah",
    "name_he": "יפתח",
    "name_en": "Yiftah",
    "lat": 33.12739,
    "lng": 35.551803,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yoqneam_moshava",
    "name_he": "יקנעם (מושבה)",
    "name_en": "Yoqne'am(moshava)",
    "lat": 32.654638,
    "lng": 35.114683,
    "region": "north",
    "type": "moshav"
  },
  {
    "id": "yoqneam_illit",
    "name_he": "יקנעם עילית",
    "name_en": "Yoqne'am Illit",
    "lat": 32.656631,
    "lng": 35.104214,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yiron",
    "name_he": "יראון",
    "name_en": "Yir'on",
    "lat": 33.076943,
    "lng": 35.454159,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yardena",
    "name_he": "ירדנה",
    "name_en": "Yardena",
    "lat": 32.564735,
    "lng": 35.564497,
    "region": "north",
    "type": "town"
  },
  {
    "id": "yirka",
    "name_he": "ירכא",
    "name_en": "Yirka",
    "lat": 32.954045,
    "lng": 35.20112,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kabul",
    "name_he": "כאבול",
    "name_en": "Kabul",
    "lat": 32.871933,
    "lng": 35.207148,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kaokab_abu_al_hija",
    "name_he": "כאוכב אבו אל-היג'א",
    "name_en": "Kaokab Abu Al-Hija",
    "lat": 32.830742,
    "lng": 35.248356,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kabri",
    "name_he": "כברי",
    "name_en": "Kabri",
    "lat": 33.02127,
    "lng": 35.149005,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kadoorie",
    "name_he": "כדורי",
    "name_en": "Kadoorie",
    "lat": 32.702634,
    "lng": 35.406708,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kaddita",
    "name_he": "כדיתה",
    "name_en": "Kaddita",
    "lat": 33.005979,
    "lng": 35.463777,
    "region": "north",
    "type": "town"
  },
  {
    "id": "korazim",
    "name_he": "כורזים",
    "name_en": "Korazim",
    "lat": 32.909268,
    "lng": 35.551189,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kahal",
    "name_he": "כחל",
    "name_en": "Kahal",
    "lat": 32.892026,
    "lng": 35.510048,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kishor",
    "name_he": "כישור",
    "name_en": "Kishor",
    "lat": 32.945574,
    "lng": 35.249611,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kelil",
    "name_he": "כליל",
    "name_en": "Kelil",
    "lat": 32.980559,
    "lng": 35.199556,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kallanit",
    "name_he": "כלנית",
    "name_en": "Kallanit",
    "lat": 32.87459,
    "lng": 35.454211,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kammana",
    "name_he": "כמאנה",
    "name_en": "Kammana",
    "lat": 32.90853,
    "lng": 35.342021,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kammon",
    "name_he": "כמון",
    "name_en": "Kammon",
    "lat": 32.908463,
    "lng": 35.359037,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kanaf",
    "name_he": "כנף",
    "name_en": "Kanaf",
    "lat": 32.871667,
    "lng": 35.701252,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kinneret_moshava",
    "name_he": "כנרת (מושבה)",
    "name_en": "Kinneret(moshava)",
    "lat": 32.722267,
    "lng": 35.563941,
    "region": "north",
    "type": "moshav"
  },
  {
    "id": "kinneret_qevuza",
    "name_he": "כנרת (קבוצה)",
    "name_en": "Kinneret(qevuza)",
    "lat": 32.713473,
    "lng": 35.565677,
    "region": "north",
    "type": "town",
    "aliases": [
      "כינרת קבוצה"
    ]
  },
  {
    "id": "kisra_sumei",
    "name_he": "כסרא-סמיע",
    "name_en": "Kisra-Sumei",
    "lat": 32.964238,
    "lng": 35.302544,
    "region": "north",
    "type": "town",
    "aliases": [
      "כיסרא סמיע"
    ]
  },
  {
    "id": "kaabiyye_tabbash_ha",
    "name_he": "כעביה-טבאש-חג'אג'רה",
    "name_en": "Ka'abiyye-Tabbash-Ha",
    "lat": 32.742447,
    "lng": 35.203823,
    "region": "north",
    "type": "town",
    "aliases": [
      "כעביה טבאש"
    ]
  },
  {
    "id": "kefar_blum",
    "name_he": "כפר בלום",
    "name_en": "Kefar Blum",
    "lat": 33.1732,
    "lng": 35.609065,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_barukh",
    "name_he": "כפר ברוך",
    "name_en": "Kefar Barukh",
    "lat": 32.646478,
    "lng": 35.190674,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_gidon",
    "name_he": "כפר גדעון",
    "name_en": "Kefar Gid'on",
    "lat": 32.644008,
    "lng": 35.291217,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_giladi",
    "name_he": "כפר גלעדי",
    "name_en": "Kefar Gil'adi",
    "lat": 33.242962,
    "lng": 35.575668,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_hahoresh",
    "name_he": "כפר החורש",
    "name_en": "Kefar Hahoresh",
    "lat": 32.70021,
    "lng": 35.273372,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_hanasi",
    "name_he": "כפר הנשיא",
    "name_en": "Kefar Hanasi",
    "lat": 32.975436,
    "lng": 35.602006,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_weradim",
    "name_he": "כפר ורדים",
    "name_en": "Kefar Weradim",
    "lat": 32.995799,
    "lng": 35.267543,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_zetim",
    "name_he": "כפר זיתים",
    "name_en": "Kefar Zetim",
    "lat": 32.811509,
    "lng": 35.463841,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_hoshen",
    "name_he": "כפר חושן",
    "name_en": "Kefar Hoshen",
    "lat": 33.010729,
    "lng": 35.438197,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_hittim",
    "name_he": "כפר חיטים",
    "name_en": "Kefar Hittim",
    "lat": 32.800955,
    "lng": 35.503211,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_hananya",
    "name_he": "כפר חנניה",
    "name_en": "Kefar Hananya",
    "lat": 32.917015,
    "lng": 35.420854,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_haruv",
    "name_he": "כפר חרוב",
    "name_en": "Kefar Haruv",
    "lat": 32.762012,
    "lng": 35.663035,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kafar_yasif",
    "name_he": "כפר יאסיף",
    "name_en": "Kafar Yasif",
    "lat": 32.953413,
    "lng": 35.162429,
    "region": "north",
    "type": "town",
    "aliases": [
      "כפר יסיף"
    ]
  },
  {
    "id": "kefar_yehoshua",
    "name_he": "כפר יהושע",
    "name_en": "Kefar Yehoshua",
    "lat": 32.68326,
    "lng": 35.152048,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_yehezqel",
    "name_he": "כפר יחזקאל",
    "name_en": "Kefar Yehezqel",
    "lat": 32.566612,
    "lng": 35.358645,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kafar_kama",
    "name_he": "כפר כמא",
    "name_en": "Kafar Kama",
    "lat": 32.721551,
    "lng": 35.439994,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kafar_kanna",
    "name_he": "כפר כנא",
    "name_en": "Kafar Kanna",
    "lat": 32.747667,
    "lng": 35.341909,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kafar_manda",
    "name_he": "כפר מנדא",
    "name_en": "Kafar Manda",
    "lat": 32.808574,
    "lng": 35.263535,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_masaryk",
    "name_he": "כפר מסריק",
    "name_en": "Kefar Masaryk",
    "lat": 32.889966,
    "lng": 35.099285,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kafar_misr",
    "name_he": "כפר מצר",
    "name_en": "Kafar Misr",
    "lat": 32.645522,
    "lng": 35.422481,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_szold",
    "name_he": "כפר סאלד",
    "name_en": "Kefar Szold",
    "lat": 33.19475,
    "lng": 35.657445,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_kish",
    "name_he": "כפר קיש",
    "name_en": "Kefar Kish",
    "lat": 32.667044,
    "lng": 35.449154,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_rosh_haniqra",
    "name_he": "כפר ראש הנקרה",
    "name_en": "Kefar Rosh Haniqra",
    "lat": 33.086061,
    "lng": 35.114799,
    "region": "north",
    "type": "town",
    "aliases": [
      "ראש הנקרה"
    ]
  },
  {
    "id": "kefar_rozenwald_zar",
    "name_he": "כפר רוזנואלד (זרעית)",
    "name_en": "Kefar Rozenwald(zar.",
    "lat": 33.098935,
    "lng": 35.287931,
    "region": "north",
    "type": "town",
    "aliases": [
      "זרעית"
    ]
  },
  {
    "id": "kefar_ruppin",
    "name_he": "כפר רופין",
    "name_en": "Kefar Ruppin",
    "lat": 32.457608,
    "lng": 35.556633,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_shammay",
    "name_he": "כפר שמאי",
    "name_en": "Kefar Shammay",
    "lat": 32.956487,
    "lng": 35.458041,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kefar_tavor",
    "name_he": "כפר תבור",
    "name_en": "Kefar Tavor",
    "lat": 32.688745,
    "lng": 35.420728,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kare_deshe",
    "name_he": "כרי דשא",
    "name_en": "Kare Deshe",
    "lat": 32.929356,
    "lng": 35.577038,
    "region": "north",
    "type": "town"
  },
  {
    "id": "karkom",
    "name_he": "כרכום",
    "name_en": "Karkom",
    "lat": 32.930056,
    "lng": 35.608027,
    "region": "north",
    "type": "town"
  },
  {
    "id": "kerem_ben_zimra",
    "name_he": "כרם בן זמרה",
    "name_en": "Kerem Ben Zimra",
    "lat": 33.036641,
    "lng": 35.468486,
    "region": "north",
    "type": "town"
  },
  {
    "id": "karmiel",
    "name_he": "כרמיאל",
    "name_en": "Karmiel",
    "lat": 32.9186,
    "lng": 35.2961,
    "region": "north",
    "type": "city"
  },
  {
    "id": "lavon",
    "name_he": "לבון",
    "name_en": "Lavon",
    "lat": 32.942498,
    "lng": 35.286841,
    "region": "north",
    "type": "town"
  },
  {
    "id": "lavi",
    "name_he": "לביא",
    "name_en": "Lavi",
    "lat": 32.788882,
    "lng": 35.442842,
    "region": "north",
    "type": "town"
  },
  {
    "id": "livnim",
    "name_he": "לבנים",
    "name_en": "Livnim",
    "lat": 32.864085,
    "lng": 35.495594,
    "region": "north",
    "type": "town"
  },
  {
    "id": "lahavot_habashan",
    "name_he": "להבות הבשן",
    "name_en": "Lahavot Habashan",
    "lat": 33.140467,
    "lng": 35.647986,
    "region": "north",
    "type": "town"
  },
  {
    "id": "lohame_hagetaot",
    "name_he": "לוחמי הגיטאות",
    "name_en": "Lohame Hageta'ot",
    "lat": 32.962257,
    "lng": 35.098253,
    "region": "north",
    "type": "town",
    "aliases": [
      "לוחמי הגטאות"
    ]
  },
  {
    "id": "lotem",
    "name_he": "לוטם",
    "name_en": "Lotem",
    "lat": 32.882565,
    "lng": 35.357142,
    "region": "north",
    "type": "town"
  },
  {
    "id": "liman",
    "name_he": "לימן",
    "name_en": "Liman",
    "lat": 33.059779,
    "lng": 35.111498,
    "region": "north",
    "type": "town"
  },
  {
    "id": "lappidot",
    "name_he": "לפידות",
    "name_en": "Lappidot",
    "lat": 32.960978,
    "lng": 35.265652,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mevo_hamma",
    "name_he": "מבוא חמה",
    "name_en": "Mevo Hamma",
    "lat": 32.737735,
    "lng": 35.655691,
    "region": "north",
    "type": "town"
  },
  {
    "id": "majd_al_kurum",
    "name_he": "מג'ד אל-כרום",
    "name_en": "Majd Al-Kurum",
    "lat": 32.920685,
    "lng": 35.255832,
    "region": "north",
    "type": "town"
  },
  {
    "id": "majdal_shams",
    "name_he": "מג'דל שמס",
    "name_en": "Majdal Shams",
    "lat": 33.266313,
    "lng": 35.768388,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mughar",
    "name_he": "מגאר",
    "name_en": "Mughar",
    "lat": 32.886375,
    "lng": 35.412888,
    "region": "north",
    "type": "town"
  },
  {
    "id": "migdal",
    "name_he": "מגדל",
    "name_en": "Migdal",
    "lat": 32.832478,
    "lng": 35.512955,
    "region": "north",
    "type": "town"
  },
  {
    "id": "migdal_haemek",
    "name_he": "מגדל העמק",
    "name_en": "Migdal HaEmek",
    "lat": 32.6713,
    "lng": 35.2401,
    "region": "north",
    "type": "city"
  },
  {
    "id": "megiddo",
    "name_he": "מגידו",
    "name_en": "Megiddo",
    "lat": 32.579658,
    "lng": 35.181666,
    "region": "north",
    "type": "town"
  },
  {
    "id": "magen_shaul",
    "name_he": "מגן שאול",
    "name_en": "Magen Sha'ul",
    "lat": 32.519594,
    "lng": 35.308088,
    "region": "north",
    "type": "town"
  },
  {
    "id": "midrakh_oz",
    "name_he": "מדרך עוז",
    "name_en": "Midrakh Oz",
    "lat": 32.595081,
    "lng": 35.159105,
    "region": "north",
    "type": "town"
  },
  {
    "id": "moledet",
    "name_he": "מולדת",
    "name_en": "Moledet",
    "lat": 32.585556,
    "lng": 35.441817,
    "region": "north",
    "type": "town"
  },
  {
    "id": "muqeible",
    "name_he": "מוקייבלה",
    "name_en": "Muqeible",
    "lat": 32.513707,
    "lng": 35.29732,
    "region": "north",
    "type": "town",
    "aliases": [
      "מוקיבלה"
    ]
  },
  {
    "id": "moran",
    "name_he": "מורן",
    "name_en": "Moran",
    "lat": 32.922039,
    "lng": 35.392526,
    "region": "north",
    "type": "town"
  },
  {
    "id": "moreshet",
    "name_he": "מורשת",
    "name_en": "Moreshet",
    "lat": 32.826856,
    "lng": 35.23381,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mizra",
    "name_he": "מזרע",
    "name_en": "Mizra",
    "lat": 32.650949,
    "lng": 35.287126,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mazraa",
    "name_he": "מזרעה",
    "name_en": "Mazra'a",
    "lat": 32.984243,
    "lng": 35.098163,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mahanayim",
    "name_he": "מחניים",
    "name_en": "Mahanayim",
    "lat": 32.989338,
    "lng": 35.571501,
    "region": "north",
    "type": "town"
  },
  {
    "id": "metula",
    "name_he": "מטולה",
    "name_en": "Metula",
    "lat": 33.279,
    "lng": 35.5773,
    "region": "north",
    "type": "local_council"
  },
  {
    "id": "metav",
    "name_he": "מיטב",
    "name_en": "Metav",
    "lat": 32.545621,
    "lng": 35.300425,
    "region": "north",
    "type": "town"
  },
  {
    "id": "metal",
    "name_he": "מיטל",
    "name_en": "Metal",
    "lat": 32.438171,
    "lng": 35.412956,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mezar",
    "name_he": "מיצר",
    "name_en": "Mezar",
    "lat": 32.768676,
    "lng": 35.737072,
    "region": "north",
    "type": "town"
  },
  {
    "id": "merav",
    "name_he": "מירב",
    "name_en": "Merav",
    "lat": 32.452839,
    "lng": 35.421813,
    "region": "north",
    "type": "town"
  },
  {
    "id": "meron",
    "name_he": "מירון",
    "name_en": "Meron",
    "lat": 32.987122,
    "lng": 35.439442,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mikhmannim",
    "name_he": "מכמנים",
    "name_en": "Mikhmannim",
    "lat": 32.906423,
    "lng": 35.329868,
    "region": "north",
    "type": "town"
  },
  {
    "id": "melea",
    "name_he": "מלאה",
    "name_en": "Mele'a",
    "lat": 32.563861,
    "lng": 35.237182,
    "region": "north",
    "type": "town"
  },
  {
    "id": "malkiyya",
    "name_he": "מלכיה",
    "name_en": "Malkiyya",
    "lat": 33.098283,
    "lng": 35.511169,
    "region": "north",
    "type": "town"
  },
  {
    "id": "manof",
    "name_he": "מנוף",
    "name_en": "Manof",
    "lat": 32.85278,
    "lng": 35.237849,
    "region": "north",
    "type": "town"
  },
  {
    "id": "manot",
    "name_he": "מנות",
    "name_en": "Manot",
    "lat": 33.038293,
    "lng": 35.196535,
    "region": "north",
    "type": "town"
  },
  {
    "id": "menahemya",
    "name_he": "מנחמיה",
    "name_en": "Menahemya",
    "lat": 32.666543,
    "lng": 35.555594,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mennara",
    "name_he": "מנרה",
    "name_en": "Mennara",
    "lat": 33.196318,
    "lng": 35.54435,
    "region": "north",
    "type": "town"
  },
  {
    "id": "manshiyyet_zabda",
    "name_he": "מנשית זבדה",
    "name_en": "Manshiyyet Zabda",
    "lat": 32.705646,
    "lng": 35.192218,
    "region": "north",
    "type": "town"
  },
  {
    "id": "massad",
    "name_he": "מסד",
    "name_en": "Massad",
    "lat": 32.843516,
    "lng": 35.423415,
    "region": "north",
    "type": "town"
  },
  {
    "id": "massada",
    "name_he": "מסדה",
    "name_en": "Massada",
    "lat": 32.682868,
    "lng": 35.598533,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mesillot",
    "name_he": "מסילות",
    "name_en": "Mesillot",
    "lat": 32.495245,
    "lng": 35.47442,
    "region": "north",
    "type": "town"
  },
  {
    "id": "masade",
    "name_he": "מסעדה",
    "name_en": "Mas'ade",
    "lat": 33.231683,
    "lng": 35.75581,
    "region": "north",
    "type": "town"
  },
  {
    "id": "maagan",
    "name_he": "מעגן",
    "name_en": "Ma'agan",
    "lat": 32.706361,
    "lng": 35.600542,
    "region": "north",
    "type": "town"
  },
  {
    "id": "maoz_hayyim",
    "name_he": "מעוז חיים",
    "name_en": "Ma'oz Hayyim",
    "lat": 32.493103,
    "lng": 35.551155,
    "region": "north",
    "type": "town"
  },
  {
    "id": "meona",
    "name_he": "מעונה",
    "name_en": "Me'ona",
    "lat": 33.016568,
    "lng": 35.260108,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mielya",
    "name_he": "מעיליא",
    "name_en": "Mi'elya",
    "lat": 33.027105,
    "lng": 35.257198,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mayan_barukh",
    "name_he": "מעין ברוך",
    "name_en": "Ma'yan Barukh",
    "lat": 33.240013,
    "lng": 35.607242,
    "region": "north",
    "type": "town",
    "aliases": [
      "מעיין ברוך"
    ]
  },
  {
    "id": "maale_gilboa",
    "name_he": "מעלה גלבוע",
    "name_en": "Ma'ale Gilboa",
    "lat": 32.476697,
    "lng": 35.419067,
    "region": "north",
    "type": "town"
  },
  {
    "id": "maale_gamla",
    "name_he": "מעלה גמלא",
    "name_en": "Ma'ale Gamla",
    "lat": 32.888163,
    "lng": 35.684272,
    "region": "north",
    "type": "town"
  },
  {
    "id": "maalot_tarshiha",
    "name_he": "מעלות-תרשיחא",
    "name_en": "Ma'alot-Tarshiha",
    "lat": 33.017,
    "lng": 35.2726,
    "region": "north",
    "type": "city"
  },
  {
    "id": "mazzuva",
    "name_he": "מצובה",
    "name_en": "Mazzuva",
    "lat": 33.062554,
    "lng": 35.15753,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mizpa",
    "name_he": "מצפה",
    "name_en": "Mizpa",
    "lat": 32.790291,
    "lng": 35.509327,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mizpe_aviv",
    "name_he": "מצפה אבי\"ב",
    "name_en": "Mizpe Aviv",
    "lat": 32.839038,
    "lng": 35.19816,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mizpe_netofa",
    "name_he": "מצפה נטופה",
    "name_en": "Mizpe Netofa",
    "lat": 32.803577,
    "lng": 35.386542,
    "region": "north",
    "type": "town"
  },
  {
    "id": "margaliyyot",
    "name_he": "מרגליות",
    "name_en": "Margaliyyot",
    "lat": 33.214559,
    "lng": 35.545037,
    "region": "north",
    "type": "town"
  },
  {
    "id": "merom_golan",
    "name_he": "מרום גולן",
    "name_en": "Merom Golan",
    "lat": 33.132905,
    "lng": 35.776208,
    "region": "north",
    "type": "town"
  },
  {
    "id": "merhavya_moshav",
    "name_he": "מרחביה (מושב)",
    "name_en": "Merhavya(moshav)",
    "lat": 32.603931,
    "lng": 35.31655,
    "region": "north",
    "type": "moshav"
  },
  {
    "id": "merhavya_qibbuz",
    "name_he": "מרחביה (קיבוץ)",
    "name_en": "Merhavya(qibbuz)",
    "lat": 32.606103,
    "lng": 35.307883,
    "region": "north",
    "type": "kibbutz"
  },
  {
    "id": "misgav_am",
    "name_he": "משגב עם",
    "name_en": "Misgav Am",
    "lat": 33.247413,
    "lng": 35.548938,
    "region": "north",
    "type": "town"
  },
  {
    "id": "meshhed",
    "name_he": "משהד",
    "name_en": "Meshhed",
    "lat": 32.74023,
    "lng": 35.324259,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mishmar_hayarden",
    "name_he": "משמר הירדן",
    "name_en": "Mishmar Hayarden",
    "lat": 33.004884,
    "lng": 35.599883,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mishmar_haemeq",
    "name_he": "משמר העמק",
    "name_en": "Mishmar Haemeq",
    "lat": 32.609016,
    "lng": 35.143594,
    "region": "north",
    "type": "town"
  },
  {
    "id": "mattat",
    "name_he": "מתת",
    "name_en": "Mattat",
    "lat": 33.040785,
    "lng": 35.357704,
    "region": "north",
    "type": "town"
  },
  {
    "id": "neot_golan",
    "name_he": "נאות גולן",
    "name_en": "Ne'ot Golan",
    "lat": 32.786407,
    "lng": 35.692214,
    "region": "north",
    "type": "town"
  },
  {
    "id": "neot_mordekhay",
    "name_he": "נאות מרדכי",
    "name_en": "Ne'ot Mordekhay",
    "lat": 33.159839,
    "lng": 35.596843,
    "region": "north",
    "type": "town"
  },
  {
    "id": "naura",
    "name_he": "נאעורה",
    "name_en": "Na'ura",
    "lat": 32.613726,
    "lng": 35.391706,
    "region": "north",
    "type": "town",
    "aliases": [
      "נעורה"
    ]
  },
  {
    "id": "nahalal",
    "name_he": "נהלל",
    "name_en": "Nahalal",
    "lat": 32.69029,
    "lng": 35.194123,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nahariya",
    "name_he": "נהריה",
    "name_en": "Nahariya",
    "lat": 33.006,
    "lng": 35.0953,
    "region": "north",
    "type": "city"
  },
  {
    "id": "nov",
    "name_he": "נוב",
    "name_en": "Nov",
    "lat": 32.832535,
    "lng": 35.78327,
    "region": "north",
    "type": "town"
  },
  {
    "id": "newe_ur",
    "name_he": "נווה אור",
    "name_en": "Newe Ur",
    "lat": 32.588391,
    "lng": 35.553176,
    "region": "north",
    "type": "town"
  },
  {
    "id": "newe_ativ",
    "name_he": "נווה אטי\"ב",
    "name_en": "Newe Ativ",
    "lat": 33.262002,
    "lng": 35.741943,
    "region": "north",
    "type": "town"
  },
  {
    "id": "newe_etan",
    "name_he": "נווה איתן",
    "name_en": "Newe Etan",
    "lat": 32.491922,
    "lng": 35.532655,
    "region": "north",
    "type": "town"
  },
  {
    "id": "newe_ziv",
    "name_he": "נווה זיו",
    "name_en": "Newe Ziv",
    "lat": 33.027541,
    "lng": 35.181601,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nazareth_illit",
    "name_he": "נוף הגליל",
    "name_en": "Nof HaGalil",
    "lat": 32.7262,
    "lng": 35.329,
    "region": "north",
    "type": "city"
  },
  {
    "id": "nurit",
    "name_he": "נורית",
    "name_en": "Nurit",
    "lat": 32.541606,
    "lng": 35.356465,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nahef",
    "name_he": "נחף",
    "name_en": "Nahef",
    "lat": 32.935281,
    "lng": 35.319794,
    "region": "north",
    "type": "town"
  },
  {
    "id": "netua",
    "name_he": "נטועה",
    "name_en": "Netu'a",
    "lat": 33.064586,
    "lng": 35.32299,
    "region": "north",
    "type": "town"
  },
  {
    "id": "natur",
    "name_he": "נטור",
    "name_en": "Natur",
    "lat": 32.854209,
    "lng": 35.751372,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nein",
    "name_he": "ניין",
    "name_en": "Nein",
    "lat": 32.630909,
    "lng": 35.348754,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nir_dawid_tel_amal",
    "name_he": "ניר דוד (תל עמל)",
    "name_en": "Nir Dawid (tel Amal)",
    "lat": 32.503639,
    "lng": 35.458157,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nir_yafe",
    "name_he": "ניר יפה",
    "name_en": "Nir Yafe",
    "lat": 32.570284,
    "lng": 35.24606,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nes_ammim",
    "name_he": "נס עמים",
    "name_en": "Nes Ammim",
    "lat": 32.965985,
    "lng": 35.12109,
    "region": "north",
    "type": "town"
  },
  {
    "id": "nazareth",
    "name_he": "נצרת",
    "name_en": "Nazareth",
    "lat": 32.6996,
    "lng": 35.3035,
    "region": "north",
    "type": "city"
  },
  {
    "id": "netiv_hashayyara",
    "name_he": "נתיב השיירה",
    "name_en": "Netiv Hashayyara",
    "lat": 32.993935,
    "lng": 35.136058,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sajur",
    "name_he": "סאג'ור",
    "name_en": "Sajur",
    "lat": 32.941283,
    "lng": 35.344697,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sasa",
    "name_he": "סאסא",
    "name_en": "Sasa",
    "lat": 33.026731,
    "lng": 35.395749,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sawaid_humayra",
    "name_he": "סואעד (חמרייה)",
    "name_en": "Sawa'id (humayra)",
    "lat": 32.767499,
    "lng": 35.167892,
    "region": "north",
    "type": "town",
    "aliases": [
      "סואעד חמירה"
    ]
  },
  {
    "id": "sulam",
    "name_he": "סולם",
    "name_en": "Sulam",
    "lat": 32.606307,
    "lng": 35.334536,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sakhnin",
    "name_he": "סח'נין",
    "name_en": "Sakhnin",
    "lat": 32.865238,
    "lng": 35.300845,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sallama",
    "name_he": "סלמה",
    "name_en": "Sallama",
    "lat": 32.8962,
    "lng": 35.359544,
    "region": "north",
    "type": "town"
  },
  {
    "id": "saar",
    "name_he": "סער",
    "name_en": "Sa'ar",
    "lat": 33.02902,
    "lng": 35.109323,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ghajar",
    "name_he": "ע'ג'ר",
    "name_en": "Ghajar",
    "lat": 33.270524,
    "lng": 35.623093,
    "region": "north",
    "type": "town"
  },
  {
    "id": "avdon",
    "name_he": "עבדון",
    "name_en": "Avdon",
    "lat": 33.049366,
    "lng": 35.182209,
    "region": "north",
    "type": "town"
  },
  {
    "id": "evron",
    "name_he": "עברון",
    "name_en": "Evron",
    "lat": 32.991905,
    "lng": 35.100688,
    "region": "north",
    "type": "town"
  },
  {
    "id": "adi",
    "name_he": "עדי",
    "name_en": "Adi",
    "lat": 32.782848,
    "lng": 35.173704,
    "region": "north",
    "type": "town"
  },
  {
    "id": "uzeir",
    "name_he": "עוזייר",
    "name_en": "Uzeir",
    "lat": 32.790298,
    "lng": 35.324852,
    "region": "north",
    "type": "town"
  },
  {
    "id": "eilabun",
    "name_he": "עיילבון",
    "name_en": "Eilabun",
    "lat": 32.835271,
    "lng": 35.402912,
    "region": "north",
    "type": "town",
    "aliases": [
      "עילבון"
    ]
  },
  {
    "id": "ilut",
    "name_he": "עילוט",
    "name_en": "Ilut",
    "lat": 32.717987,
    "lng": 35.261902,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ein_al_asad",
    "name_he": "עין אל-אסד",
    "name_en": "Ein Al-Asad",
    "lat": 32.940209,
    "lng": 35.3992,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_gev",
    "name_he": "עין גב",
    "name_en": "En Gev",
    "lat": 32.780453,
    "lng": 35.639355,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_dor",
    "name_he": "עין דור",
    "name_en": "En Dor",
    "lat": 32.656958,
    "lng": 35.416945,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_hamifraz",
    "name_he": "עין המפרץ",
    "name_en": "En Hamifraz",
    "lat": 32.903618,
    "lng": 35.096414,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_hanaziv",
    "name_he": "עין הנצי\"ב",
    "name_en": "En Hanaziv",
    "lat": 32.469711,
    "lng": 35.502306,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_haemeq",
    "name_he": "עין העמק",
    "name_en": "En Haemeq",
    "lat": 32.630161,
    "lng": 35.081068,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_hashofet",
    "name_he": "עין השופט",
    "name_en": "En Hashofet",
    "lat": 32.595769,
    "lng": 35.100771,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_ziwan",
    "name_he": "עין זיוון",
    "name_en": "En Ziwan",
    "lat": 33.095515,
    "lng": 35.79502,
    "region": "north",
    "type": "town"
  },
  {
    "id": "en_harod_ihud",
    "name_he": "עין חרוד (איחוד)",
    "name_en": "En Harod (ihud)",
    "lat": 32.56484,
    "lng": 35.390705,
    "region": "north",
    "type": "town",
    "aliases": [
      "עין חרוד, תל יוסף"
    ]
  },
  {
    "id": "en_harod_meuhad",
    "name_he": "עין חרוד (מאוחד)",
    "name_en": "En Harod(me'uhad)",
    "lat": 32.557256,
    "lng": 35.391837,
    "region": "north",
    "type": "town",
    "aliases": [
      "עין חרוד, תל יוסף"
    ]
  },
  {
    "id": "en_yaaqov",
    "name_he": "עין יעקב",
    "name_en": "En Ya'aqov",
    "lat": 33.010506,
    "lng": 35.231392,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ein_mahel",
    "name_he": "עין מאהל",
    "name_en": "Ein Mahel",
    "lat": 32.721858,
    "lng": 35.352818,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ein_qiniyye",
    "name_he": "עין קנייא",
    "name_en": "Ein Qiniyye",
    "lat": 33.23656,
    "lng": 35.73146,
    "region": "north",
    "type": "town"
  },
  {
    "id": "acre",
    "name_he": "עכו",
    "name_en": "Acre",
    "lat": 32.9261,
    "lng": 35.0764,
    "region": "north",
    "type": "city"
  },
  {
    "id": "alma",
    "name_he": "עלמה",
    "name_en": "Alma",
    "lat": 33.051877,
    "lng": 35.499942,
    "region": "north",
    "type": "town"
  },
  {
    "id": "amuqqa",
    "name_he": "עמוקה",
    "name_en": "Amuqqa",
    "lat": 32.997745,
    "lng": 35.52475,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ammiad",
    "name_he": "עמיעד",
    "name_en": "Ammi'ad",
    "lat": 32.928371,
    "lng": 35.541354,
    "region": "north",
    "type": "town"
  },
  {
    "id": "amir",
    "name_he": "עמיר",
    "name_en": "Amir",
    "lat": 33.177541,
    "lng": 35.621141,
    "region": "north",
    "type": "town"
  },
  {
    "id": "amqa",
    "name_he": "עמקה",
    "name_en": "Amqa",
    "lat": 32.979017,
    "lng": 35.162519,
    "region": "north",
    "type": "town"
  },
  {
    "id": "afula",
    "name_he": "עפולה",
    "name_en": "Afula",
    "lat": 32.6078,
    "lng": 35.2891,
    "region": "north",
    "type": "city"
  },
  {
    "id": "atsmon_segev",
    "name_he": "עצמון שגב",
    "name_en": "Atsmon-Segev",
    "lat": 32.865483,
    "lng": 35.252422,
    "region": "north",
    "type": "town"
  },
  {
    "id": "arrabe",
    "name_he": "עראבה",
    "name_en": "Arrabe",
    "lat": 32.85108,
    "lng": 35.337689,
    "region": "north",
    "type": "town"
  },
  {
    "id": "aramsha",
    "name_he": "עראמשה",
    "name_en": "Aramsha",
    "lat": 33.08884,
    "lng": 35.224876,
    "region": "north",
    "type": "town"
  },
  {
    "id": "arrab_al_naim",
    "name_he": "ערב אל נעים",
    "name_en": "Arrab Al Naim",
    "lat": 32.887965,
    "lng": 35.290532,
    "region": "north",
    "type": "town"
  },
  {
    "id": "poriyya_kefar_avoda",
    "name_he": "פוריה - כפר עבודה",
    "name_en": "Poriyya-Kefar Avoda",
    "lat": 32.716908,
    "lng": 35.548058,
    "region": "north",
    "type": "town"
  },
  {
    "id": "poriyya_newe_oved",
    "name_he": "פוריה - נווה עובד",
    "name_en": "Poriyya-Newe Oved",
    "lat": 32.74622,
    "lng": 35.535353,
    "region": "north",
    "type": "town"
  },
  {
    "id": "poriyya_illit",
    "name_he": "פוריה עילית",
    "name_en": "Poriyya Illit",
    "lat": 32.730652,
    "lng": 35.54654,
    "region": "north",
    "type": "town"
  },
  {
    "id": "pelekh",
    "name_he": "פלך",
    "name_en": "Pelekh",
    "lat": 32.932852,
    "lng": 35.235779,
    "region": "north",
    "type": "town"
  },
  {
    "id": "fassuta",
    "name_he": "פסוטה",
    "name_en": "Fassuta",
    "lat": 33.048083,
    "lng": 35.310181,
    "region": "north",
    "type": "town"
  },
  {
    "id": "peqiin_buqeia",
    "name_he": "פקיעין (בוקייעה)",
    "name_en": "Peqi'in (buqei'a)",
    "lat": 32.97396,
    "lng": 35.330754,
    "region": "north",
    "type": "town"
  },
  {
    "id": "peqiin_hadasha",
    "name_he": "פקיעין חדשה",
    "name_en": "Peqi'in Hadasha",
    "lat": 32.982391,
    "lng": 35.323417,
    "region": "north",
    "type": "town",
    "aliases": [
      "פקיעין החדשה"
    ]
  },
  {
    "id": "parod",
    "name_he": "פרוד",
    "name_en": "Parod",
    "lat": 32.932332,
    "lng": 35.432741,
    "region": "north",
    "type": "town"
  },
  {
    "id": "perazon",
    "name_he": "פרזון",
    "name_en": "Perazon",
    "lat": 32.545834,
    "lng": 35.3104,
    "region": "north",
    "type": "town"
  },
  {
    "id": "zviyya",
    "name_he": "צביה",
    "name_en": "Zviyya",
    "lat": 32.889863,
    "lng": 35.331115,
    "region": "north",
    "type": "town",
    "aliases": [
      "מעלה צביה"
    ]
  },
  {
    "id": "zivon",
    "name_he": "צבעון",
    "name_en": "Ziv'on",
    "lat": 33.025458,
    "lng": 35.416835,
    "region": "north",
    "type": "town"
  },
  {
    "id": "zuriel",
    "name_he": "צוריאל",
    "name_en": "Zuri'el",
    "lat": 33.006636,
    "lng": 35.314215,
    "region": "north",
    "type": "town"
  },
  {
    "id": "zurit",
    "name_he": "צורית",
    "name_en": "Zurit",
    "lat": 32.902113,
    "lng": 35.251126,
    "region": "north",
    "type": "town"
  },
  {
    "id": "zippori",
    "name_he": "ציפורי",
    "name_en": "Zippori",
    "lat": 32.746576,
    "lng": 35.279114,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sandala",
    "name_he": "צנדלה",
    "name_en": "Sandala",
    "lat": 32.522323,
    "lng": 35.323504,
    "region": "north",
    "type": "town",
    "aliases": [
      "סנדלה"
    ]
  },
  {
    "id": "safed",
    "name_he": "צפת",
    "name_en": "Safed",
    "lat": 32.9646,
    "lng": 35.496,
    "region": "north",
    "type": "city"
  },
  {
    "id": "qidmat_zevi",
    "name_he": "קדמת צבי",
    "name_en": "Qidmat Zevi",
    "lat": 33.027836,
    "lng": 35.699305,
    "region": "north",
    "type": "town"
  },
  {
    "id": "qaddarim",
    "name_he": "קדרים",
    "name_en": "Qaddarim",
    "lat": 32.898812,
    "lng": 35.474402,
    "region": "north",
    "type": "town"
  },
  {
    "id": "qoranit",
    "name_he": "קורנית",
    "name_en": "Qoranit",
    "lat": 32.843319,
    "lng": 35.252878,
    "region": "north",
    "type": "town"
  },
  {
    "id": "qela",
    "name_he": "קלע",
    "name_en": "Qela",
    "lat": 33.13236,
    "lng": 35.686676,
    "region": "north",
    "type": "town",
    "aliases": [
      "קלע אלון"
    ]
  },
  {
    "id": "katzrin",
    "name_he": "קצרין",
    "name_en": "Katzrin",
    "lat": 32.9943,
    "lng": 35.6917,
    "region": "north",
    "type": "local_council"
  },
  {
    "id": "qiryat_shemona",
    "name_he": "קרית שמונה",
    "name_en": "Qiryat Shemona",
    "lat": 33.206099,
    "lng": 35.571108,
    "region": "north",
    "type": "town"
  },
  {
    "id": "qeshet",
    "name_he": "קשת",
    "name_en": "Qeshet",
    "lat": 32.977601,
    "lng": 35.810039,
    "region": "north",
    "type": "town"
  },
  {
    "id": "rame",
    "name_he": "ראמה",
    "name_en": "Rame",
    "lat": 32.938406,
    "lng": 35.366988,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ras_al_ein",
    "name_he": "ראס אל-עין",
    "name_en": "Ras Al-Ein",
    "lat": 32.914083,
    "lng": 35.372193,
    "region": "north",
    "type": "town"
  },
  {
    "id": "rosh_pina",
    "name_he": "ראש פינה",
    "name_en": "Rosh Pina",
    "lat": 32.9693,
    "lng": 35.543,
    "region": "north",
    "type": "local_council"
  },
  {
    "id": "ravid",
    "name_he": "רביד",
    "name_en": "Ravid",
    "lat": 32.850651,
    "lng": 35.463216,
    "region": "north",
    "type": "town"
  },
  {
    "id": "regba",
    "name_he": "רגבה",
    "name_en": "Regba",
    "lat": 32.976192,
    "lng": 35.098642,
    "region": "north",
    "type": "town"
  },
  {
    "id": "rewaya",
    "name_he": "רוויה",
    "name_en": "Rewaya",
    "lat": 32.44791,
    "lng": 35.47177,
    "region": "north",
    "type": "town"
  },
  {
    "id": "rummane",
    "name_he": "רומאנה",
    "name_en": "Rummane",
    "lat": 32.788227,
    "lng": 35.311099,
    "region": "north",
    "type": "town"
  },
  {
    "id": "rumat_heib",
    "name_he": "רומת הייב",
    "name_en": "Rumat Heib",
    "lat": 32.779388,
    "lng": 35.302975,
    "region": "north",
    "type": "town"
  },
  {
    "id": "rehov",
    "name_he": "רחוב",
    "name_en": "Rehov",
    "lat": 32.451094,
    "lng": 35.488929,
    "region": "north",
    "type": "town"
  },
  {
    "id": "reihaniyye",
    "name_he": "ריחאניה",
    "name_en": "Reihaniyye",
    "lat": 33.048697,
    "lng": 35.48781,
    "region": "north",
    "type": "town",
    "aliases": [
      "ריחאנייה"
    ]
  },
  {
    "id": "reine",
    "name_he": "ריינה",
    "name_en": "Reine",
    "lat": 32.719567,
    "lng": 35.313961,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ram_on",
    "name_he": "רם-און",
    "name_en": "Ram-On",
    "lat": 32.527445,
    "lng": 35.258968,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramot",
    "name_he": "רמות",
    "name_en": "Ramot",
    "lat": 32.853505,
    "lng": 35.649852,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramot_menashe",
    "name_he": "רמות מנשה",
    "name_en": "Ramot Menashe",
    "lat": 32.59712,
    "lng": 35.057502,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramot_naftali",
    "name_he": "רמות נפתלי",
    "name_en": "Ramot Naftali",
    "lat": 33.100872,
    "lng": 35.553168,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramat_dawid",
    "name_he": "רמת דוד",
    "name_en": "Ramat Dawid",
    "lat": 32.678199,
    "lng": 35.202871,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramat_hashofet",
    "name_he": "רמת השופט",
    "name_en": "Ramat Hashofet",
    "lat": 32.611643,
    "lng": 35.097175,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramat_yishay",
    "name_he": "רמת ישי",
    "name_en": "Ramat Yishay",
    "lat": 32.703229,
    "lng": 35.166036,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramat_magshimim",
    "name_he": "רמת מגשימים",
    "name_en": "Ramat Magshimim",
    "lat": 32.844462,
    "lng": 35.808145,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramat_zevi",
    "name_he": "רמת צבי",
    "name_en": "Ramat Zevi",
    "lat": 32.591384,
    "lng": 35.414037,
    "region": "north",
    "type": "town"
  },
  {
    "id": "raqefet",
    "name_he": "רקפת",
    "name_en": "Raqefet",
    "lat": 32.85462,
    "lng": 35.264593,
    "region": "north",
    "type": "town"
  },
  {
    "id": "reshafim",
    "name_he": "רשפים",
    "name_en": "Reshafim",
    "lat": 32.48025,
    "lng": 35.476681,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shear_yashuv",
    "name_he": "שאר ישוב",
    "name_en": "She'ar Yashuv",
    "lat": 33.229953,
    "lng": 35.650206,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shave_ziyyon",
    "name_he": "שבי ציון",
    "name_en": "Shave Ziyyon",
    "lat": 32.981328,
    "lng": 35.084108,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shibli",
    "name_he": "שבלי - אום אל-גנם",
    "name_en": "Shibli",
    "lat": 32.678624,
    "lng": 35.40502,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_ilan",
    "name_he": "שדה אילן",
    "name_en": "Sede Ilan",
    "lat": 32.748322,
    "lng": 35.423638,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_eliyyahu",
    "name_he": "שדה אליהו",
    "name_en": "Sede Eliyyahu",
    "lat": 32.441176,
    "lng": 35.514269,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_eliezer",
    "name_he": "שדה אליעזר",
    "name_en": "Sede Eli'ezer",
    "lat": 33.04492,
    "lng": 35.559959,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_yaaqov",
    "name_he": "שדה יעקב",
    "name_en": "Sede Ya'aqov",
    "lat": 32.698229,
    "lng": 35.141107,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_nahum",
    "name_he": "שדה נחום",
    "name_en": "Sede Nahum",
    "lat": 32.525754,
    "lng": 35.481942,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_nehemya",
    "name_he": "שדה נחמיה",
    "name_en": "Sede Nehemya",
    "lat": 33.186203,
    "lng": 35.623436,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sede_terumot",
    "name_he": "שדי תרומות",
    "name_en": "Sede Terumot",
    "lat": 32.438995,
    "lng": 35.485979,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shadmot_devora",
    "name_he": "שדמות דבורה",
    "name_en": "Shadmot Devora",
    "lat": 32.696533,
    "lng": 35.435475,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shomera",
    "name_he": "שומרה",
    "name_en": "Shomera",
    "lat": 33.084659,
    "lng": 35.28504,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shorashim",
    "name_he": "שורשים",
    "name_en": "Shorashim",
    "lat": 32.893181,
    "lng": 35.25907,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shezor",
    "name_he": "שזור",
    "name_en": "Shezor",
    "lat": 32.932437,
    "lng": 35.352415,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sheikh_dannun",
    "name_he": "שייח' דנון",
    "name_en": "Sheikh Dannun",
    "lat": 32.993917,
    "lng": 35.147982,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shekhanya",
    "name_he": "שכניה",
    "name_en": "Shekhanya",
    "lat": 32.848374,
    "lng": 35.247214,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sheluhot",
    "name_he": "שלוחות",
    "name_en": "Sheluhot",
    "lat": 32.471945,
    "lng": 35.481012,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shlomi",
    "name_he": "שלומי",
    "name_en": "Shlomi",
    "lat": 33.0722,
    "lng": 35.1472,
    "region": "north",
    "type": "local_council"
  },
  {
    "id": "shamir",
    "name_he": "שמיר",
    "name_en": "Shamir",
    "lat": 33.16582,
    "lng": 35.660101,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shamerat",
    "name_he": "שמרת",
    "name_en": "Shamerat",
    "lat": 32.950581,
    "lng": 35.095606,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shimshit",
    "name_he": "שמשית",
    "name_en": "Shimshit",
    "lat": 32.733072,
    "lng": 35.246635,
    "region": "north",
    "type": "town"
  },
  {
    "id": "senir",
    "name_he": "שניר",
    "name_en": "Senir",
    "lat": 33.240431,
    "lng": 35.677169,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shaab",
    "name_he": "שעב",
    "name_en": "Sha'ab",
    "lat": 32.889053,
    "lng": 35.241661,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shaal",
    "name_he": "שעל",
    "name_en": "Sha'al",
    "lat": 33.114905,
    "lng": 35.718775,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shaar_hagolan",
    "name_he": "שער הגולן",
    "name_en": "Sha'ar Hagolan",
    "lat": 32.686649,
    "lng": 35.604238,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shefer",
    "name_he": "שפר",
    "name_en": "Shefer",
    "lat": 32.944008,
    "lng": 35.43646,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shefaram",
    "name_he": "שפרעם",
    "name_en": "Shefar'am",
    "lat": 32.805726,
    "lng": 35.171987,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sharona",
    "name_he": "שרונה",
    "name_en": "Sharona",
    "lat": 32.728245,
    "lng": 35.463283,
    "region": "north",
    "type": "town"
  },
  {
    "id": "sarid",
    "name_he": "שריד",
    "name_en": "Sarid",
    "lat": 32.663275,
    "lng": 35.225363,
    "region": "north",
    "type": "town"
  },
  {
    "id": "shetula",
    "name_he": "שתולה",
    "name_en": "Shetula",
    "lat": 33.085823,
    "lng": 35.313893,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tuval",
    "name_he": "תובל",
    "name_en": "Tuval",
    "lat": 32.929803,
    "lng": 35.246048,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tel_yosef",
    "name_he": "תל יוסף",
    "name_en": "Tel Yosef",
    "lat": 32.55515,
    "lng": 35.399414,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tel_adashim",
    "name_he": "תל עדשים",
    "name_en": "Tel Adashim",
    "lat": 32.655988,
    "lng": 35.301328,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tel_qazir",
    "name_he": "תל קציר",
    "name_en": "Tel Qazir",
    "lat": 32.70544,
    "lng": 35.617686,
    "region": "north",
    "type": "town"
  },
  {
    "id": "tel_teomim",
    "name_he": "תל תאומים",
    "name_en": "Tel Te'omim",
    "lat": 32.441986,
    "lng": 35.495984,
    "region": "north",
    "type": "town"
  },
  {
    "id": "timrat",
    "name_he": "תמרת",
    "name_en": "Timrat",
    "lat": 32.702621,
    "lng": 35.225204,
    "region": "north",
    "type": "town"
  },
  {
    "id": "ramat_trump",
    "name_he": "רמת טראמפ",
    "name_en": "Ramat Trump",
    "lat": 33.132686,
    "lng": 35.688977,
    "region": "north",
    "type": "settlement"
  }
];
