import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "avigedor",
    "name_he": "אביגדור",
    "name_en": "Avigedor",
    "lat": 31.70974,
    "lng": 34.74365,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "even_shemuel",
    "name_he": "אבן שמואל",
    "name_en": "Even Shemu'el",
    "lat": 31.574852,
    "lng": 34.765693,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "or_haner",
    "name_he": "אור הנר",
    "name_en": "Or Haner",
    "lat": 31.556632,
    "lng": 34.600896,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "orot",
    "name_he": "אורות",
    "name_en": "Orot",
    "lat": 31.742455,
    "lng": 34.735142,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ahawa",
    "name_he": "אחווה",
    "name_en": "Ahawa",
    "lat": 31.7437,
    "lng": 34.768889,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ahuzzam",
    "name_he": "אחוזם",
    "name_en": "Ahuzzam",
    "lat": 31.553971,
    "lng": 34.770361,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ibbim",
    "name_he": "איבים",
    "name_en": "Ibbim",
    "lat": 31.533363,
    "lng": 34.61019,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "etan",
    "name_he": "איתן",
    "name_en": "Etan",
    "lat": 31.572371,
    "lng": 34.747928,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "al_azy",
    "name_he": "אל-עזי",
    "name_en": "Al-Azy",
    "lat": 31.722582,
    "lng": 34.798132,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "alumma",
    "name_he": "אלומה",
    "name_en": "Alumma",
    "lat": 31.652021,
    "lng": 34.74259,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "eliav",
    "name_he": "אליאב",
    "name_en": "Eliav",
    "lat": 31.531012,
    "lng": 34.933368,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "emunim",
    "name_he": "אמונים",
    "name_en": "Emunim",
    "lat": 31.743763,
    "lng": 34.676469,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "amazya",
    "name_he": "אמציה",
    "name_en": "Amazya",
    "lat": 31.534988,
    "lng": 34.912808,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "erez",
    "name_he": "ארז",
    "name_en": "Erez",
    "lat": 31.560045,
    "lng": 34.566748,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ashdod",
    "name_he": "אשדוד",
    "name_en": "Ashdod",
    "lat": 31.8044,
    "lng": 34.6553,
    "region": "shephelah",
    "type": "city"
  },
  {
    "id": "ashkelon",
    "name_he": "אשקלון",
    "name_en": "Ashkelon",
    "lat": 31.6688,
    "lng": 34.5743,
    "region": "shephelah",
    "type": "city"
  },
  {
    "id": "beer_tuveya",
    "name_he": "באר טוביה",
    "name_en": "Be'er Tuveya",
    "lat": 31.73174,
    "lng": 34.719422,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "bizzaron",
    "name_he": "ביצרון",
    "name_en": "Bizzaron",
    "lat": 31.79611,
    "lng": 34.730218,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "bet_guvrin",
    "name_he": "בית גוברין",
    "name_en": "Bet Guvrin",
    "lat": 31.612276,
    "lng": 34.895783,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "bet_nir",
    "name_he": "בית ניר",
    "name_en": "Bet Nir",
    "lat": 31.648029,
    "lng": 34.873746,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "bet_ezra",
    "name_he": "בית עזרא",
    "name_en": "Bet Ezra",
    "lat": 31.734426,
    "lng": 34.655066,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "beit_kama",
    "name_he": "בית קמה",
    "name_en": "Beit Kama",
    "lat": 31.3925,
    "lng": 34.7516,
    "region": "shephelah",
    "type": "local_council"
  },
  {
    "id": "bet_shiqma",
    "name_he": "בית שקמה",
    "name_en": "Bet Shiqma",
    "lat": 31.63782,
    "lng": 34.608501,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "bne_dkalim",
    "name_he": "בני דקלים",
    "name_en": "Bne Dkalim",
    "lat": 31.518346,
    "lng": 34.917708,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "beror_hayil",
    "name_he": "ברור חיל",
    "name_en": "Beror Hayil",
    "lat": 31.557906,
    "lng": 34.645443,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "berekhya",
    "name_he": "ברכיה",
    "name_en": "Berekhya",
    "lat": 31.669736,
    "lng": 34.625852,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "bat_hadar",
    "name_he": "בת הדר",
    "name_en": "Bat Hadar",
    "lat": 32.213675,
    "lng": 34.81618,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "gevim",
    "name_he": "גבים",
    "name_en": "Gevim",
    "lat": 31.508425,
    "lng": 34.596297,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "givati",
    "name_he": "גבעתי",
    "name_en": "Giv'ati",
    "lat": 31.732534,
    "lng": 34.679861,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "gevaram",
    "name_he": "גברעם",
    "name_en": "Gevar'am",
    "lat": 31.591953,
    "lng": 34.61219,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "gedera",
    "name_he": "גדרה",
    "name_en": "Gedera",
    "lat": 31.814,
    "lng": 34.7794,
    "region": "shephelah",
    "type": "local_council"
  },
  {
    "id": "gea",
    "name_he": "גיאה",
    "name_en": "Ge'a",
    "lat": 31.627964,
    "lng": 34.603058,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "galon",
    "name_he": "גלאון",
    "name_en": "Gal'on",
    "lat": 31.633306,
    "lng": 34.847872,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "gan_yavne",
    "name_he": "גן יבנה",
    "name_en": "Gan Yavne",
    "lat": 31.788,
    "lng": 34.7048,
    "region": "shephelah",
    "type": "local_council"
  },
  {
    "id": "gat_qibbuz",
    "name_he": "גת (קיבוץ)",
    "name_en": "Gat(qibbuz)",
    "lat": 31.627284,
    "lng": 34.793923,
    "region": "shephelah",
    "type": "kibbutz",
    "aliases": [
      "גת"
    ]
  },
  {
    "id": "dorot",
    "name_he": "דורות",
    "name_en": "Dorot",
    "lat": 31.50561,
    "lng": 34.646103,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "hodiyya",
    "name_he": "הודיה",
    "name_en": "Hodiyya",
    "lat": 31.675422,
    "lng": 34.641848,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "wardon",
    "name_he": "ורדון",
    "name_en": "Wardon",
    "lat": 31.664118,
    "lng": 34.781332,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "zavdiel",
    "name_he": "זבדיאל",
    "name_en": "Zavdi'el",
    "lat": 31.65896,
    "lng": 34.760245,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "zohar",
    "name_he": "זוהר",
    "name_en": "Zohar",
    "lat": 31.595704,
    "lng": 34.692565,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ziqim",
    "name_he": "זיקים",
    "name_en": "Ziqim",
    "lat": 31.608939,
    "lng": 34.521692,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "zerahya",
    "name_he": "זרחיה",
    "name_en": "Zerahya",
    "lat": 31.681813,
    "lng": 34.746232,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "helez",
    "name_he": "חלץ",
    "name_en": "Helez",
    "lat": 31.578022,
    "lng": 34.657577,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "hazav",
    "name_he": "חצב",
    "name_en": "Hazav",
    "lat": 31.780491,
    "lng": 34.769952,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "hazor_ashdod",
    "name_he": "חצור-אשדוד",
    "name_en": "Hazor-Ashdod",
    "lat": 31.772505,
    "lng": 34.720161,
    "region": "shephelah",
    "type": "town",
    "aliases": [
      "חצור"
    ]
  },
  {
    "id": "yad_mordekhay",
    "name_he": "יד מרדכי",
    "name_en": "Yad Mordekhay",
    "lat": 31.588119,
    "lng": 34.557927,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "yad_natan",
    "name_he": "יד נתן",
    "name_en": "Yad Natan",
    "lat": 31.654373,
    "lng": 34.705504,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "yakhini",
    "name_he": "יכיני",
    "name_en": "Yakhini",
    "lat": 31.482959,
    "lng": 34.599994,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "yinnon",
    "name_he": "ינון",
    "name_en": "Yinnon",
    "lat": 31.742475,
    "lng": 34.781674,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kokhav_mikhael",
    "name_he": "כוכב מיכאל",
    "name_en": "Kokhav Mikha'el",
    "lat": 31.630417,
    "lng": 34.669229,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kannot",
    "name_he": "כנות",
    "name_en": "Kannot",
    "lat": 31.802652,
    "lng": 34.751861,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kefar_ahim",
    "name_he": "כפר אחים",
    "name_en": "Kefar Ahim",
    "lat": 31.744925,
    "lng": 34.756266,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kefar_harif",
    "name_he": "כפר הרי\"ף",
    "name_en": "Kefar Harif",
    "lat": 31.74698,
    "lng": 34.790883,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kefar_warburg",
    "name_he": "כפר ורבורג",
    "name_en": "Kefar Warburg",
    "lat": 31.719392,
    "lng": 34.725501,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kefar_menahem",
    "name_he": "כפר מנחם",
    "name_en": "Kefar Menahem",
    "lat": 31.731002,
    "lng": 34.834307,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kefar_silver",
    "name_he": "כפר סילבר",
    "name_en": "Kefar Silver",
    "lat": 31.673389,
    "lng": 34.612214,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "kefar_azza",
    "name_he": "כפר עזה",
    "name_en": "Kefar Azza",
    "lat": 31.483573,
    "lng": 34.53304,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "karme_qatif",
    "name_he": "כרמי קטיף",
    "name_en": "Karme Qatif",
    "lat": 30.833038,
    "lng": 34.73644,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "karmiyya",
    "name_he": "כרמיה",
    "name_en": "Karmiyya",
    "lat": 31.604898,
    "lng": 34.542323,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "lakhish",
    "name_he": "לכיש",
    "name_en": "Lakhish",
    "lat": 31.563637,
    "lng": 34.841011,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "mavqiim",
    "name_he": "מבקיעים",
    "name_en": "Mavqi'im",
    "lat": 31.621736,
    "lng": 34.575318,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "menuha",
    "name_he": "מנוחה",
    "name_en": "Menuha",
    "lat": 31.656607,
    "lng": 34.775857,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "mefallesim",
    "name_he": "מפלסים",
    "name_en": "Mefallesim",
    "lat": 31.501233,
    "lng": 34.564128,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "merkaz_shappira",
    "name_he": "מרכז שפירא",
    "name_en": "Merkaz Shappira",
    "lat": 31.697109,
    "lng": 34.708307,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "massuot_yizhaq",
    "name_he": "משואות יצחק",
    "name_en": "Massuot Yizhaq",
    "lat": 31.70271,
    "lng": 34.691571,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "mashen",
    "name_he": "משען",
    "name_en": "Mash'en",
    "lat": 31.657844,
    "lng": 34.623171,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "negba",
    "name_he": "נגבה",
    "name_en": "Negba",
    "lat": 31.660816,
    "lng": 34.683199,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nehora",
    "name_he": "נהורה",
    "name_en": "Nehora",
    "lat": 31.622934,
    "lng": 34.705197,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nogah",
    "name_he": "נוגה",
    "name_en": "Nogah",
    "lat": 31.624371,
    "lng": 34.69478,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "newe_mivtah",
    "name_he": "נווה מבטח",
    "name_en": "Newe Mivtah",
    "lat": 31.805503,
    "lng": 34.740489,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "noam",
    "name_he": "נועם",
    "name_en": "No'am",
    "lat": 31.5673,
    "lng": 34.78858,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nahal_oz",
    "name_he": "נחל עוז",
    "name_en": "Nahal Oz",
    "lat": 31.472368,
    "lng": 34.497677,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nahala",
    "name_he": "נחלה",
    "name_en": "Nahala",
    "lat": 31.65888,
    "lng": 34.794861,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "neta",
    "name_he": "נטע",
    "name_en": "Neta",
    "lat": 31.476363,
    "lng": 34.925832,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nizzan",
    "name_he": "ניצן",
    "name_en": "Nizzan",
    "lat": 31.739933,
    "lng": 34.631132,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nizzan_b",
    "name_he": "ניצן ב'",
    "name_en": "Nizzan B",
    "lat": 31.734881,
    "lng": 34.632851,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nizzanim",
    "name_he": "ניצנים",
    "name_en": "Nizzanim",
    "lat": 31.716586,
    "lng": 34.635125,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nir_banim",
    "name_he": "ניר בנים",
    "name_en": "Nir Banim",
    "lat": 31.671608,
    "lng": 34.755005,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nir_hen",
    "name_he": "ניר ח\"ן",
    "name_en": "Nir Hen",
    "lat": 31.609273,
    "lng": 34.714784,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nir_yisrael",
    "name_he": "ניר ישראל",
    "name_en": "Nir Yisra'el",
    "lat": 31.687588,
    "lng": 34.636194,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "nir_am",
    "name_he": "ניר עם",
    "name_en": "Nir Am",
    "lat": 31.520899,
    "lng": 34.580761,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "netiv_haasara",
    "name_he": "נתיב העשרה",
    "name_en": "Netiv Haasara",
    "lat": 31.569154,
    "lng": 34.540251,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "segula",
    "name_he": "סגולה",
    "name_en": "Segula",
    "lat": 31.670839,
    "lng": 34.779573,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "uza",
    "name_he": "עוזה",
    "name_en": "Uza",
    "lat": 31.592267,
    "lng": 34.764052,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ozem",
    "name_he": "עוצם",
    "name_en": "Ozem",
    "lat": 31.636905,
    "lng": 34.704354,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ezer",
    "name_he": "עזר",
    "name_en": "Ezer",
    "lat": 31.736885,
    "lng": 34.670869,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "sderot_south",
    "name_he": "עזריאל",
    "name_en": "Azriel",
    "lat": 31.4667,
    "lng": 34.6667,
    "region": "shephelah",
    "type": "settlement"
  },
  {
    "id": "azriqam",
    "name_he": "עזריקם",
    "name_en": "Azriqam",
    "lat": 31.751239,
    "lng": 34.697278,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "en_zurim",
    "name_he": "עין צורים",
    "name_en": "En Zurim",
    "lat": 31.695429,
    "lng": 34.718643,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "arugot",
    "name_he": "ערוגות",
    "name_en": "Arugot",
    "lat": 31.73158,
    "lng": 34.771966,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "qedma",
    "name_he": "קדמה",
    "name_en": "Qedma",
    "lat": 31.701519,
    "lng": 34.775826,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "qomemiyyut",
    "name_he": "קוממיות",
    "name_en": "Qomemiyyut",
    "lat": 31.662182,
    "lng": 34.730122,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "qiryat_gat",
    "name_he": "קרית גת",
    "name_en": "Qiryat Gat",
    "lat": 31.611108,
    "lng": 34.760825,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "qiryat_malakhi",
    "name_he": "קרית מלאכי",
    "name_en": "Qiryat Mal'akhi",
    "lat": 31.731532,
    "lng": 34.745468,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "revadim",
    "name_he": "רבדים",
    "name_en": "Revadim",
    "lat": 31.772357,
    "lng": 34.815616,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "rewaha",
    "name_he": "רווחה",
    "name_en": "Rewaha",
    "lat": 31.649516,
    "lng": 34.733569,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "ruhama",
    "name_he": "רוחמה",
    "name_en": "Ruhama",
    "lat": 31.496953,
    "lng": 34.704957,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "sede_dawid",
    "name_he": "שדה דוד",
    "name_en": "Sede Dawid",
    "lat": 31.575693,
    "lng": 34.683323,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "sede_yoav",
    "name_he": "שדה יואב",
    "name_en": "Sede Yo'av",
    "lat": 31.64324,
    "lng": 34.681454,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "sede_moshe",
    "name_he": "שדה משה",
    "name_en": "Sede Moshe",
    "lat": 31.611144,
    "lng": 34.80174,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "sede_uzziyyahu",
    "name_he": "שדה עוזיהו",
    "name_en": "Sede Uzziyyahu",
    "lat": 31.757345,
    "lng": 34.67651,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "shahar",
    "name_he": "שחר",
    "name_en": "Shahar",
    "lat": 31.618964,
    "lng": 34.724789,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "shalwa",
    "name_he": "שלווה",
    "name_en": "Shalwa",
    "lat": 31.564441,
    "lng": 34.767637,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "shafir",
    "name_he": "שפיר",
    "name_en": "Shafir",
    "lat": 31.700406,
    "lng": 34.723631,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "sheqef",
    "name_he": "שקף",
    "name_en": "Sheqef",
    "lat": 31.51354,
    "lng": 34.935435,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "shetulim",
    "name_he": "שתולים",
    "name_en": "Shetulim",
    "lat": 31.7737,
    "lng": 34.683903,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "timmorim",
    "name_he": "תימורים",
    "name_en": "Timmorim",
    "lat": 31.714539,
    "lng": 34.761585,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "talme_yehiel",
    "name_he": "תלמי יחיאל",
    "name_en": "Talme Yehi'el",
    "lat": 31.7534,
    "lng": 34.762211,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "talme_yafe",
    "name_he": "תלמי יפה",
    "name_en": "Talme Yafe",
    "lat": 31.615757,
    "lng": 34.617355,
    "region": "shephelah",
    "type": "town"
  },
  {
    "id": "telamim",
    "name_he": "תלמים",
    "name_en": "Telamim",
    "lat": 31.564832,
    "lng": 34.672709,
    "region": "shephelah",
    "type": "town"
  }
];
