import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "abu_juweiid",
    "name_he": "אבו ג'ווייעד (שבט)",
    "name_en": "Abu Juwei'id",
    "lat": 31.180616,
    "lng": 35.073519,
    "region": "south",
    "type": "town"
  },
  {
    "id": "abu_sureihan",
    "name_he": "אבו סריחאן (שבט)",
    "name_en": "Abu Sureihan",
    "lat": 31.262557,
    "lng": 34.885082,
    "region": "south",
    "type": "town"
  },
  {
    "id": "abu_abdun",
    "name_he": "אבו עבדון (שבט)",
    "name_en": "Abu Abdun",
    "lat": 31.314376,
    "lng": 34.994301,
    "region": "south",
    "type": "town"
  },
  {
    "id": "abu_qureinat",
    "name_he": "אבו קרינאת (יישוב)",
    "name_en": "Abu Qureinat",
    "lat": 31.140543,
    "lng": 34.96307,
    "region": "south",
    "type": "town",
    "aliases": [
      "אבו קרינאת"
    ]
  },
  {
    "id": "abu_ruqayyeq",
    "name_he": "אבו רוקייק (שבט)",
    "name_en": "Abu Ruqayyeq",
    "lat": 31.184053,
    "lng": 34.913398,
    "region": "south",
    "type": "town"
  },
  {
    "id": "abu_tulul",
    "name_he": "אבו תלול",
    "name_en": "Abu Tulul",
    "lat": 31.184354,
    "lng": 34.935406,
    "region": "south",
    "type": "town",
    "aliases": [
      "אבו-תלול והפזורה"
    ]
  },
  {
    "id": "avshalom",
    "name_he": "אבשלום",
    "name_en": "Avshalom",
    "lat": 31.195189,
    "lng": 34.33133,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ohad",
    "name_he": "אוהד",
    "name_en": "Ohad",
    "lat": 31.236984,
    "lng": 34.432011,
    "region": "south",
    "type": "town"
  },
  {
    "id": "umm_batin",
    "name_he": "אום בטין",
    "name_en": "Umm Batin",
    "lat": 31.27231,
    "lng": 34.884437,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ofakim",
    "name_he": "אופקים",
    "name_en": "Ofakim",
    "lat": 31.3185,
    "lng": 34.62,
    "region": "south",
    "type": "city"
  },
  {
    "id": "urim",
    "name_he": "אורים",
    "name_en": "Urim",
    "lat": 31.304548,
    "lng": 34.523773,
    "region": "south",
    "type": "town"
  },
  {
    "id": "elot",
    "name_he": "אילות",
    "name_en": "Elot",
    "lat": 29.580405,
    "lng": 34.963274,
    "region": "south",
    "type": "town"
  },
  {
    "id": "eilat",
    "name_he": "אילת",
    "name_en": "Eilat",
    "lat": 29.5577,
    "lng": 34.9519,
    "region": "south",
    "type": "city"
  },
  {
    "id": "al_sayyid",
    "name_he": "אל סייד",
    "name_en": "Al Sayyid",
    "lat": 31.284891,
    "lng": 34.91381,
    "region": "south",
    "type": "town",
    "aliases": [
      "אל-סייד והפזורה"
    ]
  },
  {
    "id": "elifaz",
    "name_he": "אליפז",
    "name_en": "Elifaz",
    "lat": 29.794277,
    "lng": 35.011748,
    "region": "south",
    "type": "town"
  },
  {
    "id": "asam",
    "name_he": "אעצם (שבט)",
    "name_en": "A'sam",
    "lat": 31.142156,
    "lng": 34.914858,
    "region": "south",
    "type": "town"
  },
  {
    "id": "afeinish",
    "name_he": "אפיניש (שבט)",
    "name_en": "Afeinish",
    "lat": 31.314376,
    "lng": 34.994301,
    "region": "south",
    "type": "town"
  },
  {
    "id": "eshbol",
    "name_he": "אשבול",
    "name_en": "Eshbol",
    "lat": 31.447138,
    "lng": 34.666127,
    "region": "south",
    "type": "town"
  },
  {
    "id": "eshel_hanasi",
    "name_he": "אשל הנשיא",
    "name_en": "Eshel Hanasi",
    "lat": 31.325404,
    "lng": 34.697263,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ashalim",
    "name_he": "אשלים",
    "name_en": "Ashalim",
    "lat": 30.964888,
    "lng": 34.70576,
    "region": "south",
    "type": "town"
  },
  {
    "id": "beer_ora",
    "name_he": "באר אורה",
    "name_en": "Be'er Ora",
    "lat": 29.711138,
    "lng": 34.986854,
    "region": "south",
    "type": "town"
  },
  {
    "id": "beer_gannim",
    "name_he": "באר גנים",
    "name_en": "Beer Gannim",
    "lat": 31.699929,
    "lng": 34.609284,
    "region": "south",
    "type": "town"
  },
  {
    "id": "beer_yaakov",
    "name_he": "באר יעקב",
    "name_en": "Be'er Ya'akov",
    "lat": 31.9408,
    "lng": 34.8336,
    "region": "south",
    "type": "local_council"
  },
  {
    "id": "beer_milka",
    "name_he": "באר מילכה",
    "name_en": "Be'er Milka",
    "lat": 30.931705,
    "lng": 34.40785,
    "region": "south",
    "type": "town"
  },
  {
    "id": "beersheba",
    "name_he": "באר שבע",
    "name_en": "Be'er Sheva",
    "lat": 31.2518,
    "lng": 34.7913,
    "region": "south",
    "type": "city",
    "aliases": [
      "בארשבע",
      "Beer Sheva"
    ]
  },
  {
    "id": "beeri",
    "name_he": "בארי",
    "name_en": "Be'eri",
    "lat": 31.424252,
    "lng": 34.491448,
    "region": "south",
    "type": "town"
  },
  {
    "id": "bitha",
    "name_he": "בטחה",
    "name_en": "Bitha",
    "lat": 31.33441,
    "lng": 34.632091,
    "region": "south",
    "type": "town"
  },
  {
    "id": "bir_hadage",
    "name_he": "ביר הדאג'",
    "name_en": "Bir Hadage",
    "lat": 31.026192,
    "lng": 34.711649,
    "region": "south",
    "type": "town"
  },
  {
    "id": "bet_hagaddi",
    "name_he": "בית הגדי",
    "name_en": "Bet Hagaddi",
    "lat": 31.425038,
    "lng": 34.606859,
    "region": "south",
    "type": "town"
  },
  {
    "id": "bene_nezarim",
    "name_he": "בני נצרים",
    "name_en": "Bene Nezarim",
    "lat": 31.142684,
    "lng": 34.314431,
    "region": "south",
    "type": "town"
  },
  {
    "id": "berosh",
    "name_he": "ברוש",
    "name_en": "Berosh",
    "lat": 31.370565,
    "lng": 34.631838,
    "region": "south",
    "type": "town"
  },
  {
    "id": "gevulot",
    "name_he": "גבולות",
    "name_en": "Gevulot",
    "lat": 31.210527,
    "lng": 34.465774,
    "region": "south",
    "type": "town"
  },
  {
    "id": "givolim",
    "name_he": "גבעולים",
    "name_en": "Giv'olim",
    "lat": 31.396513,
    "lng": 34.590883,
    "region": "south",
    "type": "town"
  },
  {
    "id": "gevaot_bar",
    "name_he": "גבעות בר",
    "name_en": "Geva'ot Bar",
    "lat": 31.35637,
    "lng": 34.758505,
    "region": "south",
    "type": "town"
  },
  {
    "id": "gilat",
    "name_he": "גילת",
    "name_en": "Gilat",
    "lat": 31.326931,
    "lng": 34.65343,
    "region": "south",
    "type": "town"
  },
  {
    "id": "gerofit",
    "name_he": "גרופית",
    "name_en": "Gerofit",
    "lat": 29.938866,
    "lng": 35.065919,
    "region": "south",
    "type": "town"
  },
  {
    "id": "dvir",
    "name_he": "דביר",
    "name_en": "Dvir",
    "lat": 31.412202,
    "lng": 34.824455,
    "region": "south",
    "type": "town"
  },
  {
    "id": "dimona",
    "name_he": "דימונה",
    "name_en": "Dimona",
    "lat": 31.0665,
    "lng": 35.0302,
    "region": "south",
    "type": "city"
  },
  {
    "id": "deqel",
    "name_he": "דקל",
    "name_en": "Deqel",
    "lat": 31.194806,
    "lng": 34.347737,
    "region": "south",
    "type": "town"
  },
  {
    "id": "derigat",
    "name_he": "דריג'את",
    "name_en": "Derig'at",
    "lat": 31.300412,
    "lng": 35.076237,
    "region": "south",
    "type": "town"
  },
  {
    "id": "hawashla",
    "name_he": "הוואשלה (שבט)",
    "name_en": "Hawashla",
    "lat": 31.09281,
    "lng": 34.979783,
    "region": "south",
    "type": "town"
  },
  {
    "id": "huzayyel",
    "name_he": "הוזייל (שבט)",
    "name_en": "Huzayyel",
    "lat": 31.407824,
    "lng": 34.747499,
    "region": "south",
    "type": "town"
  },
  {
    "id": "har_amasa",
    "name_he": "הר עמשא",
    "name_en": "Har Amasa",
    "lat": 31.344161,
    "lng": 35.10171,
    "region": "south",
    "type": "town"
  },
  {
    "id": "zabarga",
    "name_he": "זבארגה (שבט)",
    "name_en": "Zabarga",
    "lat": 31.241388,
    "lng": 35.031164,
    "region": "south",
    "type": "town"
  },
  {
    "id": "zimrat",
    "name_he": "זמרת",
    "name_en": "Zimrat",
    "lat": 31.447915,
    "lng": 34.553234,
    "region": "south",
    "type": "town"
  },
  {
    "id": "zerua",
    "name_he": "זרועה",
    "name_en": "Zeru'a",
    "lat": 31.458527,
    "lng": 34.624408,
    "region": "south",
    "type": "town"
  },
  {
    "id": "holit",
    "name_he": "חולית",
    "name_en": "Holit",
    "lat": 31.230286,
    "lng": 34.325612,
    "region": "south",
    "type": "town"
  },
  {
    "id": "hura",
    "name_he": "חורה",
    "name_en": "Hura",
    "lat": 31.2988,
    "lng": 34.93463,
    "region": "south",
    "type": "town"
  },
  {
    "id": "hazeva",
    "name_he": "חצבה",
    "name_en": "Hazeva",
    "lat": 30.767836,
    "lng": 35.280055,
    "region": "south",
    "type": "town"
  },
  {
    "id": "hazerim",
    "name_he": "חצרים",
    "name_en": "Hazerim",
    "lat": 31.239508,
    "lng": 34.714576,
    "region": "south",
    "type": "town"
  },
  {
    "id": "telalim",
    "name_he": "טללים",
    "name_en": "Telalim",
    "lat": 30.992797,
    "lng": 34.772106,
    "region": "south",
    "type": "town"
  },
  {
    "id": "yevul",
    "name_he": "יבול",
    "name_en": "Yevul",
    "lat": 31.189159,
    "lng": 34.319594,
    "region": "south",
    "type": "town"
  },
  {
    "id": "yahel",
    "name_he": "יהל",
    "name_en": "Yahel",
    "lat": 30.083702,
    "lng": 35.129499,
    "region": "south",
    "type": "town"
  },
  {
    "id": "yoshivya",
    "name_he": "יושיביה",
    "name_en": "Yoshivya",
    "lat": 31.443255,
    "lng": 34.608726,
    "region": "south",
    "type": "town"
  },
  {
    "id": "yotvata",
    "name_he": "יטבתה",
    "name_en": "Yotvata",
    "lat": 29.894979,
    "lng": 35.063072,
    "region": "south",
    "type": "town"
  },
  {
    "id": "yeruham",
    "name_he": "ירוחם",
    "name_en": "Yeruham",
    "lat": 30.9872,
    "lng": 34.9308,
    "region": "south",
    "type": "local_council"
  },
  {
    "id": "yesha",
    "name_he": "ישע",
    "name_en": "Yesha",
    "lat": 31.247455,
    "lng": 34.401973,
    "region": "south",
    "type": "town"
  },
  {
    "id": "yated",
    "name_he": "יתד",
    "name_en": "Yated",
    "lat": 31.206712,
    "lng": 34.326373,
    "region": "south",
    "type": "town"
  },
  {
    "id": "kochlea",
    "name_he": "כחלה",
    "name_en": "Kochlea",
    "lat": 31.288561,
    "lng": 35.051704,
    "region": "south",
    "type": "town"
  },
  {
    "id": "kissufim",
    "name_he": "כיסופים",
    "name_en": "Kissufim",
    "lat": 31.374489,
    "lng": 34.400222,
    "region": "south",
    "type": "town"
  },
  {
    "id": "kemehin",
    "name_he": "כמהין",
    "name_en": "Kemehin",
    "lat": 30.910645,
    "lng": 34.431568,
    "region": "south",
    "type": "town"
  },
  {
    "id": "kuseife",
    "name_he": "כסיפה",
    "name_en": "Kuseife",
    "lat": 31.246974,
    "lng": 35.082618,
    "region": "south",
    "type": "town",
    "aliases": [
      "כסייפה"
    ]
  },
  {
    "id": "kefar_maymon",
    "name_he": "כפר מימון",
    "name_en": "Kefar Maymon",
    "lat": 31.43289,
    "lng": 34.534798,
    "region": "south",
    "type": "town"
  },
  {
    "id": "kerem_shalom",
    "name_he": "כרם שלום",
    "name_en": "Kerem Shalom",
    "lat": 31.227816,
    "lng": 34.28448,
    "region": "south",
    "type": "town"
  },
  {
    "id": "keramim",
    "name_he": "כרמים",
    "name_en": "Keramim",
    "lat": 31.333004,
    "lng": 34.917628,
    "region": "south",
    "type": "town"
  },
  {
    "id": "lahav",
    "name_he": "להב",
    "name_en": "Lahav",
    "lat": 31.379084,
    "lng": 34.869475,
    "region": "south",
    "type": "town"
  },
  {
    "id": "lehavim",
    "name_he": "להבים",
    "name_en": "Lehavim",
    "lat": 31.370005,
    "lng": 34.812736,
    "region": "south",
    "type": "town"
  },
  {
    "id": "lotan",
    "name_he": "לוטן",
    "name_en": "Lotan",
    "lat": 29.986666,
    "lng": 35.087925,
    "region": "south",
    "type": "town"
  },
  {
    "id": "laqye",
    "name_he": "לקיה",
    "name_en": "Laqye",
    "lat": 31.323893,
    "lng": 34.864669,
    "region": "south",
    "type": "town"
  },
  {
    "id": "mabbuim",
    "name_he": "מבועים",
    "name_en": "Mabbu'im",
    "lat": 31.450015,
    "lng": 34.653979,
    "region": "south",
    "type": "town"
  },
  {
    "id": "mivtahim",
    "name_he": "מבטחים",
    "name_en": "Mivtahim",
    "lat": 31.239861,
    "lng": 34.408307,
    "region": "south",
    "type": "town",
    "aliases": [
      "מבטחים עמיעוז ישע"
    ]
  },
  {
    "id": "magen",
    "name_he": "מגן",
    "name_en": "Magen",
    "lat": 31.299629,
    "lng": 34.428916,
    "region": "south",
    "type": "town"
  },
  {
    "id": "midreshet_ben_gurion",
    "name_he": "מדרשת בן גוריון",
    "name_en": "Midreshet Ben Gurion",
    "lat": 30.853164,
    "lng": 34.781641,
    "region": "south",
    "type": "town"
  },
  {
    "id": "meitar",
    "name_he": "מיתר",
    "name_en": "Meitar",
    "lat": 31.3271,
    "lng": 34.9335,
    "region": "south",
    "type": "local_council"
  },
  {
    "id": "makchul",
    "name_he": "מכחול",
    "name_en": "Makchul",
    "lat": 31.288768,
    "lng": 35.075654,
    "region": "south",
    "type": "town"
  },
  {
    "id": "melilot",
    "name_he": "מלילות",
    "name_en": "Melilot",
    "lat": 31.390555,
    "lng": 34.595056,
    "region": "south",
    "type": "town"
  },
  {
    "id": "maslul",
    "name_he": "מסלול",
    "name_en": "Maslul",
    "lat": 31.323394,
    "lng": 34.588845,
    "region": "south",
    "type": "town"
  },
  {
    "id": "masudin_al_azazme",
    "name_he": "מסעודין אל-עזאזמה",
    "name_en": "Mas'udin Al-'azazme",
    "lat": 31.197621,
    "lng": 34.81546,
    "region": "south",
    "type": "town"
  },
  {
    "id": "magalim",
    "name_he": "מעגלים",
    "name_en": "Ma'galim",
    "lat": 31.396379,
    "lng": 34.598919,
    "region": "south",
    "type": "town",
    "aliases": [
      "מעגלים גבעולים מלילות"
    ]
  },
  {
    "id": "mitzpe_ramon",
    "name_he": "מצפה רמון",
    "name_en": "Mitzpe Ramon",
    "lat": 30.6103,
    "lng": 34.8017,
    "region": "south",
    "type": "local_council"
  },
  {
    "id": "merhav_am",
    "name_he": "מרחב עם",
    "name_en": "Merhav Am",
    "lat": 30.888045,
    "lng": 34.828922,
    "region": "south",
    "type": "town"
  },
  {
    "id": "mashabbe_sade",
    "name_he": "משאבי שדה",
    "name_en": "Mash'abbe Sade",
    "lat": 31.004913,
    "lng": 34.786022,
    "region": "south",
    "type": "town"
  },
  {
    "id": "mishmar_hanegev",
    "name_he": "משמר הנגב",
    "name_en": "Mishmar Hanegev",
    "lat": 31.363761,
    "lng": 34.718023,
    "region": "south",
    "type": "town"
  },
  {
    "id": "neot_hakikkar",
    "name_he": "נאות הכיכר",
    "name_en": "Ne'ot Hakikkar",
    "lat": 30.934268,
    "lng": 35.377717,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shizzafon",
    "name_he": "נאות סמדר",
    "name_en": "Shizzafon",
    "lat": 30.049569,
    "lng": 35.027173,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nevatim",
    "name_he": "נבטים",
    "name_en": "Nevatim",
    "lat": 31.223441,
    "lng": 34.881213,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nave",
    "name_he": "נווה",
    "name_en": "Nave",
    "lat": 31.161974,
    "lng": 34.330383,
    "region": "south",
    "type": "town"
  },
  {
    "id": "newe_zohar",
    "name_he": "נווה זוהר",
    "name_en": "Newe Zohar",
    "lat": 31.152532,
    "lng": 35.364601,
    "region": "south",
    "type": "town"
  },
  {
    "id": "newe_harif",
    "name_he": "נווה חריף",
    "name_en": "Newe Harif",
    "lat": 30.037875,
    "lng": 35.037226,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nizzana_qehilat_hin",
    "name_he": "ניצנה (קהילת חינוך)",
    "name_en": "Nizzana (qehilat Hin",
    "lat": 30.884894,
    "lng": 34.422896,
    "region": "south",
    "type": "town",
    "aliases": [
      "ניצנה"
    ]
  },
  {
    "id": "nizzane_sinay",
    "name_he": "ניצני סיני",
    "name_en": "Nizzane Sinay",
    "lat": 30.902882,
    "lng": 34.397541,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nir_yizhaq",
    "name_he": "ניר יצחק",
    "name_en": "Nir Yizhaq",
    "lat": 31.237172,
    "lng": 34.357541,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nir_moshe",
    "name_he": "ניר משה",
    "name_en": "Nir Moshe",
    "lat": 31.477549,
    "lng": 34.631101,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nir_oz",
    "name_he": "ניר עוז",
    "name_en": "Nir Oz",
    "lat": 31.312679,
    "lng": 34.402599,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nir_aqiva",
    "name_he": "ניר עקיבא",
    "name_en": "Nir Aqiva",
    "lat": 31.469932,
    "lng": 34.646697,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nirim",
    "name_he": "נירים",
    "name_en": "Nirim",
    "lat": 31.334587,
    "lng": 34.396125,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nasasra",
    "name_he": "נצאצרה (שבט)",
    "name_en": "Nasasra",
    "lat": 31.216546,
    "lng": 35.10482,
    "region": "south",
    "type": "town"
  },
  {
    "id": "netivot",
    "name_he": "נתיבות",
    "name_en": "Netivot",
    "lat": 31.4227,
    "lng": 34.5894,
    "region": "south",
    "type": "city"
  },
  {
    "id": "sufa",
    "name_he": "סופה",
    "name_en": "Sufa",
    "lat": 31.237133,
    "lng": 34.342,
    "region": "south",
    "type": "town"
  },
  {
    "id": "samar",
    "name_he": "סמר",
    "name_en": "Samar",
    "lat": 29.831708,
    "lng": 35.022823,
    "region": "south",
    "type": "town"
  },
  {
    "id": "saad",
    "name_he": "סעד",
    "name_en": "Sa'ad",
    "lat": 31.470319,
    "lng": 34.535696,
    "region": "south",
    "type": "town"
  },
  {
    "id": "sappir",
    "name_he": "ספיר",
    "name_en": "Sappir",
    "lat": 30.607715,
    "lng": 35.188206,
    "region": "south",
    "type": "town"
  },
  {
    "id": "omer",
    "name_he": "עומר",
    "name_en": "Omer",
    "lat": 31.264148,
    "lng": 34.84559,
    "region": "south",
    "type": "town"
  },
  {
    "id": "uqbi_banu_uqba",
    "name_he": "עוקבי (בנו עוקבה)",
    "name_en": "Uqbi (banu Uqba)",
    "lat": 31.300973,
    "lng": 34.840582,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ezuz",
    "name_he": "עזוז",
    "name_en": "Ezuz",
    "lat": 30.792051,
    "lng": 34.472603,
    "region": "south",
    "type": "town"
  },
  {
    "id": "atawne",
    "name_he": "עטאוונה (שבט)",
    "name_en": "Atawne",
    "lat": 31.282693,
    "lng": 34.935196,
    "region": "south",
    "type": "town"
  },
  {
    "id": "iddan",
    "name_he": "עידן",
    "name_en": "Iddan",
    "lat": 30.805994,
    "lng": 35.300448,
    "region": "south",
    "type": "town"
  },
  {
    "id": "en_gedi",
    "name_he": "עין גדי",
    "name_en": "En Gedi",
    "lat": 31.461415,
    "lng": 35.39428,
    "region": "south",
    "type": "town"
  },
  {
    "id": "en_habesor",
    "name_he": "עין הבשור",
    "name_en": "En Habesor",
    "lat": 31.281546,
    "lng": 34.444065,
    "region": "south",
    "type": "town"
  },
  {
    "id": "en_hashelosha",
    "name_he": "עין השלושה",
    "name_en": "En Hashelosha",
    "lat": 31.351602,
    "lng": 34.401534,
    "region": "south",
    "type": "town"
  },
  {
    "id": "en_hazeva",
    "name_he": "עין חצבה",
    "name_en": "En Hazeva",
    "lat": 30.798305,
    "lng": 35.245817,
    "region": "south",
    "type": "town"
  },
  {
    "id": "en_yahav",
    "name_he": "עין יהב",
    "name_en": "En Yahav",
    "lat": 30.658079,
    "lng": 35.237785,
    "region": "south",
    "type": "town"
  },
  {
    "id": "en_tamar",
    "name_he": "עין תמר",
    "name_en": "En Tamar",
    "lat": 30.944861,
    "lng": 35.368696,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ir_ovot",
    "name_he": "עיר אובות",
    "name_en": "Ir Ovot",
    "lat": 30.810291,
    "lng": 35.245814,
    "region": "south",
    "type": "town"
  },
  {
    "id": "alumim",
    "name_he": "עלומים",
    "name_en": "Alumim",
    "lat": 31.451776,
    "lng": 34.513343,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ammioz",
    "name_he": "עמיעוז",
    "name_en": "Ammi'oz",
    "lat": 31.248597,
    "lng": 34.413512,
    "region": "south",
    "type": "town"
  },
  {
    "id": "arad",
    "name_he": "ערד",
    "name_en": "Arad",
    "lat": 31.2583,
    "lng": 35.2113,
    "region": "south",
    "type": "city"
  },
  {
    "id": "arara_banegev",
    "name_he": "ערערה-בנגב",
    "name_en": "Ar'ara-Banegev",
    "lat": 31.155514,
    "lng": 35.022677,
    "region": "south",
    "type": "town",
    "aliases": [
      "ערוער - ערערה בנגב"
    ]
  },
  {
    "id": "paran",
    "name_he": "פארן",
    "name_en": "Paran",
    "lat": 30.36625,
    "lng": 35.153339,
    "region": "south",
    "type": "town"
  },
  {
    "id": "peduyim",
    "name_he": "פדויים",
    "name_en": "Peduyim",
    "lat": 31.327198,
    "lng": 34.611747,
    "region": "south",
    "type": "town"
  },
  {
    "id": "pattish",
    "name_he": "פטיש",
    "name_en": "Pattish",
    "lat": 31.326534,
    "lng": 34.559431,
    "region": "south",
    "type": "town"
  },
  {
    "id": "paame_tashaz",
    "name_he": "פעמי תש\"ז",
    "name_en": "Pa'ame Tashaz",
    "lat": 31.440256,
    "lng": 34.693229,
    "region": "south",
    "type": "town"
  },
  {
    "id": "peri_gan",
    "name_he": "פרי גן",
    "name_en": "Peri Gan",
    "lat": 31.223033,
    "lng": 34.355854,
    "region": "south",
    "type": "town"
  },
  {
    "id": "zeelim",
    "name_he": "צאלים",
    "name_en": "Ze'elim",
    "lat": 31.203591,
    "lng": 34.534821,
    "region": "south",
    "type": "town"
  },
  {
    "id": "zohar_1136",
    "name_he": "צוחר",
    "name_en": "Zohar",
    "lat": 31.238127,
    "lng": 34.42292,
    "region": "south",
    "type": "town",
    "aliases": [
      "צוחר ואוהד"
    ]
  },
  {
    "id": "zofar",
    "name_he": "צופר",
    "name_en": "Zofar",
    "lat": 30.559963,
    "lng": 35.180337,
    "region": "south",
    "type": "town"
  },
  {
    "id": "mahane_bildad",
    "name_he": "צוקים",
    "name_en": "Mahane Bildad",
    "lat": 30.488326,
    "lng": 35.168248,
    "region": "south",
    "type": "town"
  },
  {
    "id": "qabboa",
    "name_he": "קבועה (שבט)",
    "name_en": "Qabbo'a",
    "lat": 31.238247,
    "lng": 35.16716,
    "region": "south",
    "type": "town"
  },
  {
    "id": "qudeirat_as_sani",
    "name_he": "קודייראת א-צאנע(שבט)",
    "name_en": "Qudeirat As-Sani",
    "lat": 31.295804,
    "lng": 35.115228,
    "region": "south",
    "type": "town"
  },
  {
    "id": "qawain",
    "name_he": "קוואעין (שבט)",
    "name_en": "Qawa'in",
    "lat": 31.324119,
    "lng": 35.026974,
    "region": "south",
    "type": "town"
  },
  {
    "id": "qetura",
    "name_he": "קטורה",
    "name_en": "Qetura",
    "lat": 29.969409,
    "lng": 35.061147,
    "region": "south",
    "type": "town"
  },
  {
    "id": "qelahim",
    "name_he": "קלחים",
    "name_en": "Qelahim",
    "lat": 31.447613,
    "lng": 34.677479,
    "region": "south",
    "type": "town"
  },
  {
    "id": "kasr_as_sirr",
    "name_he": "קצר א-סר",
    "name_en": "Kasr As-Sirr",
    "lat": 31.079116,
    "lng": 34.983087,
    "region": "south",
    "type": "town"
  },
  {
    "id": "revivim",
    "name_he": "רביבים",
    "name_en": "Revivim",
    "lat": 31.04301,
    "lng": 34.721309,
    "region": "south",
    "type": "town"
  },
  {
    "id": "rahat",
    "name_he": "רהט",
    "name_en": "Rahat",
    "lat": 31.388648,
    "lng": 34.755683,
    "region": "south",
    "type": "town"
  },
  {
    "id": "ruah_midbar",
    "name_he": "רוח מדבר",
    "name_en": "Ruah Midbar",
    "lat": 30.981274,
    "lng": 34.733081,
    "region": "south",
    "type": "town"
  },
  {
    "id": "rannen",
    "name_he": "רנן",
    "name_en": "Rannen",
    "lat": 31.3379,
    "lng": 34.600925,
    "region": "south",
    "type": "town"
  },
  {
    "id": "reim",
    "name_he": "רעים",
    "name_en": "Re'im",
    "lat": 31.385585,
    "lng": 34.460033,
    "region": "south",
    "type": "town"
  },
  {
    "id": "retamim",
    "name_he": "רתמים",
    "name_en": "Retamim",
    "lat": 31.053688,
    "lng": 34.689659,
    "region": "south",
    "type": "town"
  },
  {
    "id": "segev_shalom",
    "name_he": "שגב-שלום",
    "name_en": "Segev-Shalom",
    "lat": 31.195584,
    "lng": 34.839079,
    "region": "south",
    "type": "town"
  },
  {
    "id": "sede_boqer",
    "name_he": "שדה בוקר",
    "name_en": "Sede Boqer",
    "lat": 30.871646,
    "lng": 34.793226,
    "region": "south",
    "type": "town"
  },
  {
    "id": "sede_nizzan",
    "name_he": "שדה ניצן",
    "name_en": "Sede Nizzan",
    "lat": 31.229659,
    "lng": 34.4193,
    "region": "south",
    "type": "town"
  },
  {
    "id": "sede_zevi",
    "name_he": "שדה צבי",
    "name_en": "Sede Zevi",
    "lat": 31.449946,
    "lng": 34.71196,
    "region": "south",
    "type": "town"
  },
  {
    "id": "sede_avraham",
    "name_he": "שדי אברהם",
    "name_en": "Sede Avraham",
    "lat": 31.211627,
    "lng": 34.337635,
    "region": "south",
    "type": "town",
    "aliases": [
      "שדה אברהם"
    ]
  },
  {
    "id": "sderot",
    "name_he": "שדרות",
    "name_en": "Sderot",
    "lat": 31.5251,
    "lng": 34.5953,
    "region": "south",
    "type": "city"
  },
  {
    "id": "shuva",
    "name_he": "שובה",
    "name_en": "Shuva",
    "lat": 31.450145,
    "lng": 34.545122,
    "region": "south",
    "type": "town",
    "aliases": [
      "זמרת ושובה"
    ]
  },
  {
    "id": "shoval",
    "name_he": "שובל",
    "name_en": "Shoval",
    "lat": 31.413997,
    "lng": 34.739955,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shomeriyya",
    "name_he": "שומריה",
    "name_en": "Shomeriyya",
    "lat": 31.431753,
    "lng": 34.884172,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shoqeda",
    "name_he": "שוקדה",
    "name_en": "Shoqeda",
    "lat": 31.422546,
    "lng": 34.524496,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shaharut",
    "name_he": "שחרות",
    "name_en": "Shaharut",
    "lat": 29.904599,
    "lng": 35.000326,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shibbolim",
    "name_he": "שיבולים",
    "name_en": "Shibbolim",
    "lat": 31.396376,
    "lng": 34.607628,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shezaf",
    "name_he": "שיזף",
    "name_en": "Shezaf",
    "lat": 31.001631,
    "lng": 34.765562,
    "region": "south",
    "type": "town"
  },
  {
    "id": "nahal_shittim",
    "name_he": "שיטים",
    "name_en": "Nahal Shittim",
    "lat": 30.176961,
    "lng": 35.016422,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shlomit",
    "name_he": "שלומית",
    "name_en": "Shlomit",
    "lat": 31.169398,
    "lng": 34.304867,
    "region": "south",
    "type": "town"
  },
  {
    "id": "shani",
    "name_he": "שני",
    "name_en": "Shani",
    "lat": 31.355912,
    "lng": 35.069729,
    "region": "south",
    "type": "town",
    "aliases": [
      "שני ליבנה"
    ]
  },
  {
    "id": "sharsheret",
    "name_he": "שרשרת",
    "name_en": "Sharsheret",
    "lat": 31.404334,
    "lng": 34.603639,
    "region": "south",
    "type": "town"
  },
  {
    "id": "teashur",
    "name_he": "תאשור",
    "name_en": "Te'ashur",
    "lat": 31.371524,
    "lng": 34.643751,
    "region": "south",
    "type": "town"
  },
  {
    "id": "tidhar",
    "name_he": "תדהר",
    "name_en": "Tidhar",
    "lat": 31.3785,
    "lng": 34.626722,
    "region": "south",
    "type": "town"
  },
  {
    "id": "tushiyya",
    "name_he": "תושיה",
    "name_en": "Tushiyya",
    "lat": 31.433694,
    "lng": 34.540891,
    "region": "south",
    "type": "town"
  },
  {
    "id": "tel_sheva",
    "name_he": "תל שבע",
    "name_en": "Tel Sheva",
    "lat": 31.248204,
    "lng": 34.861882,
    "region": "south",
    "type": "town"
  },
  {
    "id": "talme_eliyyahu",
    "name_he": "תלמי אליהו",
    "name_en": "Talme Eliyyahu",
    "lat": 31.22801,
    "lng": 34.4295,
    "region": "south",
    "type": "town"
  },
  {
    "id": "talme_bilu",
    "name_he": "תלמי ביל\"ו",
    "name_en": "Talme Bilu",
    "lat": 31.438041,
    "lng": 34.645976,
    "region": "south",
    "type": "town"
  },
  {
    "id": "talme_yosef",
    "name_he": "תלמי יוסף",
    "name_en": "Talme Yosef",
    "lat": 31.197162,
    "lng": 34.362452,
    "region": "south",
    "type": "town"
  },
  {
    "id": "tifrah",
    "name_he": "תפרח",
    "name_en": "Tifrah",
    "lat": 31.325636,
    "lng": 34.677045,
    "region": "south",
    "type": "town"
  },
  {
    "id": "tequma",
    "name_he": "תקומה",
    "name_en": "Tequma",
    "lat": 31.450983,
    "lng": 34.579894,
    "region": "south",
    "type": "town",
    "aliases": [
      "תקומה וחוות יזרעם"
    ]
  },
  {
    "id": "tarabin_as_sani",
    "name_he": "תראבין א-צאנע (שבט)",
    "name_en": "Tarabin As-Sani",
    "lat": 31.166765,
    "lng": 34.816486,
    "region": "south",
    "type": "town"
  },
  {
    "id": "tarabin_as_sani_1346",
    "name_he": "תראבין א-צאנע(ישוב)",
    "name_en": "Tarabin As-Sani",
    "lat": 31.344332,
    "lng": 34.738564,
    "region": "south",
    "type": "town",
    "aliases": [
      "תארבין"
    ]
  },
  {
    "id": "shave_darom",
    "name_he": "שבי דרום",
    "name_en": "Shavei Darom",
    "lat": 31.465253,
    "lng": 34.635639,
    "region": "south",
    "type": "moshav"
  }
];
