import type { Settlement } from '../../types';

// Generated by `npm run settlements:generate-regions`.
export const settlements: Settlement[] = [
  {
    "id": "or_yehuda",
    "name_he": "אור יהודה",
    "name_en": "Or Yehuda",
    "lat": 32.0292,
    "lng": 34.8549,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "azor",
    "name_he": "אזור",
    "name_en": "Azor",
    "lat": 32.0284,
    "lng": 34.7993,
    "region": "tel_aviv",
    "type": "local_council"
  },
  {
    "id": "bnei_brak",
    "name_he": "בני ברק",
    "name_en": "Bnei Brak",
    "lat": 32.0834,
    "lng": 34.8342,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "bat_yam",
    "name_he": "בת ים",
    "name_en": "Bat Yam",
    "lat": 32.0166,
    "lng": 34.7515,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "givatayim",
    "name_he": "גבעתיים",
    "name_en": "Givatayim",
    "lat": 32.0715,
    "lng": 34.8122,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "gelil_yam",
    "name_he": "גליל ים",
    "name_en": "Gelil Yam",
    "lat": 32.157675,
    "lng": 34.830731,
    "region": "tel_aviv",
    "type": "town"
  },
  {
    "id": "holon",
    "name_he": "חולון",
    "name_en": "Holon",
    "lat": 32.011,
    "lng": 34.7748,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "kefar_shemaryahu",
    "name_he": "כפר שמריהו",
    "name_en": "Kefar Shemaryahu",
    "lat": 32.186425,
    "lng": 34.820895,
    "region": "tel_aviv",
    "type": "town"
  },
  {
    "id": "miqwe_yisrael",
    "name_he": "מקווה ישראל",
    "name_en": "Miqwe Yisra'el",
    "lat": 32.029022,
    "lng": 34.783587,
    "region": "tel_aviv",
    "type": "town"
  },
  {
    "id": "qiryat_ono",
    "name_he": "קרית אונו",
    "name_en": "Qiryat Ono",
    "lat": 32.059202,
    "lng": 34.858603,
    "region": "tel_aviv",
    "type": "town"
  },
  {
    "id": "ramat_gan",
    "name_he": "רמת גן",
    "name_en": "Ramat Gan",
    "lat": 32.0832,
    "lng": 34.8147,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "ramat_hasharon",
    "name_he": "רמת השרון",
    "name_en": "Ramat HaSharon",
    "lat": 32.1463,
    "lng": 34.8396,
    "region": "tel_aviv",
    "type": "city"
  },
  {
    "id": "tel_aviv",
    "name_he": "תל אביב-יפו",
    "name_en": "Tel Aviv",
    "lat": 32.0853,
    "lng": 34.7818,
    "region": "tel_aviv",
    "type": "city",
    "aliases": [
      "תל אביב"
    ]
  }
];
