import type { BoundaryDistrictId } from './byDistrict/loaders';
import type { BoundaryRegionId } from './loaders';

// Generated by `npm run boundaries:generate-load-metadata`.
export const boundaryDistrictEstimatedBytes: Record<BoundaryDistrictId, number> = {
  "אילת": 5877,
  "בית שמש": 127652,
  "בקעת בית שאן": 42530,
  "בקעה": 34294,
  "גולן": 35654,
  "גליל עליון": 154272,
  "דרום הנגב": 80446,
  "דן": 34110,
  "גליל תחתון": 175038,
  "דרום השפלה": 48329,
  "השפלה": 126706,
  "ואדי ערה": 46711,
  "חפר": 128047,
  "חוף הכרמל": 29662,
  "חיפה": 13635,
  "ים המלח": 8233,
  "יהודה": 136971,
  "יערות הכרמל": 8705,
  "ירושלים": 4689,
  "ירקון": 42811,
  "מערב הנגב": 59171,
  "מנשה": 80748,
  "לכיש": 140006,
  "מערב לכיש": 33096,
  "מרכז הנגב": 33936,
  "ערבה": 23970,
  "עוטף עזה": 76139,
  "קצרין": 19200,
  "קו העימות": 142244,
  "קריות": 39799,
  "שומרון": 187750,
  "שרון": 71641,
  "תבור": 212510,
};

// Generated by `npm run boundaries:generate-load-metadata`.
export const boundaryRegionEstimatedBytes: Record<BoundaryRegionId, number> = {
  "center": 414405,
  "haifa": 215631,
  "jerusalem": 143671,
  "judea_samaria": 236033,
  "north": 843754,
  "shephelah": 221543,
  "south": 285984,
  "tel_aviv": 35198,
};

// Generated by `npm run boundaries:generate-load-metadata`.
export const kmlSupplementEstimatedBytes = 70660;
