import type { SettlementRegionId } from './settlementCatalogRegions/loaders';

// Generated by `npm run settlements:generate-regions`.
export const districtSourceRegions: Record<string, SettlementRegionId[]> = {
  "אילת": [
    "south"
  ],
  "בית שמש": [
    "jerusalem",
    "judea_samaria"
  ],
  "בקעה": [
    "judea_samaria"
  ],
  "בקעת בית שאן": [
    "north"
  ],
  "גולן": [
    "north"
  ],
  "גליל עליון": [
    "north"
  ],
  "גליל תחתון": [
    "haifa",
    "north"
  ],
  "דן": [
    "center",
    "tel_aviv"
  ],
  "דרום הנגב": [
    "shephelah",
    "south"
  ],
  "דרום השפלה": [
    "center",
    "shephelah"
  ],
  "השפלה": [
    "center",
    "judea_samaria",
    "south"
  ],
  "ואדי ערה": [
    "haifa",
    "south"
  ],
  "חוף הכרמל": [
    "haifa"
  ],
  "חיפה": [
    "haifa"
  ],
  "חפר": [
    "center",
    "haifa",
    "shephelah"
  ],
  "יהודה": [
    "jerusalem",
    "judea_samaria",
    "shephelah",
    "south"
  ],
  "ים המלח": [
    "judea_samaria",
    "south"
  ],
  "יערות הכרמל": [
    "haifa"
  ],
  "ירושלים": [
    "judea_samaria"
  ],
  "ירקון": [
    "center"
  ],
  "לכיש": [
    "center",
    "jerusalem",
    "shephelah"
  ],
  "מנשה": [
    "haifa",
    "north"
  ],
  "מערב הנגב": [
    "shephelah",
    "south"
  ],
  "מערב לכיש": [
    "shephelah",
    "south"
  ],
  "מרכז הנגב": [
    "shephelah",
    "south"
  ],
  "עוטף עזה": [
    "shephelah",
    "south"
  ],
  "ערבה": [
    "south"
  ],
  "קו העימות": [
    "north"
  ],
  "קצרין": [
    "north"
  ],
  "קריות": [
    "haifa",
    "north"
  ],
  "שומרון": [
    "jerusalem",
    "judea_samaria"
  ],
  "שרון": [
    "center",
    "tel_aviv"
  ],
  "תבור": [
    "haifa",
    "north"
  ]
};
